// v10.1 pinout / usage reference panel, new examples and wire colours — English
I18N.add('en', {
  "help.btn": "Pinout",
  "help.title": "Pinout & usage",
  "help.intro.arduino": "Arduino Uno R3 (ATmega328P, 16 MHz, 5 V logic): 14 digital pins D0–D13 (6 of them marked ~ can output PWM) and 6 analog inputs A0–A5 (10-bit ADC, also usable as digital pins D14–D19). Below: the pin map, what every pin does, electrical limits, what the simulator supports, common usage, and finally examples you can load with one click.",
  "help.intro.attiny85": "ATtiny85 (8-pin DIP, 8-bit AVR): 5 general-purpose I/O pins PB0–PB4 plus PB5 (RESET by default). No hardware UART; PWM on PB0/PB1/PB4, ADC on PB2/PB3/PB4 (and PB5). 8 KB Flash, 512 B SRAM, 512 B EEPROM; shipped running from the internal 8 MHz RC oscillator divided by 8 = 1 MHz (CKDIV8 fuse).",
  "help.nav.pinout": "Pin map",
  "help.nav.table": "Pin table",
  "help.nav.limits": "Electrical limits",
  "help.nav.sim": "Simulator support",
  "help.nav.usage": "Common usage",
  "help.nav.examples": "Examples",
  "help.cat.dig": "Digital I/O",
  "help.cat.pwm": "PWM output",
  "help.cat.ana": "Analog input",
  "help.cat.com": "Communication (UART/SPI/I²C)",
  "help.cat.int": "External interrupt",
  "help.cat.pwr": "Power",
  "help.cat.gnd": "Ground",
  "help.cat.spc": "Special function",
  "help.leg.nosim": "Dashed = not simulated",
  "help.th.pin": "Pin",
  "help.th.func": "Functions & notes",
  "help.th.sim": "Simulated",
  "help.sim.yes": "yes",
  "help.sim.part": "partly",
  "help.sim.no": "no",
  "help.sim.absent": "pin not on the part",
  "help.tag.dio": "digital in/out",
  "help.tag.pwm490": "PWM ≈ 490 Hz",
  "help.tag.pwm980": "PWM ≈ 980 Hz",
  "help.tag.tpwm": "PWM output (analogWrite)",
  "help.tag.adc": "analog input (10-bit ADC)",
  "help.tag.rx": "serial receive RX",
  "help.tag.tx": "serial transmit TX",
  "help.tag.int0": "external interrupt INT0",
  "help.tag.int1": "external interrupt INT1",
  "help.tag.ss": "SPI slave select SS",
  "help.tag.mosi": "SPI MOSI (master out)",
  "help.tag.miso": "SPI MISO (master in)",
  "help.tag.sck": "SPI clock SCK",
  "help.tag.sda": "I²C data SDA",
  "help.tag.scl": "I²C clock SCL",
  "help.tag.led": "on-board LED “L”",
  "help.tag.aref": "analog reference AREF",
  "help.tag.ioref": "I/O voltage reference IOREF",
  "help.tag.reset": "reset (active low)",
  "help.tag.treset": "RESET (active low)",
  "help.tag.v5": "5 V supply",
  "help.tag.v33": "3.3 V supply output",
  "help.tag.vin": "external supply input VIN",
  "help.tag.gnd": "ground GND",
  "help.tag.vcc": "supply VCC",
  "help.tag.usi_di": "USI data in DI / I²C SDA",
  "help.tag.usi_do": "USI data out DO",
  "help.tag.usi_sck": "USI clock USCK / I²C SCL",
  "help.tag.xtal": "external crystal pin",
  "help.tag.ain": "analog comparator input",
  "help.tag.taref": "external reference AREF",
  "help.tag.tled": "on-board LED on Digispark-type boards",
  "help.tag.icsp": "ICSP programming header",
  "help.note.d0d1": "D0/D1 are wired to the board's USB-serial chip: uploading and `Serial` both use them, and external circuits on them can make uploads fail. In the simulator D0/D1 work as plain I/O and `Serial` goes straight to the serial monitor.",
  "help.note.tone": "`tone()` uses Timer2, so PWM on D3 and D11 stops working while a tone plays.",
  "help.note.servo": "The Servo library uses Timer1, so `analogWrite()` no longer works on D9 and D10 (whichever pin the servo is on).",
  "help.note.d13": "The on-board LED “L” is driven by D13 (`LED_BUILTIN`), buffered by an op-amp on the R3. D13 is also SPI SCK, so the LED flickers while SPI is in use.",
  "help.note.a4a5": "A4/A5 are also the I²C SDA/SCL pins (the R3 repeats them as an SDA/SCL header next to AREF). While I²C is in use they cannot be analog inputs.",
  "help.note.v5": "Comes from the on-board 5 V regulator (when powered through VIN/DC) or from USB. Fine for sensors and small modules; on USB the whole board is limited by a 500 mA resettable fuse. You can also feed a regulated 5 V in here, but that bypasses the regulator and protection.",
  "help.note.v33": "On-board 3.3 V regulator output, 50 mA max.",
  "help.note.vin": "External supply input (the DC jack reaches it through a diode): 7–12 V recommended, 6–20 V limits. Below 7 V the 5 V rail may sag; above 12 V the regulator runs hot.",
  "help.note.gnd": "All GND pins are connected. The negative side of any external supply (battery, motor supply) must be joined to the Arduino GND (common ground) so signals share a reference.",
  "help.note.reset": "Pull low to reset; the reset button is wired here. The simulated part has no such pin — use the “Reset” button in the program editor instead.",
  "help.note.aref": "External analog reference input (0–5 V) for `analogReference(EXTERNAL)`; select EXTERNAL before connecting a voltage or the chip may be damaged. The simulated part has no such pin and treats EXTERNAL as VCC (5 V).",
  "help.note.ioref": "Tells shields the board's I/O voltage (5 V on the Uno). Not on the simulated part.",
  "help.note.sdascl": "Extra I²C header added on the R3, electrically the same as A4/A5. I²C (the Wire library) is not simulated.",
  "help.note.icsp": "6-pin in-circuit serial programming header, used to burn the bootloader or upload with a programmer. Not needed in the simulator.",
  "help.note.pb5": "RESET by default (active low, internal pull-up), so it is not a normal I/O pin; in the simulator pulling it below 0.3·VCC holds the chip in reset. Only programming the RSTDISBL fuse turns it into a (weak) I/O pin, and after that ISP programming no longer works until a high-voltage programmer restores it. In the simulator you can tick “PB5 as normal I/O” in the properties.",
  "help.note.pb34": "PB3/PB4 are also the external crystal pins and cannot be used as I/O with an external crystal. The default clock is the internal RC oscillator, so they are free.",
  "help.note.pb0": "Physical pin 5: PWM (OC0A), USI DI / I²C SDA, MOSI for ISP programming, and the optional external AREF (then it is no longer an I/O pin).",
  "help.note.pb1": "Physical pin 6: PWM (OC0B / OC1A), USI DO, MISO for ISP programming. Boards such as the Digispark put their on-board LED here.",
  "help.note.pb2": "Physical pin 7: the only external interrupt INT0, analog input A1 (ADC1), USI clock USCK / I²C SCL, SCK for ISP programming.",
  "help.note.vcc": "Supply 2.7–5.5 V (ATtiny85V: 1.8–5.5 V); faster clocks need more voltage (20 MHz needs 4.5 V or more). Put a 100 nF decoupling capacitor between VCC and GND close to the chip.",
  "help.lim.arduino.1": "Each I/O pin: 20 mA recommended, 40 mA absolute maximum — more can permanently damage the port.",
  "help.lim.arduino.2": "Total current of all pins together (through VCC/GND) at most 200 mA.",
  "help.lim.arduino.3": "Pin voltage must stay within −0.5 V … VCC + 0.5 V; input LOW < 0.3·VCC (1.5 V), HIGH > 0.6·VCC (3 V).",
  "help.lim.arduino.4": "Internal pull-up resistors 20–50 kΩ (`INPUT_PULLUP`).",
  "help.lim.arduino.5": "Analog inputs 0–5 V (default reference = VCC), 10 bits → 0–1023, about 4.9 mV per step; source impedance should be ≤ 10 kΩ.",
  "help.lim.arduino.6": "VIN / DC jack: 7–12 V recommended, 6–20 V limits; USB supplies 5 V through a 500 mA resettable fuse.",
  "help.lim.arduino.7": "3.3V pin: 50 mA max; how much the 5V pin can deliver depends on the supply (whole board ≤ 500 mA on USB, limited by regulator heating on VIN).",
  "help.lim.arduino.8": "ATmega328P: 16 MHz, 32 KB Flash (0.5 KB used by the bootloader), 2 KB SRAM, 1 KB EEPROM.",
  "help.lim.attiny85.1": "Each I/O pin: ≤ 20 mA recommended, 40 mA absolute maximum; total through VCC/GND ≤ 200 mA.",
  "help.lim.attiny85.2": "Supply 2.7–5.5 V (ATtiny85V: 1.8–5.5 V); up to 10 MHz from 2.7 V, 20 MHz needs 4.5–5.5 V.",
  "help.lim.attiny85.3": "Pin voltage −0.5 V … VCC + 0.5 V; internal pull-ups 20–50 kΩ.",
  "help.lim.attiny85.4": "ADC: 10 bits, 4 single-ended inputs ADC0–ADC3 = PB5 / PB2 / PB4 / PB3; reference VCC, internal 1.1 V, internal 2.56 V or external AREF on PB0.",
  "help.lim.attiny85.5": "Memory: 8 KB Flash, 512 B SRAM, 512 B EEPROM.",
  "help.lim.attiny85.6": "Clock: shipped as internal 8 MHz RC ÷ 8 = 1 MHz (CKDIV8 fuse); can be changed to internal 8 MHz, 16 MHz PLL, or an external crystal (uses PB3/PB4).",
  "help.sim.ok": "Simulated: `pinMode` / `digitalWrite` / `digitalRead` (including `INPUT_PULLUP`), `analogRead` (10-bit), `analogWrite` (PWM at the real chip's frequency), `millis` / `micros` / `delay`, `tone` / `noTone`, `pulseIn`, `shiftOut`, Servo, LiquidCrystal, `Serial` (serial monitor) and more. Pin output resistance, pull-ups and currents are part of the circuit solution, and more than 40 mA on a pin raises a warning.",
  "help.sim.no.1": "External interrupts `attachInterrupt()`: reported as unsupported when compiling — poll the pin or use `millis()` instead.",
  "help.sim.no.2": "Pin-level timing of I²C (Wire library), the SPI library and the UART: the communication functions of D0/D1, A4/A5 and D10–D13 are not modelled; `Serial` only talks to the serial monitor.",
  "help.sim.no.3": "Timer side effects of libraries (tone disabling PWM on D3/D11, Servo disabling PWM on D9/D10) are only documented here; the simulator does not reproduce them.",
  "help.sim.no.4": "The Uno part has no RESET, AREF, IOREF, separate SDA/SCL header or ICSP header; `analogReference(EXTERNAL)` uses VCC, `INTERNAL` = 1.1 V.",
  "help.sim.no.5": "The ATtiny85 has no hardware UART: `Serial` in the simulator is virtual and only sends debug text to the serial monitor.",
  "help.sim.no.6": "Over-current does not “burn” the chip: the simulator only warns, so check your design against the electrical limits.",
  "help.sim.no.7": "EEPROM, sleep modes, the watchdog, fuse settings and direct register access (such as `PORTB`, `DDRB`) are not supported.",
  "help.sim.no.8": "Instruction timing is not modelled: code runs instantly and only `delay()`, `millis()` and friends advance time; an endless loop that exceeds the work limit stops with an error.",
  "help.usage.intro": "Each section gives the wiring essentials and a snippet you can copy, plus links to related examples.",
  "help.u.power.t": "Powering the board",
  "help.u.power.1": "The Uno can be powered three ways: ① USB 5 V (simplest, whole board ≤ 500 mA); ② 7–12 V into the DC jack or VIN, regulated to 5 V on the board; ③ a regulated 5 V straight into the 5V pin (bypasses the regulator and protection — a mistake can destroy the board). In the simulator pick USB or VIN power in the properties.",
  "help.u.power.2": "The 5V and 3.3V pins can power sensors and small modules, but not motors, several servos or high-power LEDs: those loads pull the voltage down and reset the microcontroller. Give heavy loads their own supply and connect its negative side to the Arduino GND (common ground).",
  "help.u.power.3": "The ATtiny85 is just a chip with no regulator: VCC goes directly to 2.7–5.5 V, for example 3 × AA cells (4.5 V), USB 5 V or a single Li-ion cell (3.0–4.2 V). If the voltage is too low the chip does not start (the simulator shows OFF); above 5.5 V it may be damaged.",
  "help.u.power.4": "Place a 100 nF decoupling capacitor between VCC and GND right next to every chip. Motors and other inductive loads are best run from a separate supply, or at least with generous filter capacitance.",
  "help.u.dout.t": "Digital output & LED resistors",
  "help.u.dout.1": "Call `pinMode(pin, OUTPUT)`, then `digitalWrite(pin, HIGH)` / `LOW` outputs about 5 V / 0 V. An output can both source and sink current; keep it at 20 mA or less per pin.",
  "help.u.dout.2": "An LED always needs a series resistor: R = (Vcc − Vf) / I. Example: 5 V, red LED Vf ≈ 2 V, 10 mA → R = (5 − 2) / 0.01 = 300 Ω, use the standard 330 Ω; 220 Ω (about 14 mA) is fine too. Blue and white LEDs have Vf ≈ 3 V and need about 200 Ω for the same current.",
  "help.u.dout.3": "Long leg (anode +) through the resistor to the pin, short leg (cathode −) to GND: HIGH = on. Or connect the LED to 5V and let the pin sink the current: LOW = on. To drive several LEDs or anything above 20 mA from one pin, use a transistor or MOSFET.",
  "help.u.din.t": "Button input: pull-up, pull-down & debouncing",
  "help.u.din.1": "`INPUT_PULLUP` enables the internal 20–50 kΩ pull-up: wire the button between the pin and GND, no external resistor needed. Released reads HIGH, pressed reads LOW (inverted logic). This is the simplest wiring.",
  "help.u.din.2": "Pull-down wiring: button between 5V and the pin, plus 10 kΩ from the pin to GND, with `pinMode(pin, INPUT)`; pressed reads HIGH. In `INPUT` mode a floating pin reads random values, so a pull-up or pull-down is mandatory.",
  "help.u.din.3": "Mechanical buttons bounce for a few milliseconds when pressed or released, so one press can be read as several. Debounce by accepting a change only after it has been stable for 20–50 ms (time it with `millis()`, not a long `delay()`), or add an RC filter in hardware. The “Debounced button” example shows software debouncing.",
  "help.u.ain.t": "Analog input: potentiometer, divider, LDR / NTC",
  "help.u.ain.1": "`analogRead(A0)` returns 0–1023 for 0 V up to the reference (default VCC = 5 V): volts = reading × 5.0 / 1024. One conversion takes about 100 µs. `analogReference(INTERNAL)` switches to the internal 1.1 V reference for small voltages.",
  "help.u.ain.2": "Potentiometer: ends to 5V and GND, wiper to A0; turning it sweeps the reading over 0–1023. Voltage divider: Vout = Vin × R2 / (R1 + R2) brings voltages above 5 V (such as a 12 V battery) down to 0–5 V for measuring — make sure the input never exceeds VCC.",
  "help.u.ain.3": "A photoresistor (LDR) or thermistor (NTC) goes in series with a fixed resistor as a divider, the midpoint to the analog pin; choose the fixed resistor near the sensor's mid-range value, typically 10 kΩ. With the LDR at the bottom, darker means a higher voltage; an NTC's resistance falls as it warms up. `map()` converts the reading into the range you need.",
  "help.u.ain.4": "The ADC wants a source impedance ≤ 10 kΩ; with a high-value divider the reading jitters — add 100 nF from the analog pin to GND. A0–A5 also work as ordinary digital pins (D14–D19). On the ATtiny85 the analog pins are A1 (PB2), A2 (PB4) and A3 (PB3); A0 (PB5) is the reset pin and normally not used.",
  "help.u.pwm.t": "PWM: dimming & speed control",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` outputs a PWM square wave on pins marked ~: duty = value / 255, average voltage ≈ 5 V × value / 255. On the Uno D5 and D6 run at about 980 Hz, D3, D9, D10 and D11 at about 490 Hz; on the ATtiny85 use PB0, PB1 or PB4.",
  "help.u.pwm.2": "PWM is ideal for LED brightness (the eye sees the average) and motor speed; it is not a true analog voltage — add an RC low-pass filter if you need a smooth one. On a pin without ~, `analogWrite()` outputs LOW for values < 128 and HIGH otherwise.",
  "help.u.pwm.3": "0 and 255 give a steady LOW / HIGH. Perceived brightness is non-linear, so a squared curve makes fades look smoother. Watch the PWM waveform on the oscilloscope (example “Potentiometer dimmer”).",
  "help.u.motor.t": "Motors: transistor / MOSFET driver & flyback diode",
  "help.u.motor.1": "A pin delivers only about 20 mA and cannot run a motor directly. Use an NPN transistor or N-channel MOSFET as a low-side switch: load between supply + and the drain (D), source (S) to GND, gate (G) through 100–220 Ω to a PWM pin, plus 10 kΩ from gate to GND so the motor stays off while the pin floats during power-up or reset.",
  "help.u.motor.2": "Choose a logic-level MOSFET (such as the IRLZ44N, fully on at 5 V gate drive); standard parts like the IRF540 are specified at 10 V gate drive and run hot when only half on at 5 V. With a transistor put about 1 kΩ in series with the base.",
  "help.u.motor.3": "Motors, relay coils and solenoids are inductive: switching them off produces a large reverse voltage spike, so a flyback diode (such as a 1N4007, cathode to supply +) must sit across the load. The motor supply's negative side must be joined to the Arduino GND. For forward/reverse use an H-bridge driver (L298N, TB6612…).",
  "help.u.relay.t": "Relays & higher loads",
  "help.u.relay.1": "A relay uses a small coil current to switch high-current, high-voltage contacts: COM is common, NO is normally open (connected to COM while the coil is energised), NC normally closed. The contact circuit is isolated from the microcontroller, so it can switch a 12 V lamp or mains appliances.",
  "help.u.relay.2": "Relay modules contain the transistor, flyback diode and indicator LED: VCC/GND to 5V/GND, IN to any digital pin. Mind the trigger level — many modules are active low (they pull in when IN = LOW); the simulated module lets you choose high or low trigger in its properties.",
  "help.u.relay.3": "A bare relay coil usually draws 70 mA or more, so it cannot hang on a pin directly: drive it through a transistor with a flyback diode. Mains voltage is dangerous — use an enclosed ready-made module and respect the contact current rating.",
  "help.u.tone.t": "Buzzers & tone()",
  "help.u.tone.1": "`tone(pin, frequency)` outputs a 50 % square wave on any digital pin, `tone(pin, frequency, duration)` stops by itself, `noTone(pin)` stops it. Only one `tone()` can play at a time; it uses Timer2 and disables PWM on D3/D11.",
  "help.u.tone.2": "Passive buzzers and small speakers need the square wave from `tone()` to make sound, and the frequency sets the pitch; an active buzzer has its own oscillator and beeps on `digitalWrite(HIGH)`, but at a fixed pitch.",
  "help.u.tone.3": "Put about 100 Ω in series with a buzzer; an 8 Ω speaker draws far too much and needs a transistor. Common note frequencies: C4 262, D4 294, E4 330, F4 349, G4 392, A4 440, B4 494, C5 523 Hz.",
  "help.u.servo.t": "Servos",
  "help.u.servo.1": "A servo has three wires: signal (orange/yellow), supply + (red), GND (brown/black). The signal is a pulse every 20 ms or so (50 Hz); pulse widths of typically 1–2 ms set the angle, and the Servo library maps 544–2400 µs to 0–180° by default. Use `attach(pin)`, then `write(angle)`.",
  "help.u.servo.2": "The Servo library uses Timer1, so D9 and D10 lose PWM (the signal wire itself can go to any digital pin). An Uno can drive up to 12 servos.",
  "help.u.servo.3": "Servos draw hundreds of mA, even over 1 A, when starting or stalled. One small servo like the SG90 can run from the 5V pin; several or larger servos need their own 5–6 V supply with a common ground, and 100–470 µF across the servo supply helps prevent resets.",
  "help.u.lcd.t": "LCD1602 display",
  "help.u.lcd.1": "The LCD1602 (HD44780 controller) needs only 6 signal lines in 4-bit mode: RS, E, D4–D7, with RW tied to GND (write only); the 7-argument form drives RW from a pin as well. `LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`, then `lcd.begin(16, 2)`, `lcd.setCursor(col, row)`, `lcd.print()`, `lcd.clear()`.",
  "help.u.lcd.2": "Power: VSS to GND, VDD to 5V; V0 sets the contrast, usually from the wiper of a 10 kΩ potentiometer (ends to 5V/GND) — if it is off you see solid blocks or nothing at all. A/K are the backlight LED: A to 5V through a resistor (many modules have one built in) or to a pin to switch it, K to GND.",
  "help.u.lcd.3": "Short of pins? An I²C backpack (PCF8574, only A4/A5) helps on real hardware, but this simulator has no I²C, so use the parallel wiring. Rows and columns count from 0: the second line is `setCursor(0, 1)`.",
  "help.u.serial.t": "Serial debugging",
  "help.u.serial.1": "`Serial.begin(9600)` opens the port (the baud rate must match the serial monitor), `Serial.print()` / `println()` send text and numbers. It is the most common way to debug: print variables, which branch ran, sensor readings.",
  "help.u.serial.2": "`Serial.available()` returns the number of bytes received, `Serial.read()` reads one byte, `Serial.readStringUntil('\\n')` reads a line. In the simulator type into the serial monitor's input box to send text.",
  "help.u.serial.3": "On the Uno the serial port uses D0/D1 — keep other circuits off those pins while using it. Printing too often slows the program (9600 baud is about 1 character per millisecond), so pace it with `millis()`. The ATtiny85 has no hardware UART; its `Serial` in the simulator is for debugging only.",
  "help.u.millis.t": "Non-blocking timing with millis()",
  "help.u.millis.1": "During `delay()` the program can do nothing else (no button reading, no other LEDs). `millis()` returns the milliseconds since power-up; checking “now − last ≥ interval” lets you handle several things at once.",
  "help.u.millis.2": "Use `unsigned long` for time variables. Comparing by subtraction, `millis() - last >= INTERVAL`, stays correct when the counter wraps after about 49.7 days; do not write `millis() >= last + INTERVAL`.",
  "help.u.millis.3": "One time variable per task gives a simple state machine: the “millis() multitasking” example blinks two LEDs at different rates while printing the uptime, and the debounced button uses the same idea. Use `micros()` for microsecond resolution.",
  "help.ex.examples": "Related examples",
  "help.ex.intro": "“Load to canvas” replaces the current circuit and starts the simulation; “Insert into editor” puts the code into the current chip's program editor (not uploaded yet, so you can edit it first); “Copy code” copies it to the clipboard.",
  "help.ex.wiring": "Wiring",
  "help.ex.usage": "Related usage",
  "help.ex.code": "Code",
  "help.ex.load": "Load to canvas",
  "help.ex.insert": "Insert into editor",
  "help.ex.copy": "Copy code",
  "help.ex.other": "Show the {board} examples ({n}) →",
  "help.toast.inserted": "Code inserted into the {chip} editor — click “Compile & upload” to apply it",
  "help.toast.mismatch": "Inserted, but this code was written for the {board}; the pins may not match",
  "help.toast.copied": "Code copied to the clipboard",
  "help.toast.copy_failed": "Copy failed — select the code in the box and copy it manually",
  "help.toast.no_chip": "There is no microcontroller on the canvas: place a board or chip first, or use “Load to canvas”",
  "help.w.anode": "anode (+, long leg)",
  "help.w.cathode": "cathode (−)",
  "help.w.onboard_led": "on-board LED (L)",
  "help.w.red_led": "red LED",
  "help.w.yellow_led": "yellow LED",
  "help.w.green_led": "green LED",
  "help.w.white_led": "white LED",
  "help.w.all_cathodes": "all LED cathodes",
  "help.w.internal_pullup": "internal pull-up",
  "help.w.pot_ends": "ends",
  "help.w.wiper": "wiper",
  "help.w.gate": "gate G",
  "help.w.drain": "drain D",
  "help.w.source": "source S",
  "help.w.flyback": "across the motor, reversed (cathode to +), as flyback diode",
  "help.w.common_gnd": "common ground",
  "help.w.servo_sig": "signal wire",
  "help.w.servo_vcc": "power wire",
  "help.w.servo_gnd": "ground wire",
  "help.w.backlight": "backlight",
  "help.w.contrast": "contrast",
  "help.w.pin_n4": "pin 4",
  "help.w.pin_n5": "pin 5",
  "help.w.pin_n6": "pin 6",
  "help.w.pin_n8": "pin 8",
  "ex.arddebounce": "MCU: debounced button toggles an LED (millis)",
  "ex.ardnight": "MCU: LDR night light (LDR → PWM)",
  "ex.ardmulti": "MCU: millis() multitasking (no delay)",
  "ex.ardmotor": "MCU: DC motor speed control with a MOSFET (PWM)",
  "ex.ardrelay": "MCU: relay module switches a 12 V lamp on a timer",
  "ex.ardtone": "MCU: melody on a passive buzzer (tone)",
  "ex.tinyfade": "MCU: ATtiny85 PWM fade",
  "exd.arddebounce": "Each press of the button on D2 toggles the LED on D8: the input must be stable for 30 ms before a change counts, so bounce cannot toggle it twice; the press count is printed on the serial monitor.",
  "exd.ardnight": "5V → 10 kΩ → A0 → photoresistor → GND forms a divider: the darker it is, the higher the reading and the brighter the white LED on PWM pin D9. Change the photoresistor's “Light intensity” property to try it.",
  "exd.ardmulti": "No delay() at all: the LED on D8 toggles every 250 ms, the LED on D7 every 700 ms, and the uptime is printed every second — three tasks running at the same time.",
  "exd.ardmotor": "Potentiometer → A0 → PWM on D9 → logic-level MOSFET IRLZ44N → DC motor. The motor has its own 6 V battery sharing ground with the Arduino, and a 1N4007 flyback diode absorbs the turn-off spike.",
  "exd.ardrelay": "D7 drives a relay module (high-level trigger) that turns a 12 V lamp on for 2 s and off for 2 s. The lamp circuit is isolated from the Arduino; the pin only supplies a few mA.",
  "exd.ardtone": "D8 drives a passive buzzer through 100 Ω and plays a 16-step melody with tone() (0 = rest); each note's frequency is printed on the serial monitor.",
  "exd.tinyfade": "The ATtiny85 outputs PWM on PB0 (pin 5) and PB1 (pin 6): the yellow LED fades in while the green one fades out, over and over.",
  "wc.title": "Wire colour",
  "wc.n_wires": "{n} wires selected",
  "wc.red": "Red",
  "wc.black": "Black",
  "wc.blue": "Blue",
  "wc.green": "Green",
  "wc.yellow": "Yellow",
  "wc.orange": "Orange",
  "wc.white": "White",
  "wc.purple": "Purple",
  "wc.gray": "Grey",
  "wc.brown": "Brown",
  "wc.custom": "Custom colour…",
  "wc.hint": "New wires use the last colour you picked; wires of different colours are never merged automatically."
});
