// v10.1 pinout / usage reference panel, new examples and wire colours — Español
I18N.add('es', {
  "help.btn": "Pines",
  "help.title": "Pines y uso",
  "help.intro.arduino": "Arduino Uno R3 (ATmega328P, 16 MHz, lógica de 5 V): 14 pines digitales D0–D13 (6 de ellos, marcados con ~, pueden generar PWM) y 6 entradas analógicas A0–A5 (ADC de 10 bits, también utilizables como pines digitales D14–D19). A continuación: el mapa de pines, la función de cada pin, los límites eléctricos, lo que admite el simulador, los usos habituales y, al final, ejemplos que se cargan con un clic.",
  "help.intro.attiny85": "ATtiny85 (DIP de 8 pines, AVR de 8 bits): 5 E/S de uso general PB0–PB4 más PB5 (RESET por defecto). Sin UART por hardware; PWM en PB0/PB1/PB4, ADC en PB2/PB3/PB4 (y PB5). Flash de 8 KB, SRAM de 512 B, EEPROM de 512 B; de fábrica funciona con el oscilador RC interno de 8 MHz dividido entre 8 = 1 MHz (fusible CKDIV8).",
  "help.nav.pinout": "Mapa de pines",
  "help.nav.table": "Tabla de pines",
  "help.nav.limits": "Límites eléctricos",
  "help.nav.sim": "Soporte del simulador",
  "help.nav.usage": "Usos habituales",
  "help.nav.examples": "Ejemplos",
  "help.cat.dig": "E/S digital",
  "help.cat.pwm": "Salida PWM",
  "help.cat.ana": "Entrada analógica",
  "help.cat.com": "Comunicación (UART/SPI/I²C)",
  "help.cat.int": "Interrupción externa",
  "help.cat.pwr": "Alimentación",
  "help.cat.gnd": "Tierra",
  "help.cat.spc": "Función especial",
  "help.leg.nosim": "Discontinuo = no simulado",
  "help.th.pin": "Pin",
  "help.th.func": "Funciones y notas",
  "help.th.sim": "Simulado",
  "help.sim.yes": "sí",
  "help.sim.part": "en parte",
  "help.sim.no": "no",
  "help.sim.absent": "el componente no tiene este pin",
  "help.tag.dio": "entrada/salida digital",
  "help.tag.pwm490": "PWM ≈ 490 Hz",
  "help.tag.pwm980": "PWM ≈ 980 Hz",
  "help.tag.tpwm": "salida PWM (analogWrite)",
  "help.tag.adc": "entrada analógica (ADC de 10 bits)",
  "help.tag.rx": "recepción serie RX",
  "help.tag.tx": "transmisión serie TX",
  "help.tag.int0": "interrupción externa INT0",
  "help.tag.int1": "interrupción externa INT1",
  "help.tag.ss": "SPI selección de esclavo SS",
  "help.tag.mosi": "SPI MOSI (salida del maestro)",
  "help.tag.miso": "SPI MISO (entrada del maestro)",
  "help.tag.sck": "reloj SPI SCK",
  "help.tag.sda": "datos I²C SDA",
  "help.tag.scl": "reloj I²C SCL",
  "help.tag.led": "LED integrado «L»",
  "help.tag.aref": "referencia analógica AREF",
  "help.tag.ioref": "referencia de tensión de E/S IOREF",
  "help.tag.reset": "reinicio (activo en bajo)",
  "help.tag.treset": "RESET (activo en bajo)",
  "help.tag.v5": "alimentación de 5 V",
  "help.tag.v33": "salida de 3,3 V",
  "help.tag.vin": "entrada de alimentación externa VIN",
  "help.tag.gnd": "tierra GND",
  "help.tag.vcc": "alimentación VCC",
  "help.tag.usi_di": "USI entrada de datos DI / I²C SDA",
  "help.tag.usi_do": "USI salida de datos DO",
  "help.tag.usi_sck": "USI reloj USCK / I²C SCL",
  "help.tag.xtal": "pin de cristal externo",
  "help.tag.ain": "entrada del comparador analógico",
  "help.tag.taref": "referencia externa AREF",
  "help.tag.tled": "LED integrado en placas tipo Digispark",
  "help.tag.icsp": "conector de programación ICSP",
  "help.note.d0d1": "D0/D1 están conectados al chip USB-serie de la placa: la carga de programas y `Serial` los usan, y un circuito externo en ellos puede hacer fallar la carga. En el simulador D0/D1 funcionan como E/S normales y `Serial` va directamente al monitor serie.",
  "help.note.tone": "`tone()` usa el Timer2, así que el PWM de D3 y D11 deja de funcionar mientras suena un tono.",
  "help.note.servo": "La biblioteca Servo usa el Timer1, así que `analogWrite()` deja de funcionar en D9 y D10 (sea cual sea el pin del servo).",
  "help.note.d13": "El LED integrado «L» lo controla D13 (`LED_BUILTIN`), con un amplificador operacional como búfer en la R3. D13 también es SCK de SPI, por lo que el LED parpadea mientras se usa SPI.",
  "help.note.a4a5": "A4/A5 son también los pines SDA/SCL de I²C (la R3 los repite en un conector SDA/SCL junto a AREF). Mientras se usa I²C no pueden ser entradas analógicas.",
  "help.note.v5": "Procede del regulador de 5 V de la placa (con alimentación por VIN/DC) o del USB. Sirve para sensores y módulos pequeños; con USB toda la placa está limitada por un fusible rearmable de 500 mA. También se pueden introducir 5 V regulados aquí, pero se salta el regulador y las protecciones.",
  "help.note.v33": "Salida del regulador de 3,3 V de la placa, 50 mA como máximo.",
  "help.note.vin": "Entrada de alimentación externa (el conector DC llega a ella a través de un diodo): 7–12 V recomendados, límites 6–20 V. Por debajo de 7 V los 5 V pueden caer; por encima de 12 V el regulador se calienta mucho.",
  "help.note.gnd": "Todos los pines GND están unidos. El negativo de cualquier fuente externa (batería, alimentación del motor) debe ir al GND del Arduino (tierra común) para que las señales tengan la misma referencia.",
  "help.note.reset": "Llevarlo a nivel bajo reinicia la placa; el botón de reinicio está conectado aquí. El componente simulado no tiene este pin: use el botón «Reiniciar» del editor de programas.",
  "help.note.aref": "Entrada de referencia analógica externa (0–5 V) para `analogReference(EXTERNAL)`; seleccione EXTERNAL antes de conectar una tensión o el chip puede dañarse. El componente simulado no tiene este pin y trata EXTERNAL como VCC (5 V).",
  "help.note.ioref": "Indica a los shields la tensión de E/S de la placa (5 V en el Uno). No existe en el componente simulado.",
  "help.note.sdascl": "Conector I²C añadido en la R3, eléctricamente igual que A4/A5. I²C (biblioteca Wire) no se simula.",
  "help.note.icsp": "Conector de programación en circuito de 6 pines, para grabar el bootloader o cargar con un programador. No hace falta en el simulador.",
  "help.note.pb5": "Por defecto es RESET (activo en bajo, con pull-up interno), así que no es una E/S normal; en el simulador, llevarlo por debajo de 0,3·VCC mantiene el chip en reinicio. Solo programando el fusible RSTDISBL pasa a ser una E/S (débil), y después ya no se puede programar por ISP hasta recuperarlo con un programador de alta tensión. En el simulador puede activar «PB5 como E/S normal» en las propiedades.",
  "help.note.pb34": "PB3/PB4 son también los pines del cristal externo y no pueden usarse como E/S con un cristal externo. El reloj por defecto es el oscilador RC interno, así que están libres.",
  "help.note.pb0": "Pin físico 5: PWM (OC0A), USI DI / I²C SDA, MOSI para la programación ISP y AREF externo opcional (entonces deja de ser E/S).",
  "help.note.pb1": "Pin físico 6: PWM (OC0B / OC1A), USI DO, MISO para la programación ISP. Placas como Digispark tienen aquí su LED integrado.",
  "help.note.pb2": "Pin físico 7: la única interrupción externa INT0, entrada analógica A1 (ADC1), reloj USI USCK / I²C SCL, SCK para la programación ISP.",
  "help.note.vcc": "Alimentación de 2,7–5,5 V (ATtiny85V: 1,8–5,5 V); cuanto más rápido el reloj, más tensión hace falta (20 MHz necesitan 4,5 V o más). Coloque un condensador de desacoplo de 100 nF entre VCC y GND junto al chip.",
  "help.lim.arduino.1": "Cada pin de E/S: 20 mA recomendados, 40 mA máximo absoluto; más puede dañar el puerto de forma permanente.",
  "help.lim.arduino.2": "Corriente total de todos los pines juntos (por VCC/GND): 200 mA como máximo.",
  "help.lim.arduino.3": "La tensión de los pines debe estar entre −0,5 V y VCC + 0,5 V; entrada BAJA < 0,3·VCC (1,5 V), ALTA > 0,6·VCC (3 V).",
  "help.lim.arduino.4": "Resistencias pull-up internas de 20–50 kΩ (`INPUT_PULLUP`).",
  "help.lim.arduino.5": "Entradas analógicas 0–5 V (referencia por defecto = VCC), 10 bits → 0–1023, unos 4,9 mV por paso; la impedancia de la fuente debe ser ≤ 10 kΩ.",
  "help.lim.arduino.6": "VIN / conector DC: 7–12 V recomendados, límites 6–20 V; el USB da 5 V a través de un fusible rearmable de 500 mA.",
  "help.lim.arduino.7": "Pin 3.3V: 50 mA como máximo; lo que puede dar el pin 5V depende de la fuente (toda la placa ≤ 500 mA con USB, limitado por el calentamiento del regulador con VIN).",
  "help.lim.arduino.8": "ATmega328P: 16 MHz, Flash de 32 KB (0,5 KB para el bootloader), SRAM de 2 KB, EEPROM de 1 KB.",
  "help.lim.attiny85.1": "Cada pin de E/S: ≤ 20 mA recomendados, 40 mA máximo absoluto; total por VCC/GND ≤ 200 mA.",
  "help.lim.attiny85.2": "Alimentación de 2,7–5,5 V (ATtiny85V: 1,8–5,5 V); hasta 10 MHz desde 2,7 V, 20 MHz necesitan 4,5–5,5 V.",
  "help.lim.attiny85.3": "Tensión de los pines −0,5 V … VCC + 0,5 V; pull-ups internos de 20–50 kΩ.",
  "help.lim.attiny85.4": "ADC: 10 bits, 4 entradas simples ADC0–ADC3 = PB5 / PB2 / PB4 / PB3; referencia VCC, interna de 1,1 V, interna de 2,56 V o AREF externo en PB0.",
  "help.lim.attiny85.5": "Memoria: Flash de 8 KB, SRAM de 512 B, EEPROM de 512 B.",
  "help.lim.attiny85.6": "Reloj: de fábrica RC interno de 8 MHz ÷ 8 = 1 MHz (fusible CKDIV8); puede cambiarse a 8 MHz interno, PLL de 16 MHz o cristal externo (usa PB3/PB4).",
  "help.sim.ok": "Simulado: `pinMode` / `digitalWrite` / `digitalRead` (incluido `INPUT_PULLUP`), `analogRead` (10 bits), `analogWrite` (PWM a la frecuencia del chip real), `millis` / `micros` / `delay`, `tone` / `noTone`, `pulseIn`, `shiftOut`, Servo, LiquidCrystal, `Serial` (monitor serie) y más. La resistencia de salida de los pines, los pull-ups y las corrientes forman parte de la solución del circuito, y más de 40 mA en un pin genera un aviso.",
  "help.sim.no.1": "Interrupciones externas `attachInterrupt()`: se indican como no admitidas al compilar; consulte el pin periódicamente o use `millis()`.",
  "help.sim.no.2": "Temporización a nivel de pin de I²C (biblioteca Wire), la biblioteca SPI y la UART: las funciones de comunicación de D0/D1, A4/A5 y D10–D13 no se modelan; `Serial` solo se comunica con el monitor serie.",
  "help.sim.no.3": "Los efectos secundarios de las bibliotecas sobre los temporizadores (tone desactiva el PWM de D3/D11, Servo el de D9/D10) solo se documentan aquí; el simulador no los reproduce.",
  "help.sim.no.4": "El componente Uno no tiene RESET, AREF, IOREF, conector SDA/SCL aparte ni conector ICSP; `analogReference(EXTERNAL)` usa VCC, `INTERNAL` = 1,1 V.",
  "help.sim.no.5": "El ATtiny85 no tiene UART por hardware: `Serial` en el simulador es virtual y solo envía texto de depuración al monitor serie.",
  "help.sim.no.6": "La sobrecorriente no «quema» el chip: el simulador solo avisa, así que compruebe el diseño con los límites eléctricos.",
  "help.sim.no.7": "No se admiten la EEPROM, los modos de reposo, el watchdog, la configuración de fusibles ni el acceso directo a registros (como `PORTB`, `DDRB`).",
  "help.sim.no.8": "No se modela el tiempo de ejecución de las instrucciones: el código se ejecuta al instante y solo `delay()`, `millis()` y similares hacen avanzar el tiempo; un bucle infinito que supera el límite de cálculo se detiene con un error.",
  "help.usage.intro": "Cada sección resume el cableado, incluye un fragmento de código para copiar y enlaza ejemplos relacionados.",
  "help.u.power.t": "Alimentación",
  "help.u.power.1": "El Uno se puede alimentar de tres formas: ① USB de 5 V (lo más sencillo, toda la placa ≤ 500 mA); ② 7–12 V en el conector DC o en VIN, regulados a 5 V en la placa; ③ 5 V regulados directamente en el pin 5V (se salta el regulador y las protecciones: un error puede destruir la placa). En el simulador elija alimentación USB o VIN en las propiedades.",
  "help.u.power.2": "Los pines 5V y 3.3V pueden alimentar sensores y módulos pequeños, pero no motores, varios servos ni LED de potencia: esas cargas hacen caer la tensión y reinician el microcontrolador. Dé a las cargas grandes su propia fuente y una su negativo al GND del Arduino (tierra común).",
  "help.u.power.3": "El ATtiny85 es solo un chip, sin regulador: VCC va directamente a 2,7–5,5 V, por ejemplo 3 pilas AA (4,5 V), USB de 5 V o una celda de litio (3,0–4,2 V). Si la tensión es demasiado baja el chip no arranca (el simulador muestra OFF); por encima de 5,5 V puede dañarse.",
  "help.u.power.4": "Ponga un condensador de desacoplo de 100 nF entre VCC y GND junto a cada chip. Los motores y otras cargas inductivas conviene alimentarlos con una fuente separada o, al menos, con abundante capacidad de filtrado.",
  "help.u.dout.t": "Salida digital y resistencias para LED",
  "help.u.dout.1": "Llame a `pinMode(pin, OUTPUT)` y después `digitalWrite(pin, HIGH)` / `LOW` da unos 5 V / 0 V. Una salida puede entregar o absorber corriente; no supere 20 mA por pin.",
  "help.u.dout.2": "Un LED siempre necesita una resistencia en serie: R = (Vcc − Vf) / I. Ejemplo: 5 V, LED rojo Vf ≈ 2 V, 10 mA → R = (5 − 2) / 0,01 = 300 Ω, use el valor normalizado de 330 Ω; 220 Ω (unos 14 mA) también vale. Los LED azules y blancos tienen Vf ≈ 3 V y necesitan unos 200 Ω para la misma corriente.",
  "help.u.dout.3": "Pata larga (ánodo +) por la resistencia al pin, pata corta (cátodo −) a GND: HIGH = encendido. O conecte el LED a 5V y deje que el pin absorba la corriente: LOW = encendido. Para varios LED o más de 20 mA en un pin, use un transistor o un MOSFET.",
  "help.u.din.t": "Entrada de pulsador: pull-up, pull-down y antirrebote",
  "help.u.din.1": "`INPUT_PULLUP` activa el pull-up interno de 20–50 kΩ: conecte el pulsador entre el pin y GND, sin resistencia externa. Suelto lee HIGH y pulsado lee LOW (lógica invertida). Es el cableado más sencillo.",
  "help.u.din.2": "Con pull-down: pulsador entre 5V y el pin, más 10 kΩ del pin a GND, con `pinMode(pin, INPUT)`; pulsado lee HIGH. En modo `INPUT` un pin al aire lee valores aleatorios, así que el pull-up o pull-down es obligatorio.",
  "help.u.din.3": "Los pulsadores mecánicos rebotan unos milisegundos al pulsarlos o soltarlos, y una pulsación puede leerse varias veces. Para eliminar el rebote, acepte un cambio solo si se mantiene 20–50 ms (mídalo con `millis()`, no con un `delay()` largo), o añada un filtro RC. El ejemplo «Pulsador con antirrebote» muestra la solución por software.",
  "help.u.ain.t": "Entrada analógica: potenciómetro, divisor, LDR / NTC",
  "help.u.ain.1": "`analogRead(A0)` devuelve 0–1023 para 0 V hasta la referencia (por defecto VCC = 5 V): voltios = lectura × 5,0 / 1024. Una conversión tarda unos 100 µs. `analogReference(INTERNAL)` usa la referencia interna de 1,1 V para tensiones pequeñas.",
  "help.u.ain.2": "Potenciómetro: extremos a 5V y GND, cursor a A0; al girarlo la lectura recorre 0–1023. Divisor de tensión: Vout = Vin × R2 / (R1 + R2) reduce tensiones mayores de 5 V (como una batería de 12 V) a 0–5 V para medirlas; asegúrese de que la entrada nunca supere VCC.",
  "help.u.ain.3": "Una fotorresistencia (LDR) o un termistor (NTC) se pone en serie con una resistencia fija formando un divisor, con el punto medio al pin analógico; elija la resistencia fija cerca del valor medio del sensor, normalmente 10 kΩ. Con la LDR abajo, más oscuridad da más tensión; la resistencia de un NTC baja al calentarse. `map()` convierte la lectura al rango que necesite.",
  "help.u.ain.4": "El ADC requiere una impedancia de fuente ≤ 10 kΩ; con un divisor de valores altos la lectura oscila: añada 100 nF del pin analógico a GND. A0–A5 también sirven como pines digitales normales (D14–D19). En el ATtiny85 los pines analógicos son A1 (PB2), A2 (PB4) y A3 (PB3); A0 (PB5) es el pin de reinicio y normalmente no se usa.",
  "help.u.pwm.t": "PWM: regulación de brillo y velocidad",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` genera una onda cuadrada PWM en los pines marcados con ~: ciclo de trabajo = valor / 255, tensión media ≈ 5 V × valor / 255. En el Uno D5 y D6 van a unos 980 Hz, D3, D9, D10 y D11 a unos 490 Hz; en el ATtiny85 use PB0, PB1 o PB4.",
  "help.u.pwm.2": "El PWM es ideal para el brillo de un LED (el ojo ve la media) y la velocidad de un motor; no es una tensión analógica real: añada un filtro RC paso bajo si necesita una tensión suave. En un pin sin ~, `analogWrite()` da LOW para valores < 128 y HIGH en otro caso.",
  "help.u.pwm.3": "0 y 255 dan un LOW / HIGH constante. El brillo percibido no es lineal, así que una curva cuadrática hace los fundidos más naturales. Observe la onda PWM en el osciloscopio (ejemplo «regulador con potenciómetro»).",
  "help.u.motor.t": "Motores: transistor / MOSFET y diodo de rueda libre",
  "help.u.motor.1": "Un pin solo da unos 20 mA y no puede mover un motor directamente. Use un transistor NPN o un MOSFET de canal N como interruptor del lado bajo: carga entre el + de la fuente y el drenador (D), fuente (S) a GND, puerta (G) a un pin PWM a través de 100–220 Ω, más 10 kΩ de la puerta a GND para que el motor no arranque mientras el pin queda al aire al encender o reiniciar.",
  "help.u.motor.2": "Elija un MOSFET de nivel lógico (como el IRLZ44N, que conduce plenamente con 5 V en la puerta); los modelos estándar como el IRF540 se especifican con 10 V en la puerta y se calientan si a 5 V solo conducen a medias. Con un transistor ponga unos 1 kΩ en serie con la base.",
  "help.u.motor.3": "Motores, bobinas de relé y solenoides son cargas inductivas: al desconectarlos aparece un gran pico de tensión inversa, así que debe colocar un diodo de rueda libre (como un 1N4007, cátodo al + de la fuente) en paralelo con la carga. El negativo de la alimentación del motor debe unirse al GND del Arduino. Para avance/retroceso use un puente H (L298N, TB6612…).",
  "help.u.relay.t": "Relés y cargas mayores",
  "help.u.relay.1": "Un relé usa una pequeña corriente de bobina para conmutar contactos de alta corriente y tensión: COM es el común, NO normalmente abierto (unido a COM mientras la bobina está activada) y NC normalmente cerrado. El circuito de contactos está aislado del microcontrolador, así que puede conmutar una lámpara de 12 V o aparatos de red.",
  "help.u.relay.2": "Los módulos de relé incluyen el transistor, el diodo de rueda libre y un LED indicador: VCC/GND a 5V/GND, IN a cualquier pin digital. Atención al nivel de disparo: muchos módulos se activan en bajo (actúan con IN = LOW); el módulo simulado permite elegir disparo alto o bajo en sus propiedades.",
  "help.u.relay.3": "La bobina de un relé suelto suele consumir 70 mA o más, así que no puede ir directamente a un pin: contrólela con un transistor y un diodo de rueda libre. La tensión de red es peligrosa: use un módulo cerrado y respete la corriente nominal de los contactos.",
  "help.u.tone.t": "Zumbadores y tone()",
  "help.u.tone.1": "`tone(pin, frecuencia)` genera una onda cuadrada al 50 % en cualquier pin digital, `tone(pin, frecuencia, duración)` se detiene sola y `noTone(pin)` la para. Solo puede sonar un `tone()` a la vez; usa el Timer2 y desactiva el PWM de D3/D11.",
  "help.u.tone.2": "Los zumbadores pasivos y los altavoces pequeños necesitan la onda cuadrada de `tone()` para sonar, y la frecuencia fija el tono; un zumbador activo tiene su propio oscilador y suena con `digitalWrite(HIGH)`, pero con un tono fijo.",
  "help.u.tone.3": "Ponga unos 100 Ω en serie con el zumbador; un altavoz de 8 Ω consume demasiado y necesita un transistor. Frecuencias de notas comunes: C4 262, D4 294, E4 330, F4 349, G4 392, A4 440, B4 494, C5 523 Hz.",
  "help.u.servo.t": "Servos",
  "help.u.servo.1": "Un servo tiene tres cables: señal (naranja/amarillo), alimentación + (rojo) y GND (marrón/negro). La señal es un pulso cada 20 ms aproximadamente (50 Hz); anchos de pulso de normalmente 1–2 ms fijan el ángulo, y la biblioteca Servo asigna por defecto 544–2400 µs a 0–180°. Use `attach(pin)` y después `write(ángulo)`.",
  "help.u.servo.2": "La biblioteca Servo usa el Timer1, así que D9 y D10 pierden el PWM (el cable de señal puede ir a cualquier pin digital). Un Uno puede controlar hasta 12 servos.",
  "help.u.servo.3": "Los servos consumen cientos de mA, incluso más de 1 A, al arrancar o bloquearse. Un servo pequeño como el SG90 puede alimentarse del pin 5V; varios o más grandes necesitan su propia fuente de 5–6 V con tierra común, y 100–470 µF en la alimentación del servo ayudan a evitar reinicios.",
  "help.u.lcd.t": "Pantalla LCD1602",
  "help.u.lcd.1": "La LCD1602 (controlador HD44780) solo necesita 6 líneas de señal en modo de 4 bits: RS, E, D4–D7, con RW a GND (solo escritura); la forma de 7 argumentos controla también RW desde un pin. `LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`, y luego `lcd.begin(16, 2)`, `lcd.setCursor(columna, fila)`, `lcd.print()`, `lcd.clear()`.",
  "help.u.lcd.2": "Alimentación: VSS a GND, VDD a 5V; V0 ajusta el contraste, normalmente desde el cursor de un potenciómetro de 10 kΩ (extremos a 5V/GND); si está desajustado verá bloques sólidos o nada. A/K son el LED de retroiluminación: A a 5V a través de una resistencia (muchos módulos la llevan) o a un pin para conmutarla, K a GND.",
  "help.u.lcd.3": "¿Faltan pines? Un adaptador I²C (PCF8574, solo A4/A5) ayuda en el hardware real, pero este simulador no tiene I²C, así que use el cableado en paralelo. Filas y columnas se cuentan desde 0: la segunda línea es `setCursor(0, 1)`.",
  "help.u.serial.t": "Depuración por puerto serie",
  "help.u.serial.1": "`Serial.begin(9600)` abre el puerto (la velocidad debe coincidir con la del monitor serie) y `Serial.print()` / `println()` envían texto y números. Es la forma más habitual de depurar: imprimir variables, qué rama se ejecutó, lecturas de sensores.",
  "help.u.serial.2": "`Serial.available()` devuelve el número de bytes recibidos, `Serial.read()` lee un byte y `Serial.readStringUntil('\\n')` lee una línea. En el simulador escriba en el campo de entrada del monitor serie para enviar texto.",
  "help.u.serial.3": "En el Uno el puerto serie usa D0/D1: no conecte otros circuitos a esos pines mientras lo use. Imprimir demasiado a menudo ralentiza el programa (9600 baudios son aproximadamente 1 carácter por milisegundo), así que espacie los mensajes con `millis()`. El ATtiny85 no tiene UART por hardware; su `Serial` en el simulador es solo para depurar.",
  "help.u.millis.t": "Temporización sin bloqueo con millis()",
  "help.u.millis.1": "Durante `delay()` el programa no puede hacer nada más (ni leer pulsadores ni actualizar otros LED). `millis()` devuelve los milisegundos desde el encendido; comprobar «ahora − último ≥ intervalo» permite atender varias cosas a la vez.",
  "help.u.millis.2": "Use `unsigned long` para las variables de tiempo. Comparar mediante resta, `millis() - last >= INTERVAL`, sigue funcionando cuando el contador se desborda tras unos 49,7 días; no escriba `millis() >= last + INTERVAL`.",
  "help.u.millis.3": "Una variable de tiempo por tarea da una máquina de estados sencilla: el ejemplo «multitarea con millis()» hace parpadear dos LED a ritmos distintos mientras imprime el tiempo de funcionamiento, y el pulsador con antirrebote usa la misma idea. Use `micros()` para resolución de microsegundos.",
  "help.ex.examples": "Ejemplos relacionados",
  "help.ex.intro": "«Cargar en el lienzo» sustituye el circuito actual e inicia la simulación; «Insertar en el editor» pone el código en el editor de programas del chip actual (aún sin cargar, para que pueda editarlo); «Copiar código» lo copia al portapapeles.",
  "help.ex.wiring": "Cableado",
  "help.ex.usage": "Uso relacionado",
  "help.ex.code": "Código",
  "help.ex.load": "Cargar en el lienzo",
  "help.ex.insert": "Insertar en el editor",
  "help.ex.copy": "Copiar código",
  "help.ex.other": "Ver los ejemplos de {board} ({n}) →",
  "help.toast.inserted": "Código insertado en el editor de {chip}; pulse «Compilar y cargar» para aplicarlo",
  "help.toast.mismatch": "Insertado, pero este código se escribió para {board}; puede que los pines no coincidan",
  "help.toast.copied": "Código copiado al portapapeles",
  "help.toast.copy_failed": "No se pudo copiar: seleccione el código en el cuadro y cópielo a mano",
  "help.toast.no_chip": "No hay ningún microcontrolador en el lienzo: coloque primero una placa o un chip, o use «Cargar en el lienzo»",
  "help.w.anode": "ánodo (+, pata larga)",
  "help.w.cathode": "cátodo (−)",
  "help.w.onboard_led": "LED integrado (L)",
  "help.w.red_led": "LED rojo",
  "help.w.yellow_led": "LED amarillo",
  "help.w.green_led": "LED verde",
  "help.w.white_led": "LED blanco",
  "help.w.all_cathodes": "todos los cátodos de los LED",
  "help.w.internal_pullup": "pull-up interno",
  "help.w.pot_ends": "extremos",
  "help.w.wiper": "cursor",
  "help.w.gate": "puerta G",
  "help.w.drain": "drenador D",
  "help.w.source": "fuente S",
  "help.w.flyback": "en paralelo inverso con el motor (cátodo al +), como diodo de rueda libre",
  "help.w.common_gnd": "tierra común",
  "help.w.servo_sig": "cable de señal",
  "help.w.servo_vcc": "cable de alimentación",
  "help.w.servo_gnd": "cable de tierra",
  "help.w.backlight": "retroiluminación",
  "help.w.contrast": "contraste",
  "help.w.pin_n4": "pin 4",
  "help.w.pin_n5": "pin 5",
  "help.w.pin_n6": "pin 6",
  "help.w.pin_n8": "pin 8",
  "ex.arddebounce": "MCU: pulsador con antirrebote alterna un LED (millis)",
  "ex.ardnight": "MCU: luz nocturna con LDR (LDR → PWM)",
  "ex.ardmulti": "MCU: multitarea con millis() (sin delay)",
  "ex.ardmotor": "MCU: control de velocidad de motor DC con MOSFET (PWM)",
  "ex.ardrelay": "MCU: módulo de relé enciende una lámpara de 12 V con temporizador",
  "ex.ardtone": "MCU: melodía con zumbador pasivo (tone)",
  "ex.tinyfade": "MCU: fundido PWM con ATtiny85",
  "exd.arddebounce": "Cada pulsación del botón en D2 alterna el LED de D8: la entrada debe estar estable 30 ms para que cuente un cambio, así el rebote no la alterna dos veces; el número de pulsaciones se muestra en el monitor serie.",
  "exd.ardnight": "5V → 10 kΩ → A0 → fotorresistencia → GND forma un divisor: cuanto más oscuro, mayor la lectura y más brilla el LED blanco en el pin PWM D9. Cambie la propiedad «Intensidad de luz» de la fotorresistencia para probarlo.",
  "exd.ardmulti": "Sin ningún delay(): el LED de D8 cambia cada 250 ms, el de D7 cada 700 ms y cada segundo se imprime el tiempo de funcionamiento; tres tareas a la vez.",
  "exd.ardmotor": "Potenciómetro → A0 → PWM en D9 → MOSFET de nivel lógico IRLZ44N → motor DC. El motor tiene su propia batería de 6 V con tierra común con el Arduino, y un diodo 1N4007 absorbe el pico al apagarse.",
  "exd.ardrelay": "D7 controla un módulo de relé (disparo en alto) que enciende una lámpara de 12 V durante 2 s y la apaga 2 s. El circuito de la lámpara está aislado del Arduino; el pin solo aporta unos mA.",
  "exd.ardtone": "D8 excita un zumbador pasivo a través de 100 Ω y toca una melodía de 16 pasos con tone() (0 = silencio); la frecuencia de cada nota se muestra en el monitor serie.",
  "exd.tinyfade": "El ATtiny85 genera PWM en PB0 (pin 5) y PB1 (pin 6): el LED amarillo se enciende poco a poco mientras el verde se apaga, una y otra vez.",
  "wc.title": "Color del cable",
  "wc.n_wires": "{n} cables seleccionados",
  "wc.red": "Rojo",
  "wc.black": "Negro",
  "wc.blue": "Azul",
  "wc.green": "Verde",
  "wc.yellow": "Amarillo",
  "wc.orange": "Naranja",
  "wc.white": "Blanco",
  "wc.purple": "Morado",
  "wc.gray": "Gris",
  "wc.brown": "Marrón",
  "wc.custom": "Color personalizado…",
  "wc.hint": "Los cables nuevos usan el último color elegido; los cables de distinto color nunca se fusionan automáticamente."
});
