// v10.1 pinout / usage reference panel, new examples and wire colours — Français
I18N.add('fr', {
  "help.btn": "Brochage",
  "help.title": "Brochage et utilisation",
  "help.intro.arduino": "Arduino Uno R3 (ATmega328P, 16 MHz, logique 5 V) : 14 broches numériques D0–D13 (6 d’entre elles, marquées ~, peuvent produire du PWM) et 6 entrées analogiques A0–A5 (CAN 10 bits, utilisables aussi comme broches numériques D14–D19). Ci-dessous : le plan de brochage, le rôle de chaque broche, les limites électriques, ce que le simulateur prend en charge, les usages courants et enfin des exemples à charger en un clic.",
  "help.intro.attiny85": "ATtiny85 (DIP 8 broches, AVR 8 bits) : 5 E/S d’usage général PB0–PB4 plus PB5 (RESET par défaut). Pas d’UART matériel ; PWM sur PB0/PB1/PB4, CAN sur PB2/PB3/PB4 (et PB5). Flash 8 Ko, SRAM 512 o, EEPROM 512 o ; livré avec l’oscillateur RC interne de 8 MHz divisé par 8 = 1 MHz (fusible CKDIV8).",
  "help.nav.pinout": "Plan de brochage",
  "help.nav.table": "Tableau des broches",
  "help.nav.limits": "Limites électriques",
  "help.nav.sim": "Prise en charge par le simulateur",
  "help.nav.usage": "Usages courants",
  "help.nav.examples": "Exemples",
  "help.cat.dig": "E/S numérique",
  "help.cat.pwm": "Sortie PWM",
  "help.cat.ana": "Entrée analogique",
  "help.cat.com": "Communication (UART/SPI/I²C)",
  "help.cat.int": "Interruption externe",
  "help.cat.pwr": "Alimentation",
  "help.cat.gnd": "Masse",
  "help.cat.spc": "Fonction spéciale",
  "help.leg.nosim": "Pointillés = non simulé",
  "help.th.pin": "Broche",
  "help.th.func": "Fonctions et remarques",
  "help.th.sim": "Simulé",
  "help.sim.yes": "oui",
  "help.sim.part": "en partie",
  "help.sim.no": "non",
  "help.sim.absent": "broche absente du composant",
  "help.tag.dio": "entrée/sortie numérique",
  "help.tag.pwm490": "PWM ≈ 490 Hz",
  "help.tag.pwm980": "PWM ≈ 980 Hz",
  "help.tag.tpwm": "sortie PWM (analogWrite)",
  "help.tag.adc": "entrée analogique (CAN 10 bits)",
  "help.tag.rx": "réception série RX",
  "help.tag.tx": "émission série TX",
  "help.tag.int0": "interruption externe INT0",
  "help.tag.int1": "interruption externe INT1",
  "help.tag.ss": "SPI sélection esclave SS",
  "help.tag.mosi": "SPI MOSI (sortie maître)",
  "help.tag.miso": "SPI MISO (entrée maître)",
  "help.tag.sck": "horloge SPI SCK",
  "help.tag.sda": "données I²C SDA",
  "help.tag.scl": "horloge I²C SCL",
  "help.tag.led": "LED intégrée « L »",
  "help.tag.aref": "référence analogique AREF",
  "help.tag.ioref": "référence de tension E/S IOREF",
  "help.tag.reset": "réinitialisation (active à l’état bas)",
  "help.tag.treset": "RESET (actif à l’état bas)",
  "help.tag.v5": "alimentation 5 V",
  "help.tag.v33": "sortie 3,3 V",
  "help.tag.vin": "entrée d’alimentation externe VIN",
  "help.tag.gnd": "masse GND",
  "help.tag.vcc": "alimentation VCC",
  "help.tag.usi_di": "USI entrée de données DI / I²C SDA",
  "help.tag.usi_do": "USI sortie de données DO",
  "help.tag.usi_sck": "USI horloge USCK / I²C SCL",
  "help.tag.xtal": "broche de quartz externe",
  "help.tag.ain": "entrée du comparateur analogique",
  "help.tag.taref": "référence externe AREF",
  "help.tag.tled": "LED intégrée des cartes type Digispark",
  "help.tag.icsp": "connecteur de programmation ICSP",
  "help.note.d0d1": "D0/D1 sont reliées à la puce USB-série de la carte : le téléversement et `Serial` les utilisent, et un circuit externe branché dessus peut faire échouer le téléversement. Dans le simulateur, D0/D1 servent d’E/S ordinaires et `Serial` va directement au moniteur série.",
  "help.note.tone": "`tone()` utilise le Timer2 : le PWM de D3 et D11 ne fonctionne plus pendant qu’un son est joué.",
  "help.note.servo": "La bibliothèque Servo utilise le Timer1 : `analogWrite()` ne fonctionne plus sur D9 et D10 (quelle que soit la broche du servo).",
  "help.note.d13": "La LED intégrée « L » est pilotée par D13 (`LED_BUILTIN`), via un ampli-op tampon sur la R3. D13 est aussi le SCK du SPI : la LED scintille quand le SPI est utilisé.",
  "help.note.a4a5": "A4/A5 sont aussi les broches SDA/SCL de l’I²C (la R3 les répète sur un connecteur SDA/SCL près d’AREF). Pendant l’utilisation de l’I²C, elles ne peuvent pas servir d’entrées analogiques.",
  "help.note.v5": "Provient du régulateur 5 V de la carte (alimentation par VIN/DC) ou de l’USB. Convient aux capteurs et petits modules ; sur USB, toute la carte est limitée par un fusible réarmable de 500 mA. On peut aussi injecter ici un 5 V régulé, mais cela contourne le régulateur et les protections.",
  "help.note.v33": "Sortie du régulateur 3,3 V de la carte, 50 mA au maximum.",
  "help.note.vin": "Entrée d’alimentation externe (le jack DC y arrive par une diode) : 7–12 V recommandés, limites 6–20 V. En dessous de 7 V le 5 V peut chuter ; au-dessus de 12 V le régulateur chauffe.",
  "help.note.gnd": "Toutes les broches GND sont reliées. Le pôle négatif de toute alimentation externe (pile, alimentation moteur) doit être relié au GND de l’Arduino (masse commune) pour que les signaux aient la même référence.",
  "help.note.reset": "La mettre à l’état bas réinitialise la carte ; le bouton reset y est relié. Le composant simulé n’a pas cette broche : utilisez le bouton « Reset » de l’éditeur de programme.",
  "help.note.aref": "Entrée de référence analogique externe (0–5 V) pour `analogReference(EXTERNAL)` ; sélectionnez EXTERNAL avant de brancher une tension, sinon la puce peut être endommagée. Le composant simulé n’a pas cette broche et traite EXTERNAL comme VCC (5 V).",
  "help.note.ioref": "Indique aux shields la tension d’E/S de la carte (5 V sur l’Uno). Absente du composant simulé.",
  "help.note.sdascl": "Connecteur I²C ajouté sur la R3, électriquement identique à A4/A5. L’I²C (bibliothèque Wire) n’est pas simulé.",
  "help.note.icsp": "Connecteur de programmation in situ à 6 broches, pour graver le bootloader ou téléverser avec un programmateur. Inutile dans le simulateur.",
  "help.note.pb5": "RESET par défaut (actif à l’état bas, pull-up interne) : ce n’est donc pas une E/S normale ; dans le simulateur, la tirer sous 0,3·VCC maintient la puce en réinitialisation. Seule la programmation du fusible RSTDISBL en fait une E/S (faible), et la programmation ISP devient alors impossible jusqu’à une récupération avec un programmateur haute tension. Dans le simulateur, cochez « PB5 en E/S normale » dans les propriétés.",
  "help.note.pb34": "PB3/PB4 sont aussi les broches du quartz externe et ne peuvent pas servir d’E/S avec un quartz externe. L’horloge par défaut est l’oscillateur RC interne : elles sont donc libres.",
  "help.note.pb0": "Broche physique 5 : PWM (OC0A), USI DI / I²C SDA, MOSI pour la programmation ISP et AREF externe optionnelle (elle n’est alors plus une E/S).",
  "help.note.pb1": "Broche physique 6 : PWM (OC0B / OC1A), USI DO, MISO pour la programmation ISP. Des cartes comme la Digispark y placent leur LED intégrée.",
  "help.note.pb2": "Broche physique 7 : la seule interruption externe INT0, entrée analogique A1 (ADC1), horloge USI USCK / I²C SCL, SCK pour la programmation ISP.",
  "help.note.vcc": "Alimentation 2,7–5,5 V (ATtiny85V : 1,8–5,5 V) ; plus l’horloge est rapide, plus il faut de tension (20 MHz exigent 4,5 V ou plus). Placez un condensateur de découplage de 100 nF entre VCC et GND au plus près de la puce.",
  "help.lim.arduino.1": "Chaque broche d’E/S : 20 mA recommandés, 40 mA maximum absolu ; au-delà, le port peut être détruit définitivement.",
  "help.lim.arduino.2": "Courant total de toutes les broches (par VCC/GND) : 200 mA au maximum.",
  "help.lim.arduino.3": "La tension des broches doit rester entre −0,5 V et VCC + 0,5 V ; entrée BAS < 0,3·VCC (1,5 V), HAUT > 0,6·VCC (3 V).",
  "help.lim.arduino.4": "Résistances de pull-up internes de 20–50 kΩ (`INPUT_PULLUP`).",
  "help.lim.arduino.5": "Entrées analogiques 0–5 V (référence par défaut = VCC), 10 bits → 0–1023, environ 4,9 mV par pas ; l’impédance de la source doit être ≤ 10 kΩ.",
  "help.lim.arduino.6": "VIN / jack DC : 7–12 V recommandés, limites 6–20 V ; l’USB fournit 5 V via un fusible réarmable de 500 mA.",
  "help.lim.arduino.7": "Broche 3.3V : 50 mA au maximum ; ce que peut fournir la broche 5V dépend de l’alimentation (toute la carte ≤ 500 mA sur USB, limité par l’échauffement du régulateur sur VIN).",
  "help.lim.arduino.8": "ATmega328P : 16 MHz, Flash 32 Ko (dont 0,5 Ko pour le bootloader), SRAM 2 Ko, EEPROM 1 Ko.",
  "help.lim.attiny85.1": "Chaque broche d’E/S : ≤ 20 mA recommandés, 40 mA maximum absolu ; total par VCC/GND ≤ 200 mA.",
  "help.lim.attiny85.2": "Alimentation 2,7–5,5 V (ATtiny85V : 1,8–5,5 V) ; jusqu’à 10 MHz dès 2,7 V, 20 MHz exigent 4,5–5,5 V.",
  "help.lim.attiny85.3": "Tension des broches −0,5 V … VCC + 0,5 V ; pull-ups internes de 20–50 kΩ.",
  "help.lim.attiny85.4": "CAN : 10 bits, 4 entrées asymétriques ADC0–ADC3 = PB5 / PB2 / PB4 / PB3 ; référence VCC, interne 1,1 V, interne 2,56 V ou AREF externe sur PB0.",
  "help.lim.attiny85.5": "Mémoire : Flash 8 Ko, SRAM 512 o, EEPROM 512 o.",
  "help.lim.attiny85.6": "Horloge : livrée en RC interne 8 MHz ÷ 8 = 1 MHz (fusible CKDIV8) ; modifiable en 8 MHz interne, PLL 16 MHz ou quartz externe (utilise PB3/PB4).",
  "help.sim.ok": "Simulé : `pinMode` / `digitalWrite` / `digitalRead` (y compris `INPUT_PULLUP`), `analogRead` (10 bits), `analogWrite` (PWM à la fréquence de la vraie puce), `millis` / `micros` / `delay`, `tone` / `noTone`, `pulseIn`, `shiftOut`, Servo, LiquidCrystal, `Serial` (moniteur série), etc. La résistance de sortie des broches, les pull-ups et les courants font partie du calcul du circuit, et plus de 40 mA sur une broche déclenche un avertissement.",
  "help.sim.no.1": "Interruptions externes `attachInterrupt()` : signalées comme non prises en charge à la compilation ; interrogez la broche ou utilisez `millis()`.",
  "help.sim.no.2": "Chronogrammes au niveau des broches de l’I²C (bibliothèque Wire), de la bibliothèque SPI et de l’UART : les fonctions de communication de D0/D1, A4/A5 et D10–D13 ne sont pas modélisées ; `Serial` ne dialogue qu’avec le moniteur série.",
  "help.sim.no.3": "Les effets de bord des bibliothèques sur les timers (tone désactive le PWM de D3/D11, Servo celui de D9/D10) sont seulement documentés ici ; le simulateur ne les reproduit pas.",
  "help.sim.no.4": "Le composant Uno n’a ni RESET, ni AREF, ni IOREF, ni connecteur SDA/SCL séparé, ni connecteur ICSP ; `analogReference(EXTERNAL)` utilise VCC, `INTERNAL` = 1,1 V.",
  "help.sim.no.5": "L’ATtiny85 n’a pas d’UART matériel : `Serial` dans le simulateur est virtuel et sert uniquement à envoyer du texte de débogage au moniteur série.",
  "help.sim.no.6": "Une surintensité ne « grille » pas la puce : le simulateur se contente d’avertir ; vérifiez votre montage par rapport aux limites électriques.",
  "help.sim.no.7": "L’EEPROM, les modes veille, le chien de garde, les réglages de fusibles et l’accès direct aux registres (comme `PORTB`, `DDRB`) ne sont pas pris en charge.",
  "help.sim.no.8": "Le temps d’exécution des instructions n’est pas modélisé : le code s’exécute instantanément et seuls `delay()`, `millis()` et assimilés font avancer le temps ; une boucle infinie qui dépasse la limite de calcul s’arrête avec une erreur.",
  "help.usage.intro": "Chaque section résume le câblage, donne un extrait de code à copier et renvoie vers les exemples associés.",
  "help.u.power.t": "Alimenter la carte",
  "help.u.power.1": "L’Uno peut être alimenté de trois façons : ① USB 5 V (le plus simple, toute la carte ≤ 500 mA) ; ② 7–12 V sur le jack DC ou VIN, régulés à 5 V sur la carte ; ③ un 5 V régulé directement sur la broche 5V (contourne le régulateur et les protections : une erreur peut détruire la carte). Dans le simulateur, choisissez l’alimentation USB ou VIN dans les propriétés.",
  "help.u.power.2": "Les broches 5V et 3.3V peuvent alimenter des capteurs et de petits modules, mais pas des moteurs, plusieurs servos ou des LED de puissance : ces charges font chuter la tension et réinitialisent le microcontrôleur. Donnez aux charges importantes leur propre alimentation et reliez son négatif au GND de l’Arduino (masse commune).",
  "help.u.power.3": "L’ATtiny85 n’est qu’une puce, sans régulateur : VCC se branche directement sur 2,7–5,5 V, par exemple 3 piles AA (4,5 V), l’USB 5 V ou un seul élément lithium-ion (3,0–4,2 V). Si la tension est trop basse, la puce ne démarre pas (le simulateur affiche OFF) ; au-delà de 5,5 V elle peut être endommagée.",
  "help.u.power.4": "Placez un condensateur de découplage de 100 nF entre VCC et GND à côté de chaque puce. Les moteurs et autres charges inductives sont de préférence alimentés séparément, ou au moins avec une bonne capacité de filtrage.",
  "help.u.dout.t": "Sortie numérique et résistances de LED",
  "help.u.dout.1": "Appelez `pinMode(pin, OUTPUT)`, puis `digitalWrite(pin, HIGH)` / `LOW` donne environ 5 V / 0 V. Une sortie peut fournir ou absorber du courant ; restez à 20 mA ou moins par broche.",
  "help.u.dout.2": "Une LED a toujours besoin d’une résistance en série : R = (Vcc − Vf) / I. Exemple : 5 V, LED rouge Vf ≈ 2 V, 10 mA → R = (5 − 2) / 0,01 = 300 Ω, prenez la valeur normalisée 330 Ω ; 220 Ω (environ 14 mA) convient aussi. Les LED bleues et blanches ont Vf ≈ 3 V et demandent environ 200 Ω pour le même courant.",
  "help.u.dout.3": "Patte longue (anode +) vers la broche via la résistance, patte courte (cathode −) au GND : HIGH = allumée. Ou reliez la LED au 5V et laissez la broche absorber le courant : LOW = allumée. Pour plusieurs LED ou plus de 20 mA sur une broche, utilisez un transistor ou un MOSFET.",
  "help.u.din.t": "Entrée bouton : pull-up, pull-down et anti-rebond",
  "help.u.din.1": "`INPUT_PULLUP` active le pull-up interne de 20–50 kΩ : branchez le bouton entre la broche et le GND, sans résistance externe. Relâché, on lit HIGH ; appuyé, LOW (logique inversée). C’est le câblage le plus simple.",
  "help.u.din.2": "Câblage pull-down : bouton entre le 5V et la broche, plus 10 kΩ de la broche au GND, avec `pinMode(pin, INPUT)` ; appuyé, on lit HIGH. En mode `INPUT`, une broche en l’air lit des valeurs aléatoires : un pull-up ou un pull-down est obligatoire.",
  "help.u.din.3": "Les boutons mécaniques rebondissent quelques millisecondes à l’appui et au relâchement, si bien qu’un appui peut être lu plusieurs fois. Anti-rebond : n’acceptez un changement que s’il reste stable 20–50 ms (mesurez avec `millis()`, pas avec un long `delay()`), ou ajoutez un filtre RC. L’exemple « bouton avec anti-rebond » montre la méthode logicielle.",
  "help.u.ain.t": "Entrée analogique : potentiomètre, diviseur, LDR / CTN",
  "help.u.ain.1": "`analogRead(A0)` renvoie 0–1023 pour 0 V jusqu’à la référence (VCC = 5 V par défaut) : volts = lecture × 5,0 / 1024. Une conversion dure environ 100 µs. `analogReference(INTERNAL)` passe sur la référence interne de 1,1 V pour les petites tensions.",
  "help.u.ain.2": "Potentiomètre : extrémités au 5V et au GND, curseur sur A0 ; en le tournant, la lecture balaie 0–1023. Diviseur de tension : Vout = Vin × R2 / (R1 + R2) ramène des tensions supérieures à 5 V (comme une batterie 12 V) dans 0–5 V pour les mesurer ; l’entrée ne doit jamais dépasser VCC.",
  "help.u.ain.3": "Une photorésistance (LDR) ou une thermistance (CTN) se met en série avec une résistance fixe pour former un diviseur, le point milieu allant à l’entrée analogique ; choisissez la résistance fixe proche de la valeur moyenne du capteur, typiquement 10 kΩ. Avec la LDR en bas, plus il fait sombre, plus la tension monte ; la résistance d’une CTN baisse quand elle chauffe. `map()` convertit la lecture dans la plage voulue.",
  "help.u.ain.4": "Le CAN veut une impédance de source ≤ 10 kΩ ; avec un diviseur de forte valeur, la lecture fluctue : ajoutez 100 nF entre l’entrée analogique et le GND. A0–A5 servent aussi de broches numériques ordinaires (D14–D19). Sur l’ATtiny85, les entrées analogiques sont A1 (PB2), A2 (PB4) et A3 (PB3) ; A0 (PB5) est la broche de reset et n’est normalement pas utilisée.",
  "help.u.pwm.t": "PWM : variation de luminosité et de vitesse",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` produit un signal carré PWM sur les broches marquées ~ : rapport cyclique = valeur / 255, tension moyenne ≈ 5 V × valeur / 255. Sur l’Uno, D5 et D6 tournent à environ 980 Hz, D3, D9, D10 et D11 à environ 490 Hz ; sur l’ATtiny85, utilisez PB0, PB1 ou PB4.",
  "help.u.pwm.2": "Le PWM est idéal pour la luminosité d’une LED (l’œil voit la moyenne) et la vitesse d’un moteur ; ce n’est pas une vraie tension analogique : ajoutez un filtre RC passe-bas pour une tension lisse. Sur une broche sans ~, `analogWrite()` donne LOW pour les valeurs < 128 et HIGH sinon.",
  "help.u.pwm.3": "0 et 255 donnent un LOW / HIGH permanent. La luminosité perçue n’est pas linéaire : une courbe quadratique rend les fondus plus naturels. Observez le signal PWM à l’oscilloscope (exemple « variateur à potentiomètre »).",
  "help.u.motor.t": "Moteurs : transistor / MOSFET et diode de roue libre",
  "help.u.motor.1": "Une broche ne fournit qu’environ 20 mA et ne peut pas entraîner un moteur directement. Utilisez un transistor NPN ou un MOSFET canal N en interrupteur côté bas : charge entre le + de l’alimentation et le drain (D), source (S) au GND, grille (G) reliée à une broche PWM via 100–220 Ω, plus 10 kΩ de la grille au GND pour que le moteur reste arrêté quand la broche est en l’air (mise sous tension, reset).",
  "help.u.motor.2": "Choisissez un MOSFET à niveau logique (comme l’IRLZ44N, pleinement passant avec 5 V de grille) ; les modèles standard comme l’IRF540 sont spécifiés pour 10 V de grille et chauffent s’ils ne conduisent qu’à moitié sous 5 V. Avec un transistor, mettez environ 1 kΩ en série avec la base.",
  "help.u.motor.3": "Moteurs, bobines de relais et électroaimants sont des charges inductives : à la coupure, ils produisent une forte surtension inverse ; une diode de roue libre (par ex. 1N4007, cathode au + de l’alimentation) doit donc être placée aux bornes de la charge. Le négatif de l’alimentation du moteur doit être relié au GND de l’Arduino. Pour marche avant/arrière, utilisez un pont en H (L298N, TB6612…).",
  "help.u.relay.t": "Relais et charges importantes",
  "help.u.relay.1": "Un relais utilise le faible courant d’une bobine pour commuter des contacts à fort courant et haute tension : COM est le commun, NO normalement ouvert (relié à COM quand la bobine est alimentée), NC normalement fermé. Le circuit des contacts est isolé du microcontrôleur et peut commuter une lampe 12 V ou des appareils sur secteur.",
  "help.u.relay.2": "Les modules relais contiennent le transistor, la diode de roue libre et une LED témoin : VCC/GND au 5V/GND, IN sur n’importe quelle broche numérique. Attention au niveau de déclenchement : beaucoup de modules sont actifs à l’état bas (ils collent quand IN = LOW) ; le module simulé permet de choisir déclenchement haut ou bas dans ses propriétés.",
  "help.u.relay.3": "La bobine d’un relais nu consomme en général 70 mA ou plus : elle ne peut pas être branchée directement sur une broche ; commandez-la par un transistor avec une diode de roue libre. Le secteur est dangereux : utilisez un module fermé du commerce et respectez le courant nominal des contacts.",
  "help.u.tone.t": "Buzzers et tone()",
  "help.u.tone.1": "`tone(pin, fréquence)` produit un signal carré à 50 % sur n’importe quelle broche numérique, `tone(pin, fréquence, durée)` s’arrête tout seul, `noTone(pin)` l’arrête. Un seul `tone()` peut jouer à la fois ; il utilise le Timer2 et désactive le PWM de D3/D11.",
  "help.u.tone.2": "Les buzzers passifs et petits haut-parleurs ont besoin du signal carré de `tone()` pour sonner, et la fréquence fixe la hauteur ; un buzzer actif a son propre oscillateur et sonne avec `digitalWrite(HIGH)`, mais à hauteur fixe.",
  "help.u.tone.3": "Mettez environ 100 Ω en série avec un buzzer ; un haut-parleur de 8 Ω consomme beaucoup trop et demande un transistor. Fréquences de notes courantes : C4 262, D4 294, E4 330, F4 349, G4 392, A4 440, B4 494, C5 523 Hz.",
  "help.u.servo.t": "Servomoteurs",
  "help.u.servo.1": "Un servo a trois fils : signal (orange/jaune), alimentation + (rouge), GND (marron/noir). Le signal est une impulsion toutes les 20 ms environ (50 Hz) ; une largeur d’impulsion de 1–2 ms en général fixe l’angle, et la bibliothèque Servo associe par défaut 544–2400 µs à 0–180°. Utilisez `attach(pin)`, puis `write(angle)`.",
  "help.u.servo.2": "La bibliothèque Servo utilise le Timer1 : D9 et D10 perdent le PWM (le fil de signal peut aller sur n’importe quelle broche numérique). Un Uno peut piloter jusqu’à 12 servos.",
  "help.u.servo.3": "Les servos consomment des centaines de mA, voire plus de 1 A, au démarrage ou bloqués. Un petit servo comme le SG90 peut être alimenté par la broche 5V ; plusieurs servos ou des modèles plus gros demandent leur propre alimentation 5–6 V avec masse commune, et 100–470 µF sur l’alimentation des servos évitent les reset.",
  "help.u.lcd.t": "Afficheur LCD1602",
  "help.u.lcd.1": "Le LCD1602 (contrôleur HD44780) n’a besoin que de 6 lignes de signal en mode 4 bits : RS, E, D4–D7, avec RW relié au GND (écriture seule) ; la forme à 7 arguments pilote aussi RW depuis une broche. `LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`, puis `lcd.begin(16, 2)`, `lcd.setCursor(colonne, ligne)`, `lcd.print()`, `lcd.clear()`.",
  "help.u.lcd.2": "Alimentation : VSS au GND, VDD au 5V ; V0 règle le contraste, généralement depuis le curseur d’un potentiomètre de 10 kΩ (extrémités au 5V/GND) — mal réglé, on voit des pavés noirs ou rien du tout. A/K sont la LED de rétroéclairage : A au 5V via une résistance (souvent intégrée au module) ou à une broche pour la commuter, K au GND.",
  "help.u.lcd.3": "Pas assez de broches ? Un adaptateur I²C (PCF8574, seulement A4/A5) aide sur le vrai matériel, mais ce simulateur n’a pas d’I²C : utilisez le câblage parallèle. Lignes et colonnes se comptent à partir de 0 : la deuxième ligne est `setCursor(0, 1)`.",
  "help.u.serial.t": "Débogage par liaison série",
  "help.u.serial.1": "`Serial.begin(9600)` ouvre le port (le débit doit correspondre au moniteur série), `Serial.print()` / `println()` envoient du texte et des nombres. C’est la méthode de débogage la plus courante : afficher des variables, la branche exécutée, des mesures de capteurs.",
  "help.u.serial.2": "`Serial.available()` renvoie le nombre d’octets reçus, `Serial.read()` lit un octet, `Serial.readStringUntil('\\n')` lit une ligne. Dans le simulateur, tapez dans le champ de saisie du moniteur série pour envoyer du texte.",
  "help.u.serial.3": "Sur l’Uno, le port série utilise D0/D1 : ne branchez rien d’autre sur ces broches pendant son utilisation. Afficher trop souvent ralentit le programme (9600 bauds ≈ 1 caractère par milliseconde) : espacez les messages avec `millis()`. L’ATtiny85 n’a pas d’UART matériel ; son `Serial` dans le simulateur sert uniquement au débogage.",
  "help.u.millis.t": "Temporisation non bloquante avec millis()",
  "help.u.millis.1": "Pendant `delay()`, le programme ne peut rien faire d’autre (ni lire un bouton, ni mettre à jour d’autres LED). `millis()` renvoie les millisecondes écoulées depuis la mise sous tension ; tester « maintenant − dernier ≥ intervalle » permet de mener plusieurs tâches à la fois.",
  "help.u.millis.2": "Utilisez `unsigned long` pour les variables de temps. Comparer par soustraction, `millis() - last >= INTERVAL`, reste correct quand le compteur repasse à zéro au bout d’environ 49,7 jours ; n’écrivez pas `millis() >= last + INTERVAL`.",
  "help.u.millis.3": "Une variable de temps par tâche donne une machine à états simple : l’exemple « multitâche avec millis() » fait clignoter deux LED à des rythmes différents tout en affichant le temps de fonctionnement, et le bouton avec anti-rebond applique la même idée. Utilisez `micros()` pour une résolution à la microseconde.",
  "help.ex.examples": "Exemples associés",
  "help.ex.intro": "« Charger sur le canevas » remplace le circuit actuel et lance la simulation ; « Insérer dans l’éditeur » place le code dans l’éditeur de programme de la puce actuelle (pas encore téléversé, vous pouvez le modifier) ; « Copier le code » le copie dans le presse-papiers.",
  "help.ex.wiring": "Câblage",
  "help.ex.usage": "Usage associé",
  "help.ex.code": "Code source",
  "help.ex.load": "Charger sur le canevas",
  "help.ex.insert": "Insérer dans l’éditeur",
  "help.ex.copy": "Copier le code",
  "help.ex.other": "Voir les exemples pour {board} ({n}) →",
  "help.toast.inserted": "Code inséré dans l’éditeur de {chip} — cliquez sur « Compiler et téléverser » pour l’appliquer",
  "help.toast.mismatch": "Inséré, mais ce code a été écrit pour {board} ; les broches peuvent ne pas correspondre",
  "help.toast.copied": "Code copié dans le presse-papiers",
  "help.toast.copy_failed": "Échec de la copie — sélectionnez le code dans la zone et copiez-le à la main",
  "help.toast.no_chip": "Aucun microcontrôleur sur le canevas : placez d’abord une carte ou une puce, ou utilisez « Charger sur le canevas »",
  "help.w.anode": "anode (+, patte longue)",
  "help.w.cathode": "cathode (−)",
  "help.w.onboard_led": "LED intégrée (L)",
  "help.w.red_led": "LED rouge",
  "help.w.yellow_led": "LED jaune",
  "help.w.green_led": "LED verte",
  "help.w.white_led": "LED blanche",
  "help.w.all_cathodes": "toutes les cathodes des LED",
  "help.w.internal_pullup": "pull-up interne",
  "help.w.pot_ends": "extrémités",
  "help.w.wiper": "curseur",
  "help.w.gate": "grille G",
  "help.w.drain": "drain D",
  "help.w.source": "source S",
  "help.w.flyback": "en antiparallèle sur le moteur (cathode au +), en diode de roue libre",
  "help.w.common_gnd": "masse commune",
  "help.w.servo_sig": "fil de signal",
  "help.w.servo_vcc": "fil d’alimentation",
  "help.w.servo_gnd": "fil de masse",
  "help.w.backlight": "rétroéclairage",
  "help.w.contrast": "contraste",
  "help.w.pin_n4": "broche 4",
  "help.w.pin_n5": "broche 5",
  "help.w.pin_n6": "broche 6",
  "help.w.pin_n8": "broche 8",
  "ex.arddebounce": "MCU : bouton avec anti-rebond qui bascule une LED (millis)",
  "ex.ardnight": "MCU : veilleuse à photorésistance (LDR → PWM)",
  "ex.ardmulti": "MCU : multitâche avec millis() (sans delay)",
  "ex.ardmotor": "MCU : variateur de vitesse de moteur CC par MOSFET (PWM)",
  "ex.ardrelay": "MCU : module relais qui commande une lampe 12 V par minuterie",
  "ex.ardtone": "MCU : mélodie sur buzzer passif (tone)",
  "ex.tinyfade": "MCU : fondu PWM avec ATtiny85",
  "exd.arddebounce": "Chaque appui sur le bouton de D2 bascule la LED de D8 : l’entrée doit rester stable 30 ms pour qu’un changement compte, ainsi les rebonds ne la basculent pas deux fois ; le nombre d’appuis s’affiche dans le moniteur série.",
  "exd.ardnight": "5V → 10 kΩ → A0 → photorésistance → GND forme un diviseur : plus il fait sombre, plus la lecture est élevée et plus la LED blanche sur la broche PWM D9 brille. Modifiez la propriété « Intensité lumineuse » de la photorésistance pour essayer.",
  "exd.ardmulti": "Aucun delay() : la LED de D8 bascule toutes les 250 ms, celle de D7 toutes les 700 ms, et le temps de fonctionnement s’affiche chaque seconde — trois tâches en même temps.",
  "exd.ardmotor": "Potentiomètre → A0 → PWM sur D9 → MOSFET à niveau logique IRLZ44N → moteur CC. Le moteur a sa propre pile de 6 V avec masse commune avec l’Arduino, et une diode 1N4007 absorbe la surtension à la coupure.",
  "exd.ardrelay": "D7 commande un module relais (déclenchement à l’état haut) qui allume une lampe 12 V pendant 2 s puis l’éteint 2 s. Le circuit de la lampe est isolé de l’Arduino ; la broche ne fournit que quelques mA.",
  "exd.ardtone": "D8 attaque un buzzer passif via 100 Ω et joue une mélodie de 16 pas avec tone() (0 = silence) ; la fréquence de chaque note s’affiche dans le moniteur série.",
  "exd.tinyfade": "L’ATtiny85 produit du PWM sur PB0 (broche 5) et PB1 (broche 6) : la LED jaune s’allume progressivement pendant que la verte s’éteint, en boucle.",
  "wc.title": "Couleur du fil",
  "wc.n_wires": "{n} fils sélectionnés",
  "wc.red": "Rouge",
  "wc.black": "Noir",
  "wc.blue": "Bleu",
  "wc.green": "Vert",
  "wc.yellow": "Jaune",
  "wc.orange": "Orangé",
  "wc.white": "Blanc",
  "wc.purple": "Violet",
  "wc.gray": "Gris",
  "wc.brown": "Marron",
  "wc.custom": "Couleur personnalisée…",
  "wc.hint": "Les nouveaux fils prennent la dernière couleur choisie ; des fils de couleurs différentes ne sont jamais fusionnés automatiquement."
});
