// v10.1 pinout / usage reference panel, new examples and wire colours — 日本語
I18N.add('ja', {
  "help.btn": "ピン説明",
  "help.title": "ピン配置と使い方",
  "help.intro.arduino": "Arduino Uno R3（ATmega328P、16 MHz、5 V ロジック）：デジタルピン D0–D13 が 14 本（そのうち ~ 付きの 6 本は PWM 出力可）、アナログ入力 A0–A5 が 6 本（10 ビット ADC、デジタルピン D14–D19 としても使用可）。以下、ピン配置図、各ピンの機能、電気的定格、シミュレータの対応状況、よく使う回路、最後にワンクリックで読み込める作例の順に並んでいます。",
  "help.intro.attiny85": "ATtiny85（8 ピン DIP、8 ビット AVR）：汎用 I/O は PB0–PB4 の 5 本と PB5（初期設定では RESET）。ハードウェア UART はなく、PWM は PB0/PB1/PB4、ADC は PB2/PB3/PB4（PB5 も可）。Flash 8 KB、SRAM 512 B、EEPROM 512 B。出荷時は内蔵 8 MHz RC 発振器の 8 分周 = 1 MHz で動作します（CKDIV8 ヒューズ）。",
  "help.nav.pinout": "ピン配置図",
  "help.nav.table": "ピン一覧",
  "help.nav.limits": "電気的定格",
  "help.nav.sim": "シミュレータ対応",
  "help.nav.usage": "よく使う回路",
  "help.nav.examples": "作例",
  "help.cat.dig": "デジタル I/O",
  "help.cat.pwm": "PWM 出力",
  "help.cat.ana": "アナログ入力",
  "help.cat.com": "通信 (UART/SPI/I²C)",
  "help.cat.int": "外部割り込み",
  "help.cat.pwr": "電源",
  "help.cat.gnd": "グラウンド",
  "help.cat.spc": "特殊機能",
  "help.leg.nosim": "破線 = シミュレーション対象外",
  "help.th.pin": "ピン",
  "help.th.func": "機能と説明",
  "help.th.sim": "シミュレーション",
  "help.sim.yes": "対応",
  "help.sim.part": "一部対応",
  "help.sim.no": "非対応",
  "help.sim.absent": "部品にピンなし",
  "help.tag.dio": "デジタル入出力",
  "help.tag.pwm490": "PWM 約 490 Hz",
  "help.tag.pwm980": "PWM 約 980 Hz",
  "help.tag.tpwm": "PWM 出力 (analogWrite)",
  "help.tag.adc": "アナログ入力（10 ビット ADC）",
  "help.tag.rx": "シリアル受信 RX",
  "help.tag.tx": "シリアル送信 TX",
  "help.tag.int0": "外部割り込み INT0",
  "help.tag.int1": "外部割り込み INT1",
  "help.tag.ss": "SPI スレーブ選択 SS",
  "help.tag.mosi": "SPI MOSI（マスター出力）",
  "help.tag.miso": "SPI MISO（マスター入力）",
  "help.tag.sck": "SPI クロック SCK",
  "help.tag.sda": "I²C データ SDA",
  "help.tag.scl": "I²C クロック SCL",
  "help.tag.led": "オンボード LED「L」",
  "help.tag.aref": "アナログ基準電圧 AREF",
  "help.tag.ioref": "I/O 電圧基準 IOREF",
  "help.tag.reset": "リセット（Low でアクティブ）",
  "help.tag.treset": "リセット RESET（Low でアクティブ）",
  "help.tag.v5": "5 V 電源",
  "help.tag.v33": "3.3 V 電源出力",
  "help.tag.vin": "外部電源入力 VIN",
  "help.tag.gnd": "グラウンド GND",
  "help.tag.vcc": "電源 VCC",
  "help.tag.usi_di": "USI データ入力 DI / I²C SDA",
  "help.tag.usi_do": "USI データ出力 DO",
  "help.tag.usi_sck": "USI クロック USCK / I²C SCL",
  "help.tag.xtal": "外付け水晶用ピン",
  "help.tag.ain": "アナログコンパレータ入力",
  "help.tag.taref": "外部基準電圧 AREF",
  "help.tag.tled": "Digispark などのオンボード LED",
  "help.tag.icsp": "ICSP 書き込み端子",
  "help.note.d0d1": "D0/D1 はボード上の USB シリアル変換チップにつながっています。書き込みと `Serial` 通信の両方で使うため、外部回路をつなぐと書き込みに失敗することがあります。シミュレータでは D0/D1 は普通の I/O として使え、`Serial` は直接シリアルモニタにつながります。",
  "help.note.tone": "`tone()` は Timer2 を使うため、発音中は D3 と D11 の PWM が使えません。",
  "help.note.servo": "Servo ライブラリは Timer1 を使うため、D9 と D10 で `analogWrite()` が使えなくなります（サーボをどのピンにつないでも同じです）。",
  "help.note.d13": "オンボード LED「L」は D13（`LED_BUILTIN`）で駆動されます（R3 ではオペアンプでバッファ）。D13 は SPI の SCK でもあるので、SPI 使用中は LED がちらつきます。",
  "help.note.a4a5": "A4/A5 は I²C の SDA/SCL を兼ねます（R3 では AREF の隣に同じ信号の SDA/SCL ピンがあります）。I²C 使用中はアナログ入力に使えません。",
  "help.note.v5": "ボード上の 5 V レギュレータ（VIN/DC 給電時）または USB から供給されます。センサや小さなモジュールの電源に使えます。USB 給電時はボード全体が 500 mA のリセッタブルヒューズで制限されます。ここに安定化した 5 V を入力することもできますが、レギュレータと保護回路を通りません。",
  "help.note.v33": "ボード上の 3.3 V レギュレータ出力、最大 50 mA。",
  "help.note.vin": "外部電源入力（DC ジャックからダイオード経由でつながる）。推奨 7–12 V、限界 6–20 V。7 V 未満では 5 V が不安定になり、12 V を超えるとレギュレータが発熱しやすくなります。",
  "help.note.gnd": "GND ピンはすべて内部でつながっています。外部電源（電池、モーター用電源）のマイナスは必ず Arduino の GND に接続し（共通グラウンド）、信号の基準をそろえます。",
  "help.note.reset": "Low にするとリセットされます（リセットボタンもここにつながっています）。シミュレーションの部品にはこのピンがないので、プログラムエディタの「リセット」ボタンを使ってください。",
  "help.note.aref": "外部アナログ基準電圧の入力（0–5 V）で、`analogReference(EXTERNAL)` と組み合わせて使います。電圧をつなぐ前に必ず EXTERNAL に設定しないとチップを壊すおそれがあります。シミュレーションの部品にはこのピンがなく、EXTERNAL は VCC (5 V) として扱われます。",
  "help.note.ioref": "シールドにボードの I/O 電圧を知らせるピン（Uno では 5 V）。シミュレーションの部品にはありません。",
  "help.note.sdascl": "R3 で追加された I²C 用ピンで、電気的には A4/A5 と同じです。I²C（Wire ライブラリ）はシミュレーション非対応です。",
  "help.note.icsp": "6 ピンの ISP 書き込み端子で、ブートローダの書き込みやライタでの直接書き込みに使います。シミュレータでは不要です。",
  "help.note.pb5": "初期設定は RESET（Low でリセット、内部プルアップ）で、通常の I/O としては使えません。シミュレータでも 0.3·VCC 未満に下げるとチップはリセット状態のままになります。RSTDISBL ヒューズを書き込むと（駆動能力の弱い）I/O になりますが、以後は ISP で書き込めず、高電圧ライタでないと戻せません。シミュレータではプロパティの「PB5 を通常の I/O として使う」をオンにできます。",
  "help.note.pb34": "PB3/PB4 は外付け水晶用のピンを兼ね、外付け水晶を使うと I/O にできません。初期設定は内蔵 RC 発振器なので自由に使えます。",
  "help.note.pb0": "物理ピン 5：PWM (OC0A)、USI の DI / I²C SDA、ISP 書き込みの MOSI。外部 AREF にも使えます（その場合 I/O には使えません）。",
  "help.note.pb1": "物理ピン 6：PWM (OC0B / OC1A)、USI の DO、ISP 書き込みの MISO。Digispark などのボードではオンボード LED がここにつながっています。",
  "help.note.pb2": "物理ピン 7：唯一の外部割り込み INT0、アナログ入力 A1 (ADC1)、USI クロック USCK / I²C SCL、ISP 書き込みの SCK。",
  "help.note.vcc": "電源電圧 2.7–5.5 V（ATtiny85V は 1.8–5.5 V）。クロックが高いほど高い電圧が必要です（20 MHz には 4.5 V 以上）。VCC と GND の間にはチップのすぐ近くに 100 nF のパスコンを入れます。",
  "help.lim.arduino.1": "I/O ピン 1 本あたり：推奨 20 mA 以下、絶対最大 40 mA。超えるとポートが壊れるおそれがあります。",
  "help.lim.arduino.2": "全ピンの合計電流（VCC/GND の総電流）は 200 mA 以下。",
  "help.lim.arduino.3": "ピン電圧は −0.5 V … VCC + 0.5 V の範囲内。入力 Low < 0.3·VCC（1.5 V）、High > 0.6·VCC（3 V）。",
  "help.lim.arduino.4": "内部プルアップ抵抗 20–50 kΩ（`INPUT_PULLUP`）。",
  "help.lim.arduino.5": "アナログ入力 0–5 V（初期の基準電圧 = VCC）、10 ビット → 0–1023、1 段階あたり約 4.9 mV。信号源インピーダンスは 10 kΩ 以下を推奨。",
  "help.lim.arduino.6": "VIN / DC ジャック：推奨 7–12 V、限界 6–20 V。USB 給電は 5 V で、500 mA のリセッタブルヒューズ付き。",
  "help.lim.arduino.7": "3.3V ピンは最大 50 mA。5V ピンから取れる電流は電源しだい（USB ならボード全体で 500 mA 以下、VIN 給電ならレギュレータの発熱で制限）。",
  "help.lim.arduino.8": "ATmega328P：16 MHz、Flash 32 KB（うち 0.5 KB はブートローダ）、SRAM 2 KB、EEPROM 1 KB。",
  "help.lim.attiny85.1": "I/O ピン 1 本あたり：推奨 20 mA 以下、絶対最大 40 mA。VCC/GND の総電流は 200 mA 以下。",
  "help.lim.attiny85.2": "動作電圧 2.7–5.5 V（ATtiny85V：1.8–5.5 V）。10 MHz までは 2.7 V から、20 MHz には 4.5–5.5 V が必要。",
  "help.lim.attiny85.3": "ピン電圧 −0.5 V … VCC + 0.5 V。内部プルアップ 20–50 kΩ。",
  "help.lim.attiny85.4": "ADC：10 ビット、シングルエンド入力 4 本 ADC0–ADC3 = PB5 / PB2 / PB4 / PB3。基準電圧は VCC、内部 1.1 V、内部 2.56 V、PB0 の外部 AREF から選択。",
  "help.lim.attiny85.5": "メモリ：Flash 8 KB、SRAM 512 B、EEPROM 512 B。",
  "help.lim.attiny85.6": "クロック：出荷時は内蔵 8 MHz RC ÷ 8 = 1 MHz（CKDIV8 ヒューズ）。内蔵 8 MHz、PLL 16 MHz、外付け水晶（PB3/PB4 を使用）に変更可能。",
  "help.sim.ok": "シミュレーション対応：`pinMode` / `digitalWrite` / `digitalRead`（`INPUT_PULLUP` を含む）、`analogRead`（10 ビット）、`analogWrite`（実チップと同じ PWM 周波数）、`millis` / `micros` / `delay`、`tone` / `noTone`、`pulseIn`、`shiftOut`、Servo、LiquidCrystal、`Serial`（シリアルモニタ）など。ピンの出力抵抗・プルアップ・電流も回路計算に含まれ、1 ピン 40 mA を超えると警告が出ます。",
  "help.sim.no.1": "外部割り込み `attachInterrupt()`：コンパイル時に非対応と表示されます。ポーリングか `millis()` を使ってください。",
  "help.sim.no.2": "I²C（Wire ライブラリ）、SPI ライブラリ、UART のピンレベルのタイミング：D0/D1、A4/A5、D10–D13 の通信機能はモデル化されず、`Serial` はシリアルモニタとだけやり取りします。",
  "help.sim.no.3": "ライブラリによるタイマーの副作用（tone で D3/D11 の PWM が止まる、Servo で D9/D10 の PWM が止まる）は説明のみで、シミュレーションでは再現しません。",
  "help.sim.no.4": "Uno の部品には RESET、AREF、IOREF、独立した SDA/SCL ピン、ICSP 端子がありません。`analogReference(EXTERNAL)` は VCC、`INTERNAL` は 1.1 V として扱います。",
  "help.sim.no.5": "ATtiny85 にはハードウェア UART がありません。シミュレータの `Serial` は仮想的なもので、デバッグ表示をシリアルモニタに出すためだけのものです。",
  "help.sim.no.6": "過電流でチップが「焼損」することはなく、警告が出るだけです。電気的定格と照らし合わせて確認してください。",
  "help.sim.no.7": "EEPROM、スリープモード、ウォッチドッグ、ヒューズ設定、レジスタの直接操作（`PORTB`、`DDRB` など）は非対応です。",
  "help.sim.no.8": "命令の実行時間はモデル化しません。コードは一瞬で実行され、時間を進めるのは `delay()` や `millis()` などだけです。上限を超える無限ループはエラーで停止します。",
  "help.usage.intro": "各節に配線のポイントとそのままコピーできるコード、関連する作例へのリンクがあります。",
  "help.u.power.t": "電源のとり方",
  "help.u.power.1": "Uno の給電方法は 3 通り：① USB 5 V（最も簡単、ボード全体で 500 mA 以下）、② DC ジャックか VIN に 7–12 V を入れ、ボード上のレギュレータで 5 V にする、③ 安定化した 5 V を 5V ピンに直接入れる（レギュレータと保護を通らないため、間違えるとボードが壊れます）。シミュレータではプロパティで USB と VIN を選べます。",
  "help.u.power.2": "5V と 3.3V のピンはセンサや小さなモジュールの電源には使えますが、モーター、複数のサーボ、ハイパワー LED には使わないでください。電圧が下がってマイコンがリセットします。大電流の負荷は別電源にし、そのマイナスを Arduino の GND に接続します（共通グラウンド）。",
  "help.u.power.3": "ATtiny85 はチップ単体でレギュレータがありません。VCC に 2.7–5.5 V を直接つなぎます（単 3 電池 3 本の 4.5 V、USB 5 V、リチウムイオン電池 1 セルの 3.0–4.2 V など）。電圧が低すぎると起動せず（シミュレータでは OFF 表示）、5.5 V を超えると壊れるおそれがあります。",
  "help.u.power.4": "各チップの VCC–GND 間のすぐ近くに 100 nF のパスコンを入れます。モーターなど誘導性の負荷はマイコンと別の電源にするか、少なくとも大きめのコンデンサで平滑します。",
  "help.u.dout.t": "デジタル出力と LED の電流制限抵抗",
  "help.u.dout.1": "`pinMode(pin, OUTPUT)` のあと `digitalWrite(pin, HIGH)` / `LOW` で約 5 V / 0 V を出力します。出力ピンは電流を流し出すことも吸い込むこともでき、1 本あたり 20 mA 以下を推奨します。",
  "help.u.dout.2": "LED には必ず直列抵抗を入れます：R = (Vcc − Vf) / I。例：5 V、赤色 LED の Vf ≈ 2 V、10 mA なら R = (5 − 2) / 0.01 = 300 Ω で、標準値の 330 Ω を選びます。220 Ω（約 14 mA）でもかまいません。青・白色 LED は Vf ≈ 3 V なので、同じ電流なら約 200 Ω です。",
  "help.u.dout.3": "長い足（アノード +）を抵抗経由でピンへ、短い足（カソード −）を GND へつなぐと HIGH で点灯。LED を 5V 側につないでピンで電流を吸い込むと LOW で点灯します。1 本のピンで複数の LED や 20 mA を超える負荷を動かすときはトランジスタか MOSFET を使います。",
  "help.u.din.t": "ボタン入力：プルアップ、プルダウン、チャタリング対策",
  "help.u.din.1": "`INPUT_PULLUP` で内部 20–50 kΩ のプルアップが有効になります。ボタンをピンと GND の間に入れるだけで外付け抵抗は不要。離すと HIGH、押すと LOW（論理が逆）になります。いちばん簡単な配線です。",
  "help.u.din.2": "プルダウン配線：ボタンを 5V とピンの間に入れ、ピンから GND へ 10 kΩ、`pinMode(pin, INPUT)`。押すと HIGH になります。`INPUT` モードでピンが浮いていると値がでたらめに変わるので、プルアップかプルダウンが必須です。",
  "help.u.din.3": "機械式ボタンは押したり離したりするときに数ミリ秒チャタリングし、1 回押しただけで何回も読まれることがあります。対策は、値が変わってから 20–50 ms 変化しないことを確かめて確定すること（長い `delay()` ではなく `millis()` で計時）、またはハードウェアの RC フィルタです。作例「チャタリング対策ボタン」でソフトウェアの方法を示しています。",
  "help.u.ain.t": "アナログ入力：ボリューム、分圧、CdS・サーミスタ",
  "help.u.ain.1": "`analogRead(A0)` は 0 V から基準電圧（初期値 VCC = 5 V）までを 0–1023 で返します：電圧 = 読み値 × 5.0 / 1024。1 回の変換は約 100 µs。`analogReference(INTERNAL)` で内部 1.1 V 基準に切り替えると小さな電圧の測定に向きます。",
  "help.u.ain.2": "ボリューム：両端を 5V と GND、中点（ワイパー）を A0 へ。回すと読み値が 0–1023 で変わります。分圧抵抗：Vout = Vin × R2 / (R1 + R2) で、5 V を超える電圧（12 V 電池など）を 0–5 V に下げて測れます。入力が VCC を超えないようにしてください。",
  "help.u.ain.3": "CdS（光センサ、LDR）やサーミスタ（NTC）は固定抵抗と直列にして分圧回路を作り、中点をアナログピンへつなぎます。固定抵抗はセンサの中間付近の抵抗値（よく 10 kΩ）にします。LDR を下側にすると暗いほど電圧が上がり、NTC は温度が上がると抵抗が下がります。`map()` で読み値を必要な範囲に変換できます。",
  "help.u.ain.4": "ADC の信号源インピーダンスは 10 kΩ 以下が望ましく、分圧抵抗が大きすぎると値がふらつきます。アナログピンと GND の間に 100 nF を入れると安定します。A0–A5 は普通のデジタルピン（D14–D19）としても使えます。ATtiny85 のアナログピンは A1 (PB2)、A2 (PB4)、A3 (PB3) で、A0 (PB5) はリセットピンなので通常は使いません。",
  "help.u.pwm.t": "PWM：調光と速度制御",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` は ~ 付きのピンに PWM の方形波を出します：デューティ比 = 値 / 255、平均電圧 ≈ 5 V × 値 / 255。Uno では D5、D6 が約 980 Hz、D3、D9、D10、D11 が約 490 Hz。ATtiny85 では PB0、PB1、PB4 が使えます。",
  "help.u.pwm.2": "PWM は LED の明るさ（目には平均の明るさに見える）やモーターの速度の調整に向いています。本当のアナログ電圧ではないので、滑らかな電圧が必要なら RC ローパスフィルタを入れます。~ のないピンで `analogWrite()` を呼ぶと、128 未満は LOW、それ以上は HIGH になります。",
  "help.u.pwm.3": "0 と 255 では一定の LOW / HIGH になります。明るさの感じ方は非線形なので、ホタル点滅は 2 乗カーブにすると自然に見えます。PWM 波形はオシロスコープで観察できます（作例「ボリュームで調光」）。",
  "help.u.motor.t": "モーター：トランジスタ / MOSFET 駆動とフライバックダイオード",
  "help.u.motor.1": "ピンが流せるのは約 20 mA なので、モーターは直接動かせません。NPN トランジスタか N チャネル MOSFET でローサイドスイッチを作ります：負荷を電源 + とドレイン (D) の間に、ソース (S) を GND に、ゲート (G) を 100–220 Ω 経由で PWM ピンへ。さらにゲートから GND へ 10 kΩ を入れ、電源投入時やリセット中にピンが浮いてもモーターが回らないようにします。",
  "help.u.motor.2": "ロジックレベル MOSFET（IRLZ44N など、ゲート 5 V で十分オン）を選びます。IRF540 などの一般品はゲート 10 V で規定されていて、5 V では十分にオンせず発熱します。トランジスタの場合はベースに 1 kΩ 程度の抵抗を直列に入れます。",
  "help.u.motor.3": "モーター、リレーのコイル、ソレノイドは誘導性負荷で、オフにした瞬間に大きな逆起電力が出ます。負荷と並列に逆向きのフライバックダイオード（1N4007 など、カソードを電源 + 側）を必ず入れます。モーター用電源のマイナスは Arduino の GND と接続します。正転・逆転には H ブリッジドライバ（L298N、TB6612 など）を使います。",
  "help.u.relay.t": "リレーと大きな負荷",
  "help.u.relay.1": "リレーは小さなコイル電流で大電流・高電圧の接点を切り替えます。COM が共通端子、NO はノーマルオープン（コイル通電中に COM とつながる）、NC はノーマルクローズ。接点側の回路はマイコンと電気的に絶縁されているので、12 V のランプや商用電源の機器も切り替えられます。",
  "help.u.relay.2": "リレーモジュールにはトランジスタ、フライバックダイオード、表示 LED が内蔵されています。VCC/GND を 5V/GND に、IN を任意のデジタルピンにつなぐだけです。トリガ方式に注意：多くのモジュールは Low トリガ（IN = LOW で吸着）です。シミュレータのモジュールはプロパティで High/Low トリガを選べます。",
  "help.u.relay.3": "リレー単体のコイル電流は普通 70 mA 以上なので、ピンに直接つなげません。トランジスタで駆動し、フライバックダイオードを入れます。商用電源は危険です。ケース入りの完成品モジュールを使い、接点の定格電流を守ってください。",
  "help.u.tone.t": "ブザーと tone()",
  "help.u.tone.1": "`tone(pin, 周波数)` は任意のデジタルピンにデューティ 50% の方形波を出し、`tone(pin, 周波数, 時間)` は時間がたつと自動で止まり、`noTone(pin)` で止めます。同時に鳴らせる `tone()` は 1 つだけで、Timer2 を使うため D3/D11 の PWM が止まります。",
  "help.u.tone.2": "パッシブブザーや小型スピーカーは `tone()` の方形波で鳴り、周波数で音の高さが決まります。アクティブブザーは発振回路を内蔵しているので `digitalWrite(HIGH)` だけで鳴りますが、音の高さは固定です。",
  "help.u.tone.3": "ブザーには 100 Ω 程度の抵抗を直列に入れます。8 Ω のスピーカーは電流が大きすぎるのでトランジスタで駆動します。よく使う音の周波数：C4 262、D4 294、E4 330、F4 349、G4 392、A4 440、B4 494、C5 523 Hz。",
  "help.u.servo.t": "サーボモーター",
  "help.u.servo.1": "サーボの線は 3 本：信号（橙/黄）、電源 +（赤）、GND（茶/黒）。信号は約 20 ms 周期（50 Hz）のパルスで、パルス幅（普通 1–2 ms）で角度が決まります。Servo ライブラリは初期設定で 544–2400 µs を 0–180° に対応させます。`attach(pin)` のあと `write(角度)` で使います。",
  "help.u.servo.2": "Servo ライブラリは Timer1 を使うので、D9、D10 の PWM が使えなくなります（信号線自体はどのデジタルピンでもかまいません）。Uno では最大 12 個のサーボを使えます。",
  "help.u.servo.3": "サーボは起動時や拘束時に数百 mA、ときには 1 A を超える電流を流します。SG90 のような小型サーボ 1 個なら 5V ピンから給電できますが、複数や大型のサーボは独立した 5–6 V 電源を使って GND を共通にし、サーボ電源に 100–470 µF のコンデンサを入れるとリセットを防げます。",
  "help.u.lcd.t": "LCD1602 液晶ディスプレイ",
  "help.u.lcd.1": "LCD1602（HD44780 コントローラ）は 4 ビットモードなら信号線 6 本（RS、E、D4–D7）だけで済み、RW は GND（書き込みのみ）。7 引数の書き方なら RW もピンで制御します。`LiquidCrystal lcd(rs, en, d4, d5, d6, d7)` のあと `lcd.begin(16, 2)`、`lcd.setCursor(列, 行)`、`lcd.print()`、`lcd.clear()`。",
  "help.u.lcd.2": "電源：VSS を GND、VDD を 5V へ。V0 はコントラスト調整で、普通は 10 kΩ ボリュームの中点（両端は 5V/GND）につなぎます。合っていないと真っ黒なブロックが出たり何も見えなかったりします。A/K はバックライト LED で、A を抵抗経由で 5V（抵抗内蔵のモジュールも多い）かピンへ、K を GND へつなぎます。",
  "help.u.lcd.3": "ピンが足りないときは I²C 変換基板（PCF8574、A4/A5 だけを使用）が便利ですが、このシミュレータは I²C 非対応なのでパラレル接続を使ってください。行と列は 0 から数えます：2 行目は `setCursor(0, 1)`。",
  "help.u.serial.t": "シリアルでデバッグ",
  "help.u.serial.1": "`Serial.begin(9600)` でシリアルを開き（ボーレートはシリアルモニタと合わせる）、`Serial.print()` / `println()` で文字や数値を送ります。変数の値、どの分岐を通ったか、センサの読み値などを表示する、最もよく使うデバッグ方法です。",
  "help.u.serial.2": "`Serial.available()` は受信済みのバイト数、`Serial.read()` は 1 バイト読み込み、`Serial.readStringUntil('\\n')` は 1 行を読み込みます。シミュレータではシリアルモニタの入力欄から文字を送れます。",
  "help.u.serial.3": "Uno のシリアルは D0/D1 を使うので、使用中はこの 2 本にほかの回路をつながないでください。頻繁に表示しすぎるとプログラムが遅くなるので（9600 bps で 1 ミリ秒に約 1 文字）、`millis()` で間隔をあけます。ATtiny85 にはハードウェア UART がなく、シミュレータの `Serial` はデバッグ専用です。",
  "help.u.millis.t": "millis() によるノンブロッキング処理",
  "help.u.millis.1": "`delay()` の間、プログラムはほかに何もできません（ボタンも読めず、ほかの LED も更新できない）。`millis()` は電源投入からのミリ秒数を返すので、「現在時刻 − 前回時刻 ≥ 間隔」で判定すれば、いくつもの処理を同時に進められます。",
  "help.u.millis.2": "時刻の変数は `unsigned long` にします。引き算で比べる `millis() - last >= INTERVAL` なら、約 49.7 日後にカウンタが一周しても正しく動きます。`millis() >= last + INTERVAL` とは書かないでください。",
  "help.u.millis.3": "処理ごとに時刻の変数を 1 つ持てば簡単なステートマシンになります。作例「millis() で並行処理」は 2 つの LED を別々の周期で点滅させながら稼働時間を表示し、「チャタリング対策ボタン」も同じ考え方です。マイクロ秒単位が必要なら `micros()` を使います。",
  "help.ex.examples": "関連する作例",
  "help.ex.intro": "「キャンバスに読み込む」は現在の回路を置き換えてシミュレーションを開始します。「エディタに挿入」はコードを今のチップのプログラムエディタに入れます（まだ書き込まれないので、編集してから書き込めます）。「コードをコピー」はクリップボードにコピーします。",
  "help.ex.wiring": "配線",
  "help.ex.usage": "関連する使い方",
  "help.ex.code": "コード",
  "help.ex.load": "キャンバスに読み込む",
  "help.ex.insert": "エディタに挿入",
  "help.ex.copy": "コードをコピー",
  "help.ex.other": "{board} の作例を見る（{n} 件）→",
  "help.toast.inserted": "コードを {chip} のエディタに挿入しました。「コンパイルして書き込み」で反映されます",
  "help.toast.mismatch": "挿入しましたが、このコードは {board} 用なのでピンが合わない可能性があります",
  "help.toast.copied": "コードをクリップボードにコピーしました",
  "help.toast.copy_failed": "コピーできませんでした。コード欄で選択して手動でコピーしてください",
  "help.toast.no_chip": "キャンバスにマイコンがありません。先にボードかチップを置くか、「キャンバスに読み込む」を使ってください",
  "help.w.anode": "アノード（+、長い足）",
  "help.w.cathode": "カソード（−）",
  "help.w.onboard_led": "オンボード LED（L）",
  "help.w.red_led": "赤色 LED",
  "help.w.yellow_led": "黄色 LED",
  "help.w.green_led": "緑色 LED",
  "help.w.white_led": "白色 LED",
  "help.w.all_cathodes": "すべての LED のカソード",
  "help.w.internal_pullup": "内部プルアップを使用",
  "help.w.pot_ends": "両端",
  "help.w.wiper": "中点（ワイパー）",
  "help.w.gate": "ゲート G",
  "help.w.drain": "ドレイン D",
  "help.w.source": "ソース S",
  "help.w.flyback": "モーターと逆向きに並列（カソードを + 側）、フライバック用",
  "help.w.common_gnd": "共通グラウンド",
  "help.w.servo_sig": "信号線",
  "help.w.servo_vcc": "電源線",
  "help.w.servo_gnd": "GND 線",
  "help.w.backlight": "バックライト",
  "help.w.contrast": "コントラスト",
  "help.w.pin_n4": "4 番ピン",
  "help.w.pin_n5": "5 番ピン",
  "help.w.pin_n6": "6 番ピン",
  "help.w.pin_n8": "8 番ピン",
  "ex.arddebounce": "マイコン: チャタリング対策ボタンで LED を切り替え (millis)",
  "ex.ardnight": "マイコン: CdS センサーの常夜灯 (LDR → PWM)",
  "ex.ardmulti": "マイコン: millis() で並行処理 (delay なし)",
  "ex.ardmotor": "マイコン: MOSFET で DC モーターの速度制御 (PWM)",
  "ex.ardrelay": "マイコン: リレーモジュールで 12V ランプをタイマー点灯",
  "ex.ardtone": "マイコン: パッシブブザーでメロディ (tone)",
  "ex.tinyfade": "マイコン: ATtiny85 の PWM ホタル点滅",
  "exd.arddebounce": "D2 のボタンを押すたびに D8 の LED が切り替わります。入力が 30 ms 安定してから確定するので、チャタリングで二重に切り替わりません。押した回数はシリアルモニタに表示されます。",
  "exd.ardnight": "5V → 10 kΩ → A0 → CdS → GND で分圧回路を作ります。暗いほど読み値が大きくなり、PWM ピン D9 の白色 LED が明るくなります。CdS の「光の強さ」プロパティを変えて試してください。",
  "exd.ardmulti": "delay() をまったく使いません。D8 の LED は 250 ms ごと、D7 の LED は 700 ms ごとに切り替わり、毎秒稼働時間を表示します。3 つの処理が同時に進みます。",
  "exd.ardmotor": "ボリューム → A0 → D9 の PWM → ロジックレベル MOSFET IRLZ44N → DC モーター。モーターは専用の 6 V 電池で動き、GND は Arduino と共通。1N4007 フライバックダイオードがオフ時の逆起電力を吸収します。",
  "exd.ardrelay": "D7 でリレーモジュール（High トリガ）を動かし、12 V ランプを 2 秒点灯、2 秒消灯させます。ランプの回路は Arduino と絶縁されていて、ピンが流すのは数 mA だけです。",
  "exd.ardtone": "D8 から 100 Ω 経由でパッシブブザーを鳴らし、tone() で 16 拍のメロディ（0 は休符）を演奏します。各音の周波数をシリアルモニタに表示します。",
  "exd.tinyfade": "ATtiny85 が PB0（5 番ピン）と PB1（6 番ピン）に PWM を出力します。黄色 LED が明るくなるにつれて緑色 LED が暗くなり、これを繰り返します。",
  "wc.title": "ワイヤーの色",
  "wc.n_wires": "{n} 本のワイヤーを選択中",
  "wc.red": "赤",
  "wc.black": "黒",
  "wc.blue": "青",
  "wc.green": "緑",
  "wc.yellow": "黄",
  "wc.orange": "オレンジ",
  "wc.white": "白",
  "wc.purple": "紫",
  "wc.gray": "グレー",
  "wc.brown": "茶",
  "wc.custom": "カスタム色…",
  "wc.hint": "新しいワイヤーは最後に選んだ色になります。色の違うワイヤーは自動で結合されません。"
});
