// v10.1 pinout / usage reference panel, new examples and wire colours — 한국어
I18N.add('ko', {
  "help.btn": "핀 설명",
  "help.title": "핀 배치와 사용법",
  "help.intro.arduino": "Arduino Uno R3 (ATmega328P, 16 MHz, 5 V 로직): 디지털 핀 D0–D13 14개(그중 ~ 표시가 있는 6개는 PWM 출력 가능), 아날로그 입력 A0–A5 6개(10비트 ADC, 디지털 핀 D14–D19로도 사용 가능). 아래에 핀 배치도, 핀별 기능, 전기적 한계, 시뮬레이터 지원 여부, 자주 쓰는 회로, 마지막으로 클릭 한 번에 불러올 수 있는 예제가 있습니다.",
  "help.intro.attiny85": "ATtiny85 (8핀 DIP, 8비트 AVR): 범용 I/O PB0–PB4 5개와 PB5(기본값은 RESET). 하드웨어 UART가 없고, PWM은 PB0/PB1/PB4, ADC는 PB2/PB3/PB4(PB5도 가능). Flash 8 KB, SRAM 512 B, EEPROM 512 B. 출고 시 내부 8 MHz RC 발진기를 8분주한 1 MHz로 동작합니다(CKDIV8 퓨즈).",
  "help.nav.pinout": "핀 배치도",
  "help.nav.table": "핀 표",
  "help.nav.limits": "전기적 한계",
  "help.nav.sim": "시뮬레이터 지원",
  "help.nav.usage": "자주 쓰는 회로",
  "help.nav.examples": "예제",
  "help.cat.dig": "디지털 I/O",
  "help.cat.pwm": "PWM 출력",
  "help.cat.ana": "아날로그 입력",
  "help.cat.com": "통신 (UART/SPI/I²C)",
  "help.cat.int": "외부 인터럽트",
  "help.cat.pwr": "전원",
  "help.cat.gnd": "접지",
  "help.cat.spc": "특수 기능",
  "help.leg.nosim": "점선 = 시뮬레이션 안 됨",
  "help.th.pin": "핀",
  "help.th.func": "기능과 설명",
  "help.th.sim": "시뮬레이션",
  "help.sim.yes": "지원",
  "help.sim.part": "일부 지원",
  "help.sim.no": "미지원",
  "help.sim.absent": "부품에 없는 핀",
  "help.tag.dio": "디지털 입출력",
  "help.tag.pwm490": "PWM 약 490 Hz",
  "help.tag.pwm980": "PWM 약 980 Hz",
  "help.tag.tpwm": "PWM 출력 (analogWrite)",
  "help.tag.adc": "아날로그 입력 (10비트 ADC)",
  "help.tag.rx": "시리얼 수신 RX",
  "help.tag.tx": "시리얼 송신 TX",
  "help.tag.int0": "외부 인터럽트 INT0",
  "help.tag.int1": "외부 인터럽트 INT1",
  "help.tag.ss": "SPI 슬레이브 선택 SS",
  "help.tag.mosi": "SPI MOSI (마스터 출력)",
  "help.tag.miso": "SPI MISO (마스터 입력)",
  "help.tag.sck": "SPI 클록 SCK",
  "help.tag.sda": "I²C 데이터 SDA",
  "help.tag.scl": "I²C 클록 SCL",
  "help.tag.led": "보드 내장 LED “L”",
  "help.tag.aref": "아날로그 기준 전압 AREF",
  "help.tag.ioref": "I/O 전압 기준 IOREF",
  "help.tag.reset": "리셋 (LOW에서 동작)",
  "help.tag.treset": "리셋 RESET (LOW에서 동작)",
  "help.tag.v5": "5 V 전원",
  "help.tag.v33": "3.3 V 전원 출력",
  "help.tag.vin": "외부 전원 입력 VIN",
  "help.tag.gnd": "접지 GND",
  "help.tag.vcc": "전원 VCC",
  "help.tag.usi_di": "USI 데이터 입력 DI / I²C SDA",
  "help.tag.usi_do": "USI 데이터 출력 DO",
  "help.tag.usi_sck": "USI 클록 USCK / I²C SCL",
  "help.tag.xtal": "외부 크리스털 핀",
  "help.tag.ain": "아날로그 비교기 입력",
  "help.tag.taref": "외부 기준 전압 AREF",
  "help.tag.tled": "Digispark 등 보드의 내장 LED",
  "help.tag.icsp": "ICSP 프로그래밍 헤더",
  "help.note.d0d1": "D0/D1은 보드의 USB-시리얼 칩에 연결되어 있습니다. 업로드와 `Serial` 통신 모두 이 핀을 쓰므로 외부 회로를 연결하면 업로드가 실패할 수 있습니다. 시뮬레이터에서는 D0/D1을 일반 I/O로 쓸 수 있고 `Serial`은 시리얼 모니터에 바로 연결됩니다.",
  "help.note.tone": "`tone()`은 Timer2를 사용하므로 소리가 나는 동안 D3과 D11의 PWM이 동작하지 않습니다.",
  "help.note.servo": "Servo 라이브러리는 Timer1을 사용하므로 D9와 D10에서 `analogWrite()`를 쓸 수 없게 됩니다(서보를 어느 핀에 연결했는지와 무관).",
  "help.note.d13": "보드 내장 LED “L”은 D13(`LED_BUILTIN`)으로 구동되며 R3에서는 연산 증폭기로 버퍼링됩니다. D13은 SPI의 SCK이기도 해서 SPI 사용 중에는 LED가 깜박입니다.",
  "help.note.a4a5": "A4/A5는 I²C의 SDA/SCL을 겸합니다(R3에는 AREF 옆에 같은 신호의 SDA/SCL 핀이 따로 있습니다). I²C를 쓰는 동안에는 아날로그 입력으로 쓸 수 없습니다.",
  "help.note.v5": "보드의 5 V 레귤레이터(VIN/DC 전원일 때) 또는 USB에서 공급됩니다. 센서와 작은 모듈에 전원을 줄 수 있으며, USB 전원일 때는 보드 전체가 500 mA 복구형 퓨즈로 제한됩니다. 안정화된 5 V를 여기로 넣을 수도 있지만 레귤레이터와 보호 회로를 거치지 않습니다.",
  "help.note.v33": "보드의 3.3 V 레귤레이터 출력, 최대 50 mA.",
  "help.note.vin": "외부 전원 입력(DC 잭이 다이오드를 거쳐 연결됨). 권장 7–12 V, 한계 6–20 V. 7 V 미만이면 5 V가 불안정해지고, 12 V를 넘으면 레귤레이터가 쉽게 과열됩니다.",
  "help.note.gnd": "모든 GND 핀은 서로 연결되어 있습니다. 외부 전원(배터리, 모터 전원)의 음극은 반드시 Arduino GND에 연결해야(공통 접지) 신호의 기준이 같아집니다.",
  "help.note.reset": "LOW로 당기면 리셋됩니다(리셋 버튼도 여기에 연결). 시뮬레이션 부품에는 이 핀이 없으니 프로그램 편집기의 “리셋” 버튼을 사용하세요.",
  "help.note.aref": "외부 아날로그 기준 전압 입력(0–5 V)으로 `analogReference(EXTERNAL)`과 함께 씁니다. 전압을 연결하기 전에 반드시 EXTERNAL로 설정해야 하며, 그렇지 않으면 칩이 손상될 수 있습니다. 시뮬레이션 부품에는 이 핀이 없고 EXTERNAL은 VCC(5 V)로 처리됩니다.",
  "help.note.ioref": "실드에 보드의 I/O 전압(Uno는 5 V)을 알려 주는 핀. 시뮬레이션 부품에는 없습니다.",
  "help.note.sdascl": "R3에서 추가된 I²C 핀으로 전기적으로 A4/A5와 같습니다. I²C(Wire 라이브러리)는 시뮬레이션되지 않습니다.",
  "help.note.icsp": "6핀 ISP 프로그래밍 헤더로, 부트로더를 굽거나 프로그래머로 직접 업로드할 때 씁니다. 시뮬레이터에서는 필요 없습니다.",
  "help.note.pb5": "기본값은 RESET(LOW에서 리셋, 내부 풀업)이라 일반 I/O로 쓸 수 없습니다. 시뮬레이터에서도 0.3·VCC 아래로 내리면 칩이 리셋 상태로 유지됩니다. RSTDISBL 퓨즈를 구워야 (구동력이 약한) I/O가 되지만, 그 후에는 ISP로 프로그래밍할 수 없고 고전압 프로그래머로만 복구할 수 있습니다. 시뮬레이터에서는 속성에서 “PB5를 일반 I/O로 사용”을 켤 수 있습니다.",
  "help.note.pb34": "PB3/PB4는 외부 크리스털 핀을 겸하므로 외부 크리스털을 쓰면 I/O로 쓸 수 없습니다. 기본 클록은 내부 RC 발진기라서 자유롭게 쓸 수 있습니다.",
  "help.note.pb0": "물리 5번 핀: PWM(OC0A), USI의 DI / I²C SDA, ISP 프로그래밍의 MOSI, 외부 AREF로도 사용 가능(이 경우 I/O로는 사용 불가).",
  "help.note.pb1": "물리 6번 핀: PWM(OC0B / OC1A), USI의 DO, ISP 프로그래밍의 MISO. Digispark 같은 보드는 내장 LED를 여기에 연결합니다.",
  "help.note.pb2": "물리 7번 핀: 유일한 외부 인터럽트 INT0, 아날로그 입력 A1(ADC1), USI 클록 USCK / I²C SCL, ISP 프로그래밍의 SCK.",
  "help.note.vcc": "전원 2.7–5.5 V(ATtiny85V는 1.8–5.5 V). 클록이 높을수록 더 높은 전압이 필요합니다(20 MHz는 4.5 V 이상). VCC와 GND 사이, 칩 가까이에 100 nF 디커플링 커패시터를 둡니다.",
  "help.lim.arduino.1": "I/O 핀 하나당: 권장 20 mA 이하, 절대 최대 40 mA. 넘으면 포트가 영구 손상될 수 있습니다.",
  "help.lim.arduino.2": "모든 핀의 전류 합계(VCC/GND 총전류)는 200 mA 이하.",
  "help.lim.arduino.3": "핀 전압은 −0.5 V … VCC + 0.5 V 범위를 벗어나면 안 됩니다. 입력 LOW < 0.3·VCC(1.5 V), HIGH > 0.6·VCC(3 V).",
  "help.lim.arduino.4": "내부 풀업 저항 20–50 kΩ(`INPUT_PULLUP`).",
  "help.lim.arduino.5": "아날로그 입력 0–5 V(기본 기준 = VCC), 10비트 → 0–1023, 한 단계 약 4.9 mV. 신호원 임피던스는 10 kΩ 이하 권장.",
  "help.lim.arduino.6": "VIN / DC 잭: 권장 7–12 V, 한계 6–20 V. USB 전원은 5 V이며 500 mA 복구형 퓨즈가 있습니다.",
  "help.lim.arduino.7": "3.3V 핀은 최대 50 mA. 5V 핀에서 쓸 수 있는 전류는 전원에 따라 다릅니다(USB면 보드 전체 500 mA 이하, VIN이면 레귤레이터 발열로 제한).",
  "help.lim.arduino.8": "ATmega328P: 16 MHz, Flash 32 KB(부트로더가 0.5 KB 사용), SRAM 2 KB, EEPROM 1 KB.",
  "help.lim.attiny85.1": "I/O 핀 하나당: 권장 20 mA 이하, 절대 최대 40 mA. VCC/GND 총전류 200 mA 이하.",
  "help.lim.attiny85.2": "동작 전압 2.7–5.5 V(ATtiny85V: 1.8–5.5 V). 10 MHz까지는 2.7 V부터, 20 MHz는 4.5–5.5 V 필요.",
  "help.lim.attiny85.3": "핀 전압 −0.5 V … VCC + 0.5 V. 내부 풀업 20–50 kΩ.",
  "help.lim.attiny85.4": "ADC: 10비트, 단일 입력 4개 ADC0–ADC3 = PB5 / PB2 / PB4 / PB3. 기준 전압은 VCC, 내부 1.1 V, 내부 2.56 V, PB0의 외부 AREF 중 선택.",
  "help.lim.attiny85.5": "메모리: Flash 8 KB, SRAM 512 B, EEPROM 512 B.",
  "help.lim.attiny85.6": "클록: 출고 시 내부 8 MHz RC ÷ 8 = 1 MHz(CKDIV8 퓨즈). 내부 8 MHz, PLL 16 MHz, 외부 크리스털(PB3/PB4 사용)로 변경 가능.",
  "help.sim.ok": "시뮬레이션 지원: `pinMode` / `digitalWrite` / `digitalRead`(`INPUT_PULLUP` 포함), `analogRead`(10비트), `analogWrite`(실제 칩과 같은 PWM 주파수), `millis` / `micros` / `delay`, `tone` / `noTone`, `pulseIn`, `shiftOut`, Servo, LiquidCrystal, LiquidCrystal_I2C, DHT, OneWire + DallasTemperature, `Serial`(시리얼 모니터) 등. 핀의 출력 저항, 풀업, 전류도 회로 계산에 포함되며 핀 하나가 40 mA를 넘으면 경고가 표시됩니다.",
  "help.sim.no.1": "외부 인터럽트 `attachInterrupt()`: 컴파일 시 미지원으로 표시됩니다. 폴링이나 `millis()`를 대신 쓰세요.",
  "help.sim.no.3": "라이브러리의 타이머 부작용(tone이 D3/D11 PWM을, Servo가 D9/D10 PWM을 멈추는 것)은 설명에만 있고 시뮬레이션에서는 재현되지 않습니다.",
  "help.sim.no.4": "Uno 부품에는 RESET, AREF, IOREF, 별도의 SDA/SCL 핀, ICSP 헤더가 없습니다. `analogReference(EXTERNAL)`은 VCC, `INTERNAL`은 1.1 V로 처리합니다.",
  "help.sim.no.5": "ATtiny85에는 하드웨어 UART가 없습니다. 시뮬레이터의 `Serial`은 가상이며 디버그 메시지를 시리얼 모니터에 보내는 용도로만 쓰입니다.",
  "help.sim.no.6": "과전류로 칩이 “타지” 않습니다. 시뮬레이터는 경고만 하므로 전기적 한계와 비교해 직접 확인하세요.",
  "help.sim.no.7": "EEPROM, 슬립 모드, 워치독, 퓨즈 설정, 레지스터 직접 조작(`PORTB`, `DDRB` 등)은 지원하지 않습니다.",
  "help.sim.no.8": "명령 실행 시간은 모델링하지 않습니다. 코드는 즉시 실행되고 `delay()`, `millis()` 등만 시간을 진행시킵니다. 연산 한도를 넘는 무한 루프는 오류로 멈춥니다.",
  "help.usage.intro": "각 절에는 배선 요점과 바로 복사할 수 있는 코드, 관련 예제 링크가 있습니다.",
  "help.u.power.t": "전원 공급 방법",
  "help.u.power.1": "Uno의 전원 공급 방법은 세 가지입니다. ① USB 5 V(가장 간단, 보드 전체 500 mA 이하) ② DC 잭이나 VIN에 7–12 V를 넣고 보드의 레귤레이터로 5 V를 만듦 ③ 안정화된 5 V를 5V 핀에 직접 넣음(레귤레이터와 보호 회로를 거치지 않으므로 잘못 연결하면 보드가 망가짐). 시뮬레이터에서는 속성에서 USB 또는 VIN 전원을 고를 수 있습니다.",
  "help.u.power.2": "5V와 3.3V 핀은 센서나 작은 모듈의 전원으로는 괜찮지만 모터, 여러 개의 서보, 고출력 LED에는 쓰지 마세요. 전압이 떨어져 마이크로컨트롤러가 리셋됩니다. 큰 전류 부하는 별도 전원을 쓰고 그 음극을 Arduino GND에 연결합니다(공통 접지).",
  "help.u.power.3": "ATtiny85는 칩뿐이고 레귤레이터가 없습니다. VCC에 2.7–5.5 V를 직접 연결합니다. 예: AA 건전지 3개(4.5 V), USB 5 V, 리튬이온 전지 1셀(3.0–4.2 V). 전압이 너무 낮으면 시작하지 않고(시뮬레이터에 OFF 표시) 5.5 V를 넘으면 손상될 수 있습니다.",
  "help.u.power.4": "칩마다 VCC와 GND 사이 바로 옆에 100 nF 디커플링 커패시터를 둡니다. 모터 같은 유도성 부하는 마이크로컨트롤러와 다른 전원을 쓰거나, 적어도 큰 필터 커패시터를 추가합니다.",
  "help.u.dout.t": "디지털 출력과 LED 저항",
  "help.u.dout.1": "`pinMode(pin, OUTPUT)` 다음 `digitalWrite(pin, HIGH)` / `LOW`로 약 5 V / 0 V를 출력합니다. 출력 핀은 전류를 내보낼 수도 받아들일 수도 있으며 핀당 20 mA 이하를 권장합니다.",
  "help.u.dout.2": "LED에는 반드시 직렬 저항을 넣습니다: R = (Vcc − Vf) / I. 예: 5 V, 빨간 LED Vf ≈ 2 V, 10 mA → R = (5 − 2) / 0.01 = 300 Ω, 표준값 330 Ω 사용. 220 Ω(약 14 mA)도 괜찮습니다. 파란색·흰색 LED는 Vf ≈ 3 V라서 같은 전류에 약 200 Ω이 필요합니다.",
  "help.u.dout.3": "긴 다리(애노드 +)를 저항을 거쳐 핀에, 짧은 다리(캐소드 −)를 GND에 연결하면 HIGH = 켜짐. LED를 5V 쪽에 연결하고 핀이 전류를 받아들이게 하면 LOW = 켜짐입니다. 한 핀으로 여러 LED나 20 mA가 넘는 부하를 구동하려면 트랜지스터나 MOSFET을 쓰세요.",
  "help.u.din.t": "버튼 입력: 풀업, 풀다운, 디바운싱",
  "help.u.din.1": "`INPUT_PULLUP`은 내부 20–50 kΩ 풀업을 켭니다. 버튼을 핀과 GND 사이에 연결하면 외부 저항이 필요 없습니다. 떼면 HIGH, 누르면 LOW(반대 논리)입니다. 가장 간단한 배선입니다.",
  "help.u.din.2": "풀다운 배선: 버튼을 5V와 핀 사이에, 핀에서 GND로 10 kΩ, `pinMode(pin, INPUT)`. 누르면 HIGH입니다. `INPUT` 모드에서 핀이 떠 있으면 값이 무작위로 바뀌므로 풀업이나 풀다운이 꼭 필요합니다.",
  "help.u.din.3": "기계식 버튼은 누르거나 뗄 때 몇 밀리초 동안 채터링이 생겨 한 번 누른 것이 여러 번으로 읽힐 수 있습니다. 디바운싱: 값이 바뀐 뒤 20–50 ms 동안 그대로일 때만 인정합니다(긴 `delay()` 대신 `millis()`로 시간 측정). 또는 하드웨어 RC 필터를 씁니다. 예제 “디바운스 버튼”에서 소프트웨어 방식을 볼 수 있습니다.",
  "help.u.ain.t": "아날로그 입력: 가변저항, 분압, 조도·온도 센서",
  "help.u.ain.1": "`analogRead(A0)`는 0 V부터 기준 전압(기본 VCC = 5 V)까지를 0–1023으로 돌려줍니다: 전압 = 읽은 값 × 5.0 / 1024. 변환 한 번에 약 100 µs. `analogReference(INTERNAL)`로 내부 1.1 V 기준을 쓰면 작은 전압 측정에 좋습니다.",
  "help.u.ain.2": "가변저항: 양 끝을 5V와 GND에, 가운데 단자(와이퍼)를 A0에 연결하면 돌릴 때 읽은 값이 0–1023에서 바뀝니다. 분압 저항: Vout = Vin × R2 / (R1 + R2)로 5 V보다 높은 전압(예: 12 V 배터리)을 0–5 V로 낮춰 측정할 수 있지만, 입력이 VCC를 넘지 않게 하세요.",
  "help.u.ain.3": "조도 센서(LDR)나 서미스터(NTC)는 고정 저항과 직렬로 분압 회로를 만들고 중간점을 아날로그 핀에 연결합니다. 고정 저항은 센서의 중간 동작점 저항값(보통 10 kΩ)으로 고릅니다. LDR을 아래쪽에 두면 어두울수록 전압이 높아지고, NTC는 온도가 오르면 저항이 줄어듭니다. `map()`으로 읽은 값을 원하는 범위로 바꿀 수 있습니다.",
  "help.u.ain.4": "ADC는 신호원 임피던스 10 kΩ 이하가 좋습니다. 분압 저항이 너무 크면 값이 흔들리므로 아날로그 핀과 GND 사이에 100 nF를 넣으세요. A0–A5는 일반 디지털 핀(D14–D19)으로도 쓸 수 있습니다. ATtiny85의 아날로그 핀은 A1(PB2), A2(PB4), A3(PB3)이며 A0(PB5)은 리셋 핀이라 보통 쓰지 않습니다.",
  "help.u.pwm.t": "PWM: 밝기와 속도 조절",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)`는 ~ 표시가 있는 핀에 PWM 구형파를 출력합니다: 듀티비 = 값 / 255, 평균 전압 ≈ 5 V × 값 / 255. Uno의 D5, D6은 약 980 Hz, D3, D9, D10, D11은 약 490 Hz이며 ATtiny85는 PB0, PB1, PB4를 씁니다.",
  "help.u.pwm.2": "PWM은 LED 밝기(눈에는 평균 밝기로 보임)와 모터 속도 조절에 알맞습니다. 진짜 아날로그 전압이 아니므로 매끄러운 전압이 필요하면 RC 저역 통과 필터를 넣습니다. ~ 표시가 없는 핀에서 `analogWrite()`를 호출하면 128 미만은 LOW, 그 이상은 HIGH가 됩니다.",
  "help.u.pwm.3": "0과 255는 일정한 LOW / HIGH입니다. 사람이 느끼는 밝기는 비선형이라 숨쉬는 LED는 제곱 곡선을 쓰면 더 자연스럽습니다. PWM 파형은 오실로스코프로 볼 수 있습니다(예제 “가변저항 밝기 조절”).",
  "help.u.motor.t": "모터: 트랜지스터 / MOSFET 구동과 플라이백 다이오드",
  "help.u.motor.1": "핀은 약 20 mA만 낼 수 있어 모터를 직접 구동할 수 없습니다. NPN 트랜지스터나 N채널 MOSFET으로 로우사이드 스위치를 만듭니다: 부하를 전원 +와 드레인(D) 사이에, 소스(S)를 GND에, 게이트(G)를 100–220 Ω을 거쳐 PWM 핀에 연결하고, 게이트에서 GND로 10 kΩ을 넣어 전원 투입이나 리셋 중 핀이 떠 있어도 모터가 돌지 않게 합니다.",
  "help.u.motor.2": "로직 레벨 MOSFET(예: IRLZ44N, 게이트 5 V로 완전히 켜짐)을 고르세요. IRF540 같은 일반 MOSFET은 게이트 10 V 기준으로 규정되어 있어 5 V에서는 덜 켜져 발열합니다. 트랜지스터를 쓸 때는 베이스에 약 1 kΩ 저항을 직렬로 넣습니다.",
  "help.u.motor.3": "모터, 릴레이 코일, 솔레노이드는 유도성 부하라서 끄는 순간 큰 역기전력이 생깁니다. 부하와 병렬로 역방향 플라이백 다이오드(예: 1N4007, 캐소드를 전원 + 쪽)를 반드시 넣으세요. 모터 전원의 음극은 Arduino GND와 연결해야 합니다. 정·역회전에는 H 브리지 드라이버(L298N, TB6612 등)를 씁니다.",
  "help.u.relay.t": "릴레이와 큰 부하",
  "help.u.relay.1": "릴레이는 작은 코일 전류로 큰 전류·고전압 접점을 전환합니다. COM은 공통 단자, NO는 평상시 열림(코일에 전류가 흐를 때 COM과 연결), NC는 평상시 닫힘입니다. 접점 회로는 마이크로컨트롤러와 전기적으로 절연되어 12 V 램프나 상용 전원 기기도 켜고 끌 수 있습니다.",
  "help.u.relay.2": "릴레이 모듈에는 트랜지스터, 플라이백 다이오드, 표시 LED가 내장되어 있어 VCC/GND를 5V/GND에, IN을 아무 디지털 핀에 연결하면 됩니다. 트리거 방식에 주의하세요. 많은 모듈이 LOW 트리거(IN = LOW일 때 동작)이며, 시뮬레이터의 모듈은 속성에서 HIGH/LOW 트리거를 고를 수 있습니다.",
  "help.u.relay.3": "릴레이 단품의 코일 전류는 보통 70 mA 이상이라 핀에 직접 연결할 수 없습니다. 트랜지스터로 구동하고 플라이백 다이오드를 넣으세요. 상용 전원은 위험하므로 케이스가 있는 완제품 모듈을 쓰고 접점의 정격 전류를 지키세요.",
  "help.u.tone.t": "부저와 tone()",
  "help.u.tone.1": "`tone(pin, 주파수)`는 아무 디지털 핀에 듀티 50% 구형파를 출력하고, `tone(pin, 주파수, 시간)`은 시간이 지나면 저절로 멈추며, `noTone(pin)`으로 멈춥니다. 동시에 하나의 `tone()`만 울릴 수 있고, Timer2를 써서 D3/D11의 PWM이 멈춥니다.",
  "help.u.tone.2": "수동 부저와 작은 스피커는 `tone()`의 구형파가 있어야 소리가 나며 주파수가 음높이를 정합니다. 능동 부저는 발진 회로가 내장되어 `digitalWrite(HIGH)`만으로 울리지만 음높이가 고정됩니다.",
  "help.u.tone.3": "부저에는 약 100 Ω 저항을 직렬로 넣습니다. 8 Ω 스피커는 전류가 너무 커서 트랜지스터로 구동해야 합니다. 자주 쓰는 음 주파수: C4 262, D4 294, E4 330, F4 349, G4 392, A4 440, B4 494, C5 523 Hz.",
  "help.u.servo.t": "서보 모터",
  "help.u.servo.1": "서보에는 선이 세 가닥 있습니다: 신호(주황/노랑), 전원 +(빨강), GND(갈색/검정). 신호는 약 20 ms 주기(50 Hz)의 펄스이고 펄스 폭(보통 1–2 ms)이 각도를 정합니다. Servo 라이브러리는 기본으로 544–2400 µs를 0–180°에 대응시킵니다. `attach(pin)` 다음 `write(각도)`로 씁니다.",
  "help.u.servo.2": "Servo 라이브러리는 Timer1을 쓰므로 D9, D10의 PWM을 쓸 수 없게 됩니다(신호선 자체는 어느 디지털 핀이든 됩니다). Uno는 최대 12개의 서보를 구동할 수 있습니다.",
  "help.u.servo.3": "서보는 시작하거나 막혔을 때 수백 mA, 때로는 1 A가 넘는 전류를 씁니다. SG90 같은 소형 서보 한 개는 5V 핀으로 구동할 수 있지만, 여러 개나 큰 서보는 별도의 5–6 V 전원과 공통 접지를 쓰고, 서보 전원에 100–470 µF 커패시터를 달면 리셋을 줄일 수 있습니다.",
  "help.u.lcd.t": "LCD1602 디스플레이",
  "help.u.lcd.1": "LCD1602(HD44780 컨트롤러)는 4비트 모드에서 신호선 6개(RS, E, D4–D7)만 필요하고 RW는 GND(쓰기 전용)에 연결합니다. 인자 7개 형식을 쓰면 RW도 핀으로 제어합니다. `LiquidCrystal lcd(rs, en, d4, d5, d6, d7)` 다음 `lcd.begin(16, 2)`, `lcd.setCursor(열, 행)`, `lcd.print()`, `lcd.clear()`.",
  "help.u.serial.t": "시리얼 디버깅",
  "help.u.serial.1": "`Serial.begin(9600)`으로 시리얼을 열고(보드레이트는 시리얼 모니터와 같아야 함) `Serial.print()` / `println()`으로 문자와 숫자를 보냅니다. 변수 값, 실행된 분기, 센서 값을 출력하는 가장 흔한 디버깅 방법입니다.",
  "help.u.serial.2": "`Serial.available()`은 받은 바이트 수, `Serial.read()`는 한 바이트 읽기, `Serial.readStringUntil('\\n')`은 한 줄 읽기입니다. 시뮬레이터에서는 시리얼 모니터의 입력란에 글자를 입력해 보냅니다.",
  "help.u.serial.3": "Uno의 시리얼은 D0/D1을 쓰므로 사용 중에는 이 두 핀에 다른 회로를 연결하지 마세요. 너무 자주 출력하면 프로그램이 느려지므로(9600 bps는 1 ms에 약 1글자) `millis()`로 간격을 둡니다. ATtiny85에는 하드웨어 UART가 없고 시뮬레이터의 `Serial`은 디버깅 전용입니다.",
  "help.u.millis.t": "millis()로 논블로킹 타이밍",
  "help.u.millis.1": "`delay()` 동안 프로그램은 아무것도 못 합니다(버튼을 읽지도, 다른 LED를 바꾸지도 못함). `millis()`는 전원을 켠 뒤의 밀리초를 돌려주므로 “현재 − 이전 ≥ 간격”으로 판단하면 여러 일을 동시에 처리할 수 있습니다.",
  "help.u.millis.2": "시간 변수는 `unsigned long`을 쓰세요. 뺄셈으로 비교하는 `millis() - last >= INTERVAL`은 약 49.7일 뒤 카운터가 한 바퀴 돌아도 올바르게 동작합니다. `millis() >= last + INTERVAL`처럼 쓰지 마세요.",
  "help.u.millis.3": "작업마다 시간 변수를 하나씩 두면 간단한 상태 기계가 됩니다. 예제 “millis() 멀티태스킹”은 두 LED를 서로 다른 주기로 깜박이면서 가동 시간을 출력하고, “디바운스 버튼”도 같은 방법을 씁니다. 마이크로초 단위가 필요하면 `micros()`를 쓰세요.",
  "help.ex.examples": "관련 예제",
  "help.ex.intro": "“캔버스에 불러오기”는 현재 회로를 바꾸고 시뮬레이션을 시작합니다. “편집기에 넣기”는 코드를 현재 칩의 프로그램 편집기에 넣습니다(아직 업로드되지 않으므로 고친 뒤 업로드할 수 있음). “코드 복사”는 클립보드에 복사합니다.",
  "help.ex.wiring": "배선",
  "help.ex.usage": "관련 사용법",
  "help.ex.code": "코드",
  "help.ex.load": "캔버스에 불러오기",
  "help.ex.insert": "편집기에 넣기",
  "help.ex.copy": "코드 복사",
  "help.ex.other": "{board} 예제 보기({n}개) →",
  "help.toast.inserted": "코드를 {chip} 편집기에 넣었습니다. “컴파일 후 업로드”를 눌러 적용하세요",
  "help.toast.mismatch": "넣었지만 이 코드는 {board}용이라 핀이 맞지 않을 수 있습니다",
  "help.toast.copied": "코드를 클립보드에 복사했습니다",
  "help.toast.copy_failed": "복사하지 못했습니다. 코드 상자에서 직접 선택해 복사하세요",
  "help.toast.no_chip": "캔버스에 마이크로컨트롤러가 없습니다. 먼저 보드나 칩을 놓거나 “캔버스에 불러오기”를 쓰세요",
  "help.w.anode": "애노드(+, 긴 다리)",
  "help.w.cathode": "캐소드(−)",
  "help.w.onboard_led": "보드 내장 LED(L)",
  "help.w.red_led": "빨간 LED",
  "help.w.yellow_led": "노란 LED",
  "help.w.green_led": "초록 LED",
  "help.w.white_led": "흰색 LED",
  "help.w.all_cathodes": "모든 LED의 캐소드",
  "help.w.internal_pullup": "내부 풀업 사용",
  "help.w.pot_ends": "양 끝",
  "help.w.wiper": "가운데 단자",
  "help.w.gate": "게이트 G",
  "help.w.drain": "드레인 D",
  "help.w.source": "소스 S",
  "help.w.flyback": "모터와 역방향 병렬(캐소드를 + 쪽), 플라이백용",
  "help.w.common_gnd": "공통 접지",
  "help.w.servo_sig": "신호선",
  "help.w.servo_vcc": "전원선",
  "help.w.servo_gnd": "접지선",
  "help.w.backlight": "백라이트",
  "help.w.contrast": "명암",
  "help.w.pin_n4": "4번 핀",
  "help.w.pin_n5": "5번 핀",
  "help.w.pin_n6": "6번 핀",
  "help.w.pin_n8": "8번 핀",
  "ex.arddebounce": "MCU: 디바운스 버튼으로 LED 토글 (millis)",
  "ex.ardnight": "MCU: 조도 센서 수면등 (LDR → PWM)",
  "ex.ardmulti": "MCU: millis() 멀티태스킹 (delay 없음)",
  "ex.ardmotor": "MCU: MOSFET으로 DC 모터 속도 제어 (PWM)",
  "ex.ardrelay": "MCU: 릴레이 모듈로 12V 램프 타이머 제어",
  "ex.ardtone": "MCU: 수동 부저로 멜로디 연주 (tone)",
  "ex.tinyfade": "MCU: ATtiny85 PWM 숨쉬는 LED",
  "exd.arddebounce": "D2의 버튼을 누를 때마다 D8의 LED가 켜졌다 꺼졌다 합니다. 입력이 30 ms 동안 안정되어야 인정하므로 채터링으로 두 번 바뀌지 않습니다. 누른 횟수는 시리얼 모니터에 출력됩니다.",
  "exd.ardnight": "5V → 10 kΩ → A0 → 조도 센서 → GND로 분압 회로를 만듭니다. 어두울수록 읽은 값이 커지고 PWM 핀 D9의 흰색 LED가 밝아집니다. 조도 센서의 “빛의 세기” 속성을 바꿔 보세요.",
  "exd.ardmulti": "delay()를 전혀 쓰지 않습니다. D8의 LED는 250 ms마다, D7의 LED는 700 ms마다 바뀌고 매초 가동 시간을 출력합니다. 세 가지 작업이 동시에 진행됩니다.",
  "exd.ardmotor": "가변저항 → A0 → D9의 PWM → 로직 레벨 MOSFET IRLZ44N → DC 모터. 모터는 별도의 6 V 배터리로 돌고 Arduino와 접지를 공유하며, 1N4007 플라이백 다이오드가 끌 때의 역기전력을 흡수합니다.",
  "exd.ardrelay": "D7이 릴레이 모듈(HIGH 트리거)을 구동해 12 V 램프를 2초 켜고 2초 끕니다. 램프 회로는 Arduino와 절연되어 있고 핀은 몇 mA만 공급합니다.",
  "exd.ardtone": "D8이 100 Ω을 거쳐 수동 부저를 울리고 tone()으로 16박자 멜로디(0은 쉼표)를 연주합니다. 각 음의 주파수는 시리얼 모니터에 출력됩니다.",
  "exd.tinyfade": "ATtiny85가 PB0(5번 핀)과 PB1(6번 핀)에 PWM을 출력합니다. 노란 LED가 밝아지는 동안 초록 LED는 어두워지며 이를 반복합니다.",
  "wc.title": "전선 색",
  "wc.n_wires": "전선 {n}개 선택됨",
  "wc.red": "빨강",
  "wc.black": "검정",
  "wc.blue": "파랑",
  "wc.green": "초록",
  "wc.yellow": "노랑",
  "wc.orange": "주황",
  "wc.white": "흰색",
  "wc.purple": "보라",
  "wc.gray": "회색",
  "wc.brown": "갈색",
  "wc.custom": "사용자 지정 색…",
  "wc.hint": "새 전선은 마지막으로 고른 색을 씁니다. 색이 다른 전선은 자동으로 합쳐지지 않습니다."
});
