// v10.1 pinout / usage reference panel, new examples and wire colours — Português (Brasil)
I18N.add('pt-BR', {
  "help.btn": "Pinagem",
  "help.title": "Pinagem e uso",
  "help.intro.arduino": "Arduino Uno R3 (ATmega328P, 16 MHz, lógica de 5 V): 14 pinos digitais D0–D13 (6 deles, marcados com ~, podem gerar PWM) e 6 entradas analógicas A0–A5 (ADC de 10 bits, também utilizáveis como pinos digitais D14–D19). Abaixo: o mapa de pinos, a função de cada pino, os limites elétricos, o que o simulador suporta, os usos comuns e, no fim, exemplos que você carrega com um clique.",
  "help.intro.attiny85": "ATtiny85 (DIP de 8 pinos, AVR de 8 bits): 5 E/S de uso geral PB0–PB4 mais PB5 (RESET por padrão). Sem UART por hardware; PWM em PB0/PB1/PB4, ADC em PB2/PB3/PB4 (e PB5). Flash de 8 KB, SRAM de 512 B, EEPROM de 512 B; de fábrica roda com o oscilador RC interno de 8 MHz dividido por 8 = 1 MHz (fusível CKDIV8).",
  "help.nav.pinout": "Mapa de pinos",
  "help.nav.table": "Tabela de pinos",
  "help.nav.limits": "Limites elétricos",
  "help.nav.sim": "Suporte do simulador",
  "help.nav.usage": "Usos comuns",
  "help.nav.examples": "Exemplos",
  "help.cat.dig": "E/S digital",
  "help.cat.pwm": "Saída PWM",
  "help.cat.ana": "Entrada analógica",
  "help.cat.com": "Comunicação (UART/SPI/I²C)",
  "help.cat.int": "Interrupção externa",
  "help.cat.pwr": "Alimentação",
  "help.cat.gnd": "Terra",
  "help.cat.spc": "Função especial",
  "help.leg.nosim": "Tracejado = não simulado",
  "help.th.pin": "Pino",
  "help.th.func": "Funções e observações",
  "help.th.sim": "Simulado",
  "help.sim.yes": "sim",
  "help.sim.part": "em parte",
  "help.sim.no": "não",
  "help.sim.absent": "pino ausente no componente",
  "help.tag.dio": "entrada/saída digital",
  "help.tag.pwm490": "PWM ≈ 490 Hz",
  "help.tag.pwm980": "PWM ≈ 980 Hz",
  "help.tag.tpwm": "saída PWM (analogWrite)",
  "help.tag.adc": "entrada analógica (ADC de 10 bits)",
  "help.tag.rx": "recepção serial RX",
  "help.tag.tx": "transmissão serial TX",
  "help.tag.int0": "interrupção externa INT0",
  "help.tag.int1": "interrupção externa INT1",
  "help.tag.ss": "SPI seleção de escravo SS",
  "help.tag.mosi": "SPI MOSI (saída do mestre)",
  "help.tag.miso": "SPI MISO (entrada do mestre)",
  "help.tag.sck": "clock SPI SCK",
  "help.tag.sda": "dados I²C SDA",
  "help.tag.scl": "clock I²C SCL",
  "help.tag.led": "LED da placa “L”",
  "help.tag.aref": "referência analógica AREF",
  "help.tag.ioref": "referência de tensão de E/S IOREF",
  "help.tag.reset": "reset (ativo em nível baixo)",
  "help.tag.treset": "RESET (ativo em nível baixo)",
  "help.tag.v5": "alimentação de 5 V",
  "help.tag.v33": "saída de 3,3 V",
  "help.tag.vin": "entrada de alimentação externa VIN",
  "help.tag.gnd": "terra GND",
  "help.tag.vcc": "alimentação VCC",
  "help.tag.usi_di": "USI entrada de dados DI / I²C SDA",
  "help.tag.usi_do": "USI saída de dados DO",
  "help.tag.usi_sck": "USI clock USCK / I²C SCL",
  "help.tag.xtal": "pino de cristal externo",
  "help.tag.ain": "entrada do comparador analógico",
  "help.tag.taref": "referência externa AREF",
  "help.tag.tled": "LED da placa em placas tipo Digispark",
  "help.tag.icsp": "conector de gravação ICSP",
  "help.note.d0d1": "D0/D1 estão ligados ao chip USB-serial da placa: o upload e o `Serial` usam esses pinos, e um circuito externo neles pode fazer o upload falhar. No simulador, D0/D1 funcionam como E/S comuns e o `Serial` vai direto para o monitor serial.",
  "help.note.tone": "`tone()` usa o Timer2, então o PWM em D3 e D11 para de funcionar enquanto um tom toca.",
  "help.note.servo": "A biblioteca Servo usa o Timer1, então `analogWrite()` deixa de funcionar em D9 e D10 (qualquer que seja o pino do servo).",
  "help.note.d13": "O LED da placa “L” é acionado por D13 (`LED_BUILTIN`), com um amplificador operacional como buffer na R3. D13 também é o SCK do SPI, então o LED pisca enquanto o SPI está em uso.",
  "help.note.a4a5": "A4/A5 também são os pinos SDA/SCL do I²C (a R3 os repete num conector SDA/SCL ao lado do AREF). Enquanto o I²C está em uso, eles não podem ser entradas analógicas.",
  "help.note.v5": "Vem do regulador de 5 V da placa (com alimentação por VIN/DC) ou do USB. Serve para sensores e módulos pequenos; no USB, a placa inteira é limitada por um fusível rearmável de 500 mA. Também é possível injetar 5 V regulados aqui, mas isso contorna o regulador e as proteções.",
  "help.note.v33": "Saída do regulador de 3,3 V da placa, no máximo 50 mA.",
  "help.note.vin": "Entrada de alimentação externa (o conector DC chega a ela por um diodo): 7–12 V recomendados, limites de 6–20 V. Abaixo de 7 V os 5 V podem cair; acima de 12 V o regulador esquenta.",
  "help.note.gnd": "Todos os pinos GND estão interligados. O negativo de qualquer fonte externa (bateria, alimentação do motor) precisa ser ligado ao GND do Arduino (terra comum) para que os sinais tenham a mesma referência.",
  "help.note.reset": "Levar a nível baixo reinicia a placa; o botão de reset está ligado aqui. O componente simulado não tem este pino — use o botão “Reset” do editor de programa.",
  "help.note.aref": "Entrada de referência analógica externa (0–5 V) para `analogReference(EXTERNAL)`; selecione EXTERNAL antes de ligar uma tensão, senão o chip pode ser danificado. O componente simulado não tem este pino e trata EXTERNAL como VCC (5 V).",
  "help.note.ioref": "Informa aos shields a tensão de E/S da placa (5 V no Uno). Ausente no componente simulado.",
  "help.note.sdascl": "Conector I²C adicionado na R3, eletricamente igual a A4/A5. O I²C (biblioteca Wire) não é simulado.",
  "help.note.icsp": "Conector de gravação no circuito de 6 pinos, para gravar o bootloader ou enviar o programa com um gravador. Desnecessário no simulador.",
  "help.note.pb5": "Por padrão é RESET (ativo em nível baixo, pull-up interno), portanto não é uma E/S comum; no simulador, levá-lo abaixo de 0,3·VCC mantém o chip em reset. Só gravando o fusível RSTDISBL ele vira uma E/S (fraca), e depois disso a gravação por ISP deixa de funcionar até a recuperação com um gravador de alta tensão. No simulador, marque “PB5 como E/S comum” nas propriedades.",
  "help.note.pb34": "PB3/PB4 também são os pinos do cristal externo e não podem ser E/S com um cristal externo. O clock padrão é o oscilador RC interno, então eles estão livres.",
  "help.note.pb0": "Pino físico 5: PWM (OC0A), USI DI / I²C SDA, MOSI para a gravação ISP e AREF externo opcional (aí deixa de ser E/S).",
  "help.note.pb1": "Pino físico 6: PWM (OC0B / OC1A), USI DO, MISO para a gravação ISP. Placas como a Digispark têm o LED da placa aqui.",
  "help.note.pb2": "Pino físico 7: a única interrupção externa INT0, entrada analógica A1 (ADC1), clock USI USCK / I²C SCL, SCK para a gravação ISP.",
  "help.note.vcc": "Alimentação de 2,7–5,5 V (ATtiny85V: 1,8–5,5 V); clocks mais altos exigem mais tensão (20 MHz precisam de 4,5 V ou mais). Coloque um capacitor de desacoplamento de 100 nF entre VCC e GND bem perto do chip.",
  "help.lim.arduino.1": "Cada pino de E/S: 20 mA recomendados, 40 mA máximo absoluto — acima disso a porta pode ser danificada permanentemente.",
  "help.lim.arduino.2": "Corrente total de todos os pinos juntos (por VCC/GND): no máximo 200 mA.",
  "help.lim.arduino.3": "A tensão dos pinos deve ficar entre −0,5 V e VCC + 0,5 V; entrada BAIXA < 0,3·VCC (1,5 V), ALTA > 0,6·VCC (3 V).",
  "help.lim.arduino.4": "Resistores de pull-up internos de 20–50 kΩ (`INPUT_PULLUP`).",
  "help.lim.arduino.5": "Entradas analógicas de 0–5 V (referência padrão = VCC), 10 bits → 0–1023, cerca de 4,9 mV por passo; a impedância da fonte deve ser ≤ 10 kΩ.",
  "help.lim.arduino.6": "VIN / conector DC: 7–12 V recomendados, limites de 6–20 V; o USB fornece 5 V por um fusível rearmável de 500 mA.",
  "help.lim.arduino.7": "Pino 3.3V: no máximo 50 mA; quanto o pino 5V pode fornecer depende da fonte (placa inteira ≤ 500 mA no USB, limitado pelo aquecimento do regulador no VIN).",
  "help.lim.arduino.8": "ATmega328P: 16 MHz, Flash de 32 KB (0,5 KB para o bootloader), SRAM de 2 KB, EEPROM de 1 KB.",
  "help.lim.attiny85.1": "Cada pino de E/S: ≤ 20 mA recomendados, 40 mA máximo absoluto; total por VCC/GND ≤ 200 mA.",
  "help.lim.attiny85.2": "Alimentação de 2,7–5,5 V (ATtiny85V: 1,8–5,5 V); até 10 MHz a partir de 2,7 V, 20 MHz exigem 4,5–5,5 V.",
  "help.lim.attiny85.3": "Tensão dos pinos −0,5 V … VCC + 0,5 V; pull-ups internos de 20–50 kΩ.",
  "help.lim.attiny85.4": "ADC: 10 bits, 4 entradas simples ADC0–ADC3 = PB5 / PB2 / PB4 / PB3; referência VCC, interna de 1,1 V, interna de 2,56 V ou AREF externo em PB0.",
  "help.lim.attiny85.5": "Memória: Flash de 8 KB, SRAM de 512 B, EEPROM de 512 B.",
  "help.lim.attiny85.6": "Clock: de fábrica RC interno de 8 MHz ÷ 8 = 1 MHz (fusível CKDIV8); pode ser trocado para 8 MHz interno, PLL de 16 MHz ou cristal externo (usa PB3/PB4).",
  "help.sim.ok": "Simulado: `pinMode` / `digitalWrite` / `digitalRead` (incluindo `INPUT_PULLUP`), `analogRead` (10 bits), `analogWrite` (PWM na frequência do chip real), `millis` / `micros` / `delay`, `tone` / `noTone`, `pulseIn`, `shiftOut`, Servo, LiquidCrystal, `Serial` (monitor serial) e mais. A resistência de saída dos pinos, os pull-ups e as correntes entram no cálculo do circuito, e mais de 40 mA em um pino gera um aviso.",
  "help.sim.no.1": "Interrupções externas `attachInterrupt()`: aparecem como não suportadas na compilação — leia o pino periodicamente ou use `millis()`.",
  "help.sim.no.2": "Temporização em nível de pino do I²C (biblioteca Wire), da biblioteca SPI e da UART: as funções de comunicação de D0/D1, A4/A5 e D10–D13 não são modeladas; o `Serial` só conversa com o monitor serial.",
  "help.sim.no.3": "Efeitos colaterais das bibliotecas nos timers (tone desliga o PWM em D3/D11, Servo em D9/D10) são apenas documentados aqui; o simulador não os reproduz.",
  "help.sim.no.4": "O componente Uno não tem RESET, AREF, IOREF, conector SDA/SCL separado nem conector ICSP; `analogReference(EXTERNAL)` usa VCC, `INTERNAL` = 1,1 V.",
  "help.sim.no.5": "O ATtiny85 não tem UART por hardware: o `Serial` no simulador é virtual e só envia texto de depuração ao monitor serial.",
  "help.sim.no.6": "Sobrecorrente não “queima” o chip: o simulador apenas avisa, então confira o projeto com os limites elétricos.",
  "help.sim.no.7": "EEPROM, modos de suspensão, watchdog, configuração de fusíveis e acesso direto a registradores (como `PORTB`, `DDRB`) não são suportados.",
  "help.sim.no.8": "O tempo de execução das instruções não é modelado: o código roda instantaneamente e só `delay()`, `millis()` e afins fazem o tempo avançar; um laço infinito que excede o limite de cálculo para com um erro.",
  "help.usage.intro": "Cada seção resume a ligação, traz um trecho de código para copiar e indica exemplos relacionados.",
  "help.u.power.t": "Alimentação da placa",
  "help.u.power.1": "O Uno pode ser alimentado de três formas: ① USB 5 V (o mais simples, placa inteira ≤ 500 mA); ② 7–12 V no conector DC ou no VIN, regulados para 5 V na placa; ③ 5 V regulados direto no pino 5V (contorna o regulador e as proteções — um erro pode destruir a placa). No simulador, escolha alimentação USB ou VIN nas propriedades.",
  "help.u.power.2": "Os pinos 5V e 3.3V podem alimentar sensores e módulos pequenos, mas não motores, vários servos ou LEDs de potência: essas cargas derrubam a tensão e reiniciam o microcontrolador. Dê às cargas pesadas uma fonte própria e ligue o negativo dela ao GND do Arduino (terra comum).",
  "help.u.power.3": "O ATtiny85 é só um chip, sem regulador: o VCC vai direto a 2,7–5,5 V, por exemplo 3 pilhas AA (4,5 V), USB 5 V ou uma célula de íon-lítio (3,0–4,2 V). Com tensão baixa demais o chip não inicia (o simulador mostra OFF); acima de 5,5 V ele pode ser danificado.",
  "help.u.power.4": "Coloque um capacitor de desacoplamento de 100 nF entre VCC e GND ao lado de cada chip. Motores e outras cargas indutivas devem, de preferência, ter fonte separada ou pelo menos uma boa capacitância de filtro.",
  "help.u.dout.t": "Saída digital e resistores de LED",
  "help.u.dout.1": "Chame `pinMode(pin, OUTPUT)`; depois `digitalWrite(pin, HIGH)` / `LOW` fornece cerca de 5 V / 0 V. Uma saída pode fornecer ou absorver corrente; fique em 20 mA ou menos por pino.",
  "help.u.dout.2": "Um LED sempre precisa de um resistor em série: R = (Vcc − Vf) / I. Exemplo: 5 V, LED vermelho Vf ≈ 2 V, 10 mA → R = (5 − 2) / 0,01 = 300 Ω, use o valor comercial de 330 Ω; 220 Ω (cerca de 14 mA) também serve. LEDs azuis e brancos têm Vf ≈ 3 V e precisam de cerca de 200 Ω para a mesma corrente.",
  "help.u.dout.3": "Perna longa (ânodo +) pelo resistor até o pino, perna curta (cátodo −) no GND: HIGH = aceso. Ou ligue o LED ao 5V e deixe o pino absorver a corrente: LOW = aceso. Para vários LEDs ou mais de 20 mA em um pino, use um transistor ou MOSFET.",
  "help.u.din.t": "Entrada de botão: pull-up, pull-down e debounce",
  "help.u.din.1": "`INPUT_PULLUP` ativa o pull-up interno de 20–50 kΩ: ligue o botão entre o pino e o GND, sem resistor externo. Solto lê HIGH, pressionado lê LOW (lógica invertida). É a ligação mais simples.",
  "help.u.din.2": "Ligação com pull-down: botão entre o 5V e o pino, mais 10 kΩ do pino ao GND, com `pinMode(pin, INPUT)`; pressionado lê HIGH. No modo `INPUT` um pino solto lê valores aleatórios, então o pull-up ou pull-down é obrigatório.",
  "help.u.din.3": "Botões mecânicos trepidam por alguns milissegundos ao pressionar e soltar, e um toque pode ser lido várias vezes. Debounce: só aceite uma mudança depois que ela ficar estável por 20–50 ms (meça com `millis()`, não com um `delay()` longo), ou acrescente um filtro RC. O exemplo “botão com debounce” mostra a solução por software.",
  "help.u.ain.t": "Entrada analógica: potenciômetro, divisor, LDR / NTC",
  "help.u.ain.1": "`analogRead(A0)` retorna 0–1023 para 0 V até a referência (padrão VCC = 5 V): volts = leitura × 5,0 / 1024. Uma conversão leva cerca de 100 µs. `analogReference(INTERNAL)` passa para a referência interna de 1,1 V, boa para tensões pequenas.",
  "help.u.ain.2": "Potenciômetro: extremidades no 5V e no GND, cursor no A0; ao girar, a leitura percorre 0–1023. Divisor de tensão: Vout = Vin × R2 / (R1 + R2) reduz tensões acima de 5 V (como uma bateria de 12 V) para 0–5 V para medir — garanta que a entrada nunca passe de VCC.",
  "help.u.ain.3": "Um fotorresistor (LDR) ou termistor (NTC) vai em série com um resistor fixo formando um divisor, com o ponto médio na entrada analógica; escolha o resistor fixo perto do valor médio do sensor, tipicamente 10 kΩ. Com o LDR embaixo, mais escuro significa tensão maior; a resistência de um NTC cai quando ele esquenta. `map()` converte a leitura para a faixa que você precisa.",
  "help.u.ain.4": "O ADC quer uma impedância de fonte ≤ 10 kΩ; com um divisor de valor alto a leitura oscila — acrescente 100 nF da entrada analógica ao GND. A0–A5 também funcionam como pinos digitais comuns (D14–D19). No ATtiny85 as entradas analógicas são A1 (PB2), A2 (PB4) e A3 (PB3); A0 (PB5) é o pino de reset e normalmente não é usado.",
  "help.u.pwm.t": "PWM: brilho e velocidade",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` gera uma onda quadrada PWM nos pinos marcados com ~: ciclo de trabalho = valor / 255, tensão média ≈ 5 V × valor / 255. No Uno, D5 e D6 rodam a cerca de 980 Hz, D3, D9, D10 e D11 a cerca de 490 Hz; no ATtiny85, use PB0, PB1 ou PB4.",
  "help.u.pwm.2": "O PWM é ideal para o brilho de LEDs (o olho vê a média) e a velocidade de motores; não é uma tensão analógica de verdade — acrescente um filtro RC passa-baixa se precisar de uma tensão suave. Em um pino sem ~, `analogWrite()` dá LOW para valores < 128 e HIGH caso contrário.",
  "help.u.pwm.3": "0 e 255 dão LOW / HIGH constante. O brilho percebido não é linear, então uma curva quadrática deixa as transições mais naturais. Veja a forma de onda PWM no osciloscópio (exemplo “dimmer com potenciômetro”).",
  "help.u.motor.t": "Motores: transistor / MOSFET e diodo de roda livre",
  "help.u.motor.1": "Um pino fornece só cerca de 20 mA e não consegue acionar um motor diretamente. Use um transistor NPN ou um MOSFET canal N como chave no lado baixo: carga entre o + da fonte e o dreno (D), fonte (S) no GND, gate (G) ligado a um pino PWM por 100–220 Ω, mais 10 kΩ do gate ao GND para o motor ficar parado enquanto o pino está solto na ligação ou no reset.",
  "help.u.motor.2": "Escolha um MOSFET de nível lógico (como o IRLZ44N, totalmente ligado com 5 V no gate); modelos comuns como o IRF540 são especificados com 10 V no gate e esquentam se conduzirem só pela metade com 5 V. Com transistor, coloque cerca de 1 kΩ em série com a base.",
  "help.u.motor.3": "Motores, bobinas de relé e solenoides são cargas indutivas: ao desligar surge um grande pico de tensão reversa, então um diodo de roda livre (como o 1N4007, cátodo no + da fonte) precisa ficar em paralelo com a carga. O negativo da fonte do motor deve ser ligado ao GND do Arduino. Para ir e voltar, use uma ponte H (L298N, TB6612…).",
  "help.u.relay.t": "Relés e cargas maiores",
  "help.u.relay.1": "Um relé usa uma pequena corrente de bobina para comutar contatos de alta corrente e alta tensão: COM é o comum, NA (NO) é normalmente aberto (ligado ao COM enquanto a bobina está energizada) e NF (NC) normalmente fechado. O circuito dos contatos é isolado do microcontrolador e pode comutar uma lâmpada de 12 V ou aparelhos da rede elétrica.",
  "help.u.relay.2": "Módulos de relé já têm o transistor, o diodo de roda livre e um LED indicador: VCC/GND no 5V/GND, IN em qualquer pino digital. Atenção ao nível de disparo — muitos módulos são ativos em nível baixo (acionam com IN = LOW); o módulo simulado permite escolher disparo alto ou baixo nas propriedades.",
  "help.u.relay.3": "A bobina de um relé avulso costuma consumir 70 mA ou mais, então não pode ir direto a um pino: acione-a por um transistor com diodo de roda livre. A rede elétrica é perigosa — use um módulo pronto com caixa e respeite a corrente nominal dos contatos.",
  "help.u.tone.t": "Buzzers e tone()",
  "help.u.tone.1": "`tone(pin, frequência)` gera uma onda quadrada de 50 % em qualquer pino digital, `tone(pin, frequência, duração)` para sozinho, `noTone(pin)` interrompe. Só um `tone()` toca por vez; ele usa o Timer2 e desliga o PWM em D3/D11.",
  "help.u.tone.2": "Buzzers passivos e alto-falantes pequenos precisam da onda quadrada do `tone()` para soar, e a frequência define a nota; um buzzer ativo tem oscilador próprio e apita com `digitalWrite(HIGH)`, mas numa nota fixa.",
  "help.u.tone.3": "Coloque cerca de 100 Ω em série com o buzzer; um alto-falante de 8 Ω puxa corrente demais e precisa de transistor. Frequências de notas comuns: C4 262, D4 294, E4 330, F4 349, G4 392, A4 440, B4 494, C5 523 Hz.",
  "help.u.servo.t": "Servomotores",
  "help.u.servo.1": "Um servo tem três fios: sinal (laranja/amarelo), alimentação + (vermelho), GND (marrom/preto). O sinal é um pulso a cada 20 ms aproximadamente (50 Hz); larguras de pulso de normalmente 1–2 ms definem o ângulo, e a biblioteca Servo associa por padrão 544–2400 µs a 0–180°. Use `attach(pin)` e depois `write(ângulo)`.",
  "help.u.servo.2": "A biblioteca Servo usa o Timer1, então D9 e D10 perdem o PWM (o fio de sinal pode ir a qualquer pino digital). Um Uno controla até 12 servos.",
  "help.u.servo.3": "Servos puxam centenas de mA, às vezes mais de 1 A, ao partir ou travar. Um servo pequeno como o SG90 pode ser alimentado pelo pino 5V; vários servos ou modelos maiores precisam de uma fonte própria de 5–6 V com terra comum, e 100–470 µF na alimentação dos servos ajudam a evitar resets.",
  "help.u.lcd.t": "Display LCD1602",
  "help.u.lcd.1": "O LCD1602 (controlador HD44780) precisa de só 6 linhas de sinal no modo de 4 bits: RS, E, D4–D7, com RW no GND (só escrita); a forma com 7 argumentos controla também o RW por um pino. `LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`, depois `lcd.begin(16, 2)`, `lcd.setCursor(coluna, linha)`, `lcd.print()`, `lcd.clear()`.",
  "help.u.lcd.2": "Alimentação: VSS no GND, VDD no 5V; V0 ajusta o contraste, em geral pelo cursor de um potenciômetro de 10 kΩ (extremidades no 5V/GND) — mal ajustado, aparecem blocos pretos ou nada. A/K são o LED de luz de fundo: A no 5V por um resistor (muitos módulos já têm) ou num pino para ligar e desligar, K no GND.",
  "help.u.lcd.3": "Faltam pinos? Um adaptador I²C (PCF8574, só A4/A5) ajuda no hardware real, mas este simulador não tem I²C, então use a ligação paralela. Linhas e colunas contam a partir de 0: a segunda linha é `setCursor(0, 1)`.",
  "help.u.serial.t": "Depuração pela serial",
  "help.u.serial.1": "`Serial.begin(9600)` abre a porta (a taxa deve ser a mesma do monitor serial), `Serial.print()` / `println()` enviam texto e números. É a forma mais comum de depurar: imprimir variáveis, qual caminho o programa seguiu, leituras de sensores.",
  "help.u.serial.2": "`Serial.available()` retorna o número de bytes recebidos, `Serial.read()` lê um byte e `Serial.readStringUntil('\\n')` lê uma linha. No simulador, digite no campo de entrada do monitor serial para enviar texto.",
  "help.u.serial.3": "No Uno, a serial usa D0/D1 — não ligue outros circuitos nesses pinos enquanto ela estiver em uso. Imprimir com muita frequência deixa o programa lento (9600 baud ≈ 1 caractere por milissegundo), então espace as mensagens com `millis()`. O ATtiny85 não tem UART por hardware; o `Serial` dele no simulador serve só para depuração.",
  "help.u.millis.t": "Temporização sem bloqueio com millis()",
  "help.u.millis.1": "Durante `delay()` o programa não faz mais nada (não lê botões, não atualiza outros LEDs). `millis()` retorna os milissegundos desde que a placa ligou; testar “agora − último ≥ intervalo” permite cuidar de várias coisas ao mesmo tempo.",
  "help.u.millis.2": "Use `unsigned long` nas variáveis de tempo. Comparar por subtração, `millis() - last >= INTERVAL`, continua correto quando o contador estoura após cerca de 49,7 dias; não escreva `millis() >= last + INTERVAL`.",
  "help.u.millis.3": "Uma variável de tempo por tarefa forma uma máquina de estados simples: o exemplo “multitarefa com millis()” pisca dois LEDs em ritmos diferentes enquanto imprime o tempo ligado, e o botão com debounce usa a mesma ideia. Use `micros()` para resolução de microssegundos.",
  "help.ex.examples": "Exemplos relacionados",
  "help.ex.intro": "“Carregar na área de trabalho” substitui o circuito atual e inicia a simulação; “Inserir no editor” coloca o código no editor de programa do chip atual (ainda não enviado, dá para editar antes); “Copiar código” copia para a área de transferência.",
  "help.ex.wiring": "Ligações",
  "help.ex.usage": "Uso relacionado",
  "help.ex.code": "Código-fonte",
  "help.ex.load": "Carregar na área de trabalho",
  "help.ex.insert": "Inserir no editor",
  "help.ex.copy": "Copiar código",
  "help.ex.other": "Ver os exemplos de {board} ({n}) →",
  "help.toast.inserted": "Código inserido no editor de {chip} — clique em “Compilar e enviar” para aplicar",
  "help.toast.mismatch": "Inserido, mas este código foi escrito para {board}; os pinos podem não corresponder",
  "help.toast.copied": "Código copiado para a área de transferência",
  "help.toast.copy_failed": "Falha ao copiar — selecione o código na caixa e copie manualmente",
  "help.toast.no_chip": "Não há microcontrolador na área de trabalho: coloque primeiro uma placa ou um chip, ou use “Carregar na área de trabalho”",
  "help.w.anode": "ânodo (+, perna longa)",
  "help.w.cathode": "cátodo (−)",
  "help.w.onboard_led": "LED da placa (L)",
  "help.w.red_led": "LED vermelho",
  "help.w.yellow_led": "LED amarelo",
  "help.w.green_led": "LED verde",
  "help.w.white_led": "LED branco",
  "help.w.all_cathodes": "todos os cátodos dos LEDs",
  "help.w.internal_pullup": "pull-up interno",
  "help.w.pot_ends": "extremidades",
  "help.w.wiper": "cursor",
  "help.w.gate": "gate G",
  "help.w.drain": "dreno D",
  "help.w.source": "fonte S",
  "help.w.flyback": "em antiparalelo com o motor (cátodo no +), como diodo de roda livre",
  "help.w.common_gnd": "terra comum",
  "help.w.servo_sig": "fio de sinal",
  "help.w.servo_vcc": "fio de alimentação",
  "help.w.servo_gnd": "fio de terra",
  "help.w.backlight": "luz de fundo",
  "help.w.contrast": "contraste",
  "help.w.pin_n4": "pino 4",
  "help.w.pin_n5": "pino 5",
  "help.w.pin_n6": "pino 6",
  "help.w.pin_n8": "pino 8",
  "ex.arddebounce": "MCU: botão com debounce alterna um LED (millis)",
  "ex.ardnight": "MCU: luz noturna com LDR (LDR → PWM)",
  "ex.ardmulti": "MCU: multitarefa com millis() (sem delay)",
  "ex.ardmotor": "MCU: controle de velocidade de motor CC com MOSFET (PWM)",
  "ex.ardrelay": "MCU: módulo relé liga uma lâmpada de 12 V por temporizador",
  "ex.ardtone": "MCU: melodia em buzzer passivo (tone)",
  "ex.tinyfade": "MCU: fade PWM com ATtiny85",
  "exd.arddebounce": "Cada toque no botão em D2 alterna o LED em D8: a entrada precisa ficar estável por 30 ms para a mudança contar, então a trepidação não alterna duas vezes; o número de toques aparece no monitor serial.",
  "exd.ardnight": "5V → 10 kΩ → A0 → fotorresistor → GND formam um divisor: quanto mais escuro, maior a leitura e mais brilha o LED branco no pino PWM D9. Mude a propriedade “Intensidade da luz” do fotorresistor para testar.",
  "exd.ardmulti": "Nenhum delay(): o LED em D8 alterna a cada 250 ms, o de D7 a cada 700 ms, e a cada segundo o tempo ligado é impresso — três tarefas ao mesmo tempo.",
  "exd.ardmotor": "Potenciômetro → A0 → PWM em D9 → MOSFET de nível lógico IRLZ44N → motor CC. O motor tem sua própria bateria de 6 V com terra comum ao Arduino, e um diodo 1N4007 absorve o pico no desligamento.",
  "exd.ardrelay": "D7 aciona um módulo relé (disparo em nível alto) que acende uma lâmpada de 12 V por 2 s e apaga por 2 s. O circuito da lâmpada é isolado do Arduino; o pino fornece só alguns mA.",
  "exd.ardtone": "D8 aciona um buzzer passivo por 100 Ω e toca uma melodia de 16 passos com tone() (0 = pausa); a frequência de cada nota aparece no monitor serial.",
  "exd.tinyfade": "O ATtiny85 gera PWM em PB0 (pino 5) e PB1 (pino 6): o LED amarelo acende aos poucos enquanto o verde apaga, sem parar.",
  "wc.title": "Cor do fio",
  "wc.n_wires": "{n} fios selecionados",
  "wc.red": "Vermelho",
  "wc.black": "Preto",
  "wc.blue": "Azul",
  "wc.green": "Verde",
  "wc.yellow": "Amarelo",
  "wc.orange": "Laranja",
  "wc.white": "Branco",
  "wc.purple": "Roxo",
  "wc.gray": "Cinza",
  "wc.brown": "Marrom",
  "wc.custom": "Cor personalizada…",
  "wc.hint": "Fios novos usam a última cor escolhida; fios de cores diferentes nunca são unidos automaticamente."
});
