// v10.1 pinout / usage reference panel, new examples and wire colours — 简体中文 (source text)
I18N.add('zh-CN', {
  "help.btn": "引脚说明",
  "help.title": "引脚说明与用法",
  "help.intro.arduino": "Arduino Uno R3（ATmega328P，16 MHz，5 V 逻辑）：14 个数字引脚 D0–D13（其中 6 个带 ~ 可输出 PWM），6 个模拟输入 A0–A5（10 位 ADC，也可当数字脚 D14–D19）。下面依次是引脚图、每个引脚的功能、电气极限、仿真支持情况、常规用法，最后是可一键载入的示例。",
  "help.intro.attiny85": "ATtiny85（8 脚 DIP，AVR 8 位）：5 个通用 IO PB0–PB4，另有 PB5（默认是 RESET）。没有硬件串口；PWM 在 PB0/PB1/PB4，ADC 在 PB2/PB3/PB4（PB5 也可）。Flash 8 KB、SRAM 512 B、EEPROM 512 B；出厂默认内部 8 MHz RC 振荡器 8 分频 = 1 MHz（CKDIV8 熔丝）。",
  "help.nav.pinout": "引脚图",
  "help.nav.table": "引脚表",
  "help.nav.limits": "电气极限",
  "help.nav.sim": "仿真支持",
  "help.nav.usage": "常规用法",
  "help.nav.examples": "示例",
  "help.cat.dig": "数字 IO",
  "help.cat.pwm": "PWM 输出",
  "help.cat.ana": "模拟输入",
  "help.cat.com": "通信 (UART/SPI/I²C)",
  "help.cat.int": "外部中断",
  "help.cat.pwr": "电源",
  "help.cat.gnd": "地",
  "help.cat.spc": "特殊功能",
  "help.leg.nosim": "虚线框 = 仿真器未模拟",
  "help.th.pin": "引脚",
  "help.th.func": "功能与说明",
  "help.th.sim": "仿真",
  "help.sim.yes": "支持",
  "help.sim.part": "部分支持",
  "help.sim.no": "不支持",
  "help.sim.absent": "元件上无此脚",
  "help.tag.dio": "数字输入/输出",
  "help.tag.pwm490": "PWM 约 490 Hz",
  "help.tag.pwm980": "PWM 约 980 Hz",
  "help.tag.tpwm": "PWM 输出 (analogWrite)",
  "help.tag.adc": "模拟输入（10 位 ADC）",
  "help.tag.rx": "串口接收 RX",
  "help.tag.tx": "串口发送 TX",
  "help.tag.int0": "外部中断 INT0",
  "help.tag.int1": "外部中断 INT1",
  "help.tag.ss": "SPI 片选 SS",
  "help.tag.mosi": "SPI 主出从入 MOSI",
  "help.tag.miso": "SPI 主入从出 MISO",
  "help.tag.sck": "SPI 时钟 SCK",
  "help.tag.sda": "I²C 数据 SDA",
  "help.tag.scl": "I²C 时钟 SCL",
  "help.tag.led": "板载 LED「L」",
  "help.tag.aref": "模拟参考电压 AREF",
  "help.tag.ioref": "IO 电平参考 IOREF",
  "help.tag.reset": "复位（低电平有效）",
  "help.tag.treset": "复位 RESET（低电平有效）",
  "help.tag.v5": "5 V 电源",
  "help.tag.v33": "3.3 V 电源输出",
  "help.tag.vin": "外部电源输入 VIN",
  "help.tag.gnd": "地 GND",
  "help.tag.vcc": "电源 VCC",
  "help.tag.usi_di": "USI 数据输入 DI / I²C SDA",
  "help.tag.usi_do": "USI 数据输出 DO",
  "help.tag.usi_sck": "USI 时钟 USCK / I²C SCL",
  "help.tag.xtal": "外部晶振引脚",
  "help.tag.ain": "模拟比较器输入",
  "help.tag.taref": "外部参考电压 AREF",
  "help.tag.tled": "Digispark 等板的板载 LED",
  "help.tag.icsp": "ICSP 在线编程接口",
  "help.note.d0d1": "D0/D1 与板上的 USB 转串口芯片相连：上传程序和 `Serial` 通信都要用它们，外接电路可能导致上传失败。仿真中 D0/D1 可当普通 IO，`Serial` 直接连到串口监视器。",
  "help.note.tone": "`tone()` 占用 Timer2，发声期间 D3 和 D11 的 PWM 失效。",
  "help.note.servo": "Servo 库占用 Timer1，使用后 D9 和 D10 都不能再 `analogWrite()`（与舵机接在哪个脚无关）。",
  "help.note.d13": "板载 LED「L」由 D13（`LED_BUILTIN`）驱动，R3 上经运放缓冲。D13 同时是 SPI 的 SCK，使用 SPI 时 LED 会闪。",
  "help.note.a4a5": "A4/A5 同时是 I²C 的 SDA/SCL（R3 在 AREF 旁另有一组 SDA/SCL 排针，与 A4/A5 内部相连）。使用 I²C 时它们不能再作模拟输入。",
  "help.note.v5": "来自板载 5 V 稳压器（VIN/DC 供电时）或 USB。可给传感器和小模块供电；USB 供电时全板受 500 mA 自恢复保险丝限制。也能从这里输入稳压的 5 V，但会绕过稳压器和保护电路。",
  "help.note.v33": "板载 3.3 V 稳压输出，最大 50 mA。",
  "help.note.vin": "外部电源输入（DC 插座经二极管接到这里），推荐 7–12 V，极限 6–20 V。低于 7 V 时 5 V 可能不稳，高于 12 V 稳压器容易过热。",
  "help.note.gnd": "所有 GND 相互连通。外部电源（电池、电机电源）的负极必须与 Arduino 的 GND 相连（共地），信号才有共同的参考。",
  "help.note.reset": "拉低即复位，板上的复位按钮也接在这里。仿真元件没有此脚，可用程序编辑器里的「复位」按钮代替。",
  "help.note.aref": "外部模拟参考电压输入（0–5 V），配合 `analogReference(EXTERNAL)` 使用；接外部电压前必须先设为 EXTERNAL，否则可能损坏芯片。仿真元件没有此脚，EXTERNAL 按 VCC (5 V) 处理。",
  "help.note.ioref": "告诉扩展板本板的 IO 电平（Uno 上接 5 V）。仿真元件没有此脚。",
  "help.note.sdascl": "R3 新增的 I²C 排针，与 A4/A5 电气上相同。仿真器不支持 I²C（Wire 库）。",
  "help.note.icsp": "6 针 ISP 在线编程接口，用于烧写引导程序或用编程器直接下载程序。仿真中不需要。",
  "help.note.pb5": "默认是 RESET（低电平复位，内部上拉），不能当普通 IO；仿真中把它拉到 0.3·VCC 以下会让芯片保持复位。烧写 RSTDISBL 熔丝后才成为（驱动能力较弱的）IO，但之后不能再用 ISP 编程，需要高压编程器才能恢复。仿真中可在属性里勾选「PB5 作普通 IO」。",
  "help.note.pb34": "PB3/PB4 也是外部晶振引脚：使用外部晶振时不能当 IO。默认使用内部 RC 振荡器，所以可以自由使用。",
  "help.note.pb0": "物理第 5 脚：PWM (OC0A)、USI 的 DI / I²C SDA、ISP 编程的 MOSI，也可作外部 AREF（此时不能再作 IO）。",
  "help.note.pb1": "物理第 6 脚：PWM (OC0B / OC1A)、USI 的 DO、ISP 编程的 MISO。Digispark 等开发板的板载 LED 接在这里。",
  "help.note.pb2": "物理第 7 脚：唯一的外部中断 INT0、模拟输入 A1 (ADC1)、USI 时钟 USCK / I²C SCL、ISP 编程的 SCK。",
  "help.note.vcc": "供电 2.7–5.5 V（ATtiny85V 为 1.8–5.5 V），时钟越高需要的电压越高（20 MHz 需 4.5 V 以上）。VCC 与 GND 之间就近接 100 nF 去耦电容。",
  "help.lim.arduino.1": "每个 IO 引脚：推荐 ≤ 20 mA，绝对最大 40 mA，超过可能永久损坏端口。",
  "help.lim.arduino.2": "所有引脚电流之和（VCC/GND 总电流）不超过 200 mA。",
  "help.lim.arduino.3": "引脚电压不得超出 −0.5 V … VCC + 0.5 V；输入低电平 < 0.3·VCC（1.5 V），高电平 > 0.6·VCC（3 V）。",
  "help.lim.arduino.4": "内部上拉电阻 20–50 kΩ（`INPUT_PULLUP`）。",
  "help.lim.arduino.5": "模拟输入 0–5 V（默认参考 = VCC），10 位 → 0–1023，每档约 4.9 mV；信号源阻抗建议 ≤ 10 kΩ。",
  "help.lim.arduino.6": "VIN / DC 插座：推荐 7–12 V，极限 6–20 V；USB 供电为 5 V，带 500 mA 自恢复保险丝。",
  "help.lim.arduino.7": "3.3V 引脚最大 50 mA；5V 引脚能给出多少电流取决于电源（USB 时全板 ≤ 500 mA，VIN 供电时受稳压器发热限制）。",
  "help.lim.arduino.8": "ATmega328P：16 MHz，Flash 32 KB（引导程序占 0.5 KB），SRAM 2 KB，EEPROM 1 KB。",
  "help.lim.attiny85.1": "每个 IO 引脚：建议 ≤ 20 mA，绝对最大 40 mA；VCC/GND 总电流 ≤ 200 mA。",
  "help.lim.attiny85.2": "工作电压 2.7–5.5 V（ATtiny85V：1.8–5.5 V）；10 MHz 以下 2.7 V 即可，20 MHz 需要 4.5–5.5 V。",
  "help.lim.attiny85.3": "引脚电压 −0.5 V … VCC + 0.5 V；内部上拉 20–50 kΩ。",
  "help.lim.attiny85.4": "ADC：10 位，4 路单端输入 ADC0–ADC3 = PB5 / PB2 / PB4 / PB3；参考电压可选 VCC、内部 1.1 V、内部 2.56 V 或 PB0 上的外部 AREF。",
  "help.lim.attiny85.5": "存储：Flash 8 KB、SRAM 512 B、EEPROM 512 B。",
  "help.lim.attiny85.6": "时钟：出厂为内部 8 MHz RC ÷ 8 = 1 MHz（CKDIV8 熔丝）；可改为内部 8 MHz、PLL 16 MHz，或外部晶振（占用 PB3/PB4）。",
  "help.sim.ok": "仿真支持：`pinMode` / `digitalWrite` / `digitalRead`（含 `INPUT_PULLUP`）、`analogRead`（10 位）、`analogWrite`（PWM 频率与真实芯片一致）、`millis` / `micros` / `delay`、`tone` / `noTone`、`pulseIn`、`shiftOut`、Servo、LiquidCrystal、LiquidCrystal_I2C、DHT、OneWire + DallasTemperature、`Serial`（串口监视器）等。引脚的输出电阻、上拉电阻和电流都参与电路求解，单脚超过 40 mA 会给出警告。",
  "help.sim.no.1": "外部中断 `attachInterrupt()`：编译时提示不支持，请改用轮询或 `millis()`。",
  "help.sim.no.3": "库对定时器的副作用（tone 使 D3/D11 的 PWM 失效、Servo 使 D9/D10 的 PWM 失效）只在说明中提示，仿真中不会出现。",
  "help.sim.no.4": "Uno 元件没有 RESET、AREF、IOREF、单独的 SDA/SCL 排针和 ICSP 接口；`analogReference(EXTERNAL)` 按 VCC 处理，`INTERNAL` = 1.1 V。",
  "help.sim.no.5": "ATtiny85 没有硬件串口：仿真中的 `Serial` 是虚拟的，只用于把调试信息输出到串口监视器。",
  "help.sim.no.6": "引脚过流不会「烧坏」芯片：仿真只给出警告，请对照电气极限自行检查。",
  "help.sim.no.7": "EEPROM、睡眠模式、看门狗、熔丝设置以及直接操作寄存器（如 `PORTB`、`DDRB`）不支持。",
  "help.sim.no.8": "不模拟指令执行时间：代码视为瞬间完成，只有 `delay()`、`millis()` 等推动时间；死循环超过运算上限会报错。",
  "help.usage.intro": "每一节给出接线要点和一段可以直接复制的代码，并链接到相关示例。",
  "help.u.power.t": "供电方式",
  "help.u.power.1": "Uno 有三种供电方式：① USB 5 V（最简单，全板 ≤ 500 mA）；② DC 插座或 VIN 接 7–12 V，经板载稳压器得到 5 V；③ 直接向 5V 引脚输入稳压的 5 V（绕过稳压器和保护，接错会损坏板子）。仿真中可在属性里选择 USB 或 VIN 供电。",
  "help.u.power.2": "5V 和 3.3V 引脚可以给传感器、小模块供电，但不要用它们驱动电机、多个舵机或大功率 LED：这些负载会拉低电压，使单片机复位。大电流负载请用独立电源，并把电源负极与 Arduino 的 GND 相连（共地）。",
  "help.u.power.3": "ATtiny85 只是一颗芯片，没有稳压器：VCC 要直接接 2.7–5.5 V，例如 3 节 AA 电池（4.5 V）、USB 5 V 或单节锂电池（3.0–4.2 V）。电压太低芯片不会启动（仿真显示 OFF），超过 5.5 V 可能损坏。",
  "help.u.power.4": "每颗芯片的 VCC 与 GND 之间就近放一只 100 nF 去耦电容。电机等感性负载最好使用与单片机分开的电源，至少要加大电容滤波。",
  "help.u.dout.t": "数字输出与 LED 限流电阻",
  "help.u.dout.1": "先 `pinMode(pin, OUTPUT)`，再用 `digitalWrite(pin, HIGH)` / `LOW` 输出约 5 V / 0 V。输出脚既能输出电流也能吸收电流，每脚推荐不超过 20 mA。",
  "help.u.dout.2": "LED 必须串联限流电阻：R = (Vcc − Vf) / I。例如 5 V、红色 LED Vf ≈ 2 V、取 10 mA：R = (5 − 2) / 0.01 = 300 Ω，选常用值 330 Ω；用 220 Ω 约 14 mA 也可以。蓝、白色 LED 的 Vf ≈ 3 V，同样电流约需 200 Ω。",
  "help.u.dout.3": "LED 长脚（阳极 +）经电阻接引脚，短脚（阴极 −）接 GND，此时 HIGH = 亮；也可以把 LED 接到 5V，由引脚吸收电流，此时 LOW = 亮。一个引脚要驱动多颗 LED 或超过 20 mA 的负载时，请用三极管或 MOSFET。",
  "help.u.din.t": "按键输入：上拉、下拉与消抖",
  "help.u.din.1": "`INPUT_PULLUP` 打开内部 20–50 kΩ 上拉电阻：按键一端接引脚、另一端接 GND，不需要外接电阻。没按时读到 HIGH，按下读到 LOW（逻辑相反）。这是最简单的接法。",
  "help.u.din.2": "下拉接法：按键接在 5V 与引脚之间，引脚再经 10 kΩ 接 GND，`pinMode(pin, INPUT)`，按下读到 HIGH。注意 `INPUT` 模式下引脚悬空时读数会随机跳动，必须有上拉或下拉电阻。",
  "help.u.din.3": "机械按键按下和松开时会抖动几毫秒，一次按压可能被读成好几次。消抖方法：读数变化后等 20–50 ms 仍不变才确认（用 `millis()` 计时，不要用长时间的 `delay()`），或在硬件上加 RC 滤波。示例「按键消抖」演示了软件消抖。",
  "help.u.ain.t": "模拟输入：电位器、分压、光敏/热敏电阻",
  "help.u.ain.1": "`analogRead(A0)` 返回 0–1023，对应 0 V 到参考电压（默认 VCC = 5 V）：电压 = 读数 × 5.0 / 1024。一次转换约 100 µs。`analogReference(INTERNAL)` 改用内部 1.1 V 参考，适合测量小电压。",
  "help.u.ain.2": "电位器：两端分别接 5V 和 GND，中间抽头接 A0，旋转时读数在 0–1023 之间变化。分压电阻：Vout = Vin × R2 / (R1 + R2)，可以把高于 5 V 的电压（如 12 V 电池）降到 0–5 V 再测，但要保证输入不超过 VCC。",
  "help.u.ain.3": "光敏电阻 (LDR) 和热敏电阻 (NTC) 要与一个固定电阻串联成分压器，中点接模拟口；固定电阻取传感器在中间工作点的阻值，常用 10 kΩ。LDR 接在下方时越暗电压越高；NTC 温度越高阻值越小。可以用 `map()` 把读数换算成需要的范围。",
  "help.u.ain.4": "ADC 要求信号源阻抗 ≤ 10 kΩ，分压电阻太大时读数不稳，可在模拟口与 GND 之间加 100 nF 电容。A0–A5 也能当普通数字脚使用（D14–D19）。ATtiny85 的模拟口是 A1 (PB2)、A2 (PB4)、A3 (PB3)；A0 (PB5) 是复位脚，一般不用。",
  "help.u.pwm.t": "PWM：调光与调速",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` 在带 ~ 的引脚输出 PWM 方波：占空比 = 值 / 255，平均电压 ≈ 5 V × 值 / 255。Uno 的 D5、D6 约 980 Hz，D3、D9、D10、D11 约 490 Hz；ATtiny85 可用 PB0、PB1、PB4。",
  "help.u.pwm.2": "PWM 适合调 LED 亮度（人眼看到的是平均亮度）和电机转速；它不是真正的模拟电压，需要平滑电压时请加 RC 低通滤波。在不带 ~ 的引脚上调用 `analogWrite()` 时，值 < 128 输出 LOW，否则输出 HIGH。",
  "help.u.pwm.3": "值为 0 或 255 时输出恒定的 LOW / HIGH。人眼对亮度的感觉是非线性的，呼吸灯用平方曲线会更自然。可以用示波器观察 PWM 波形（示例「电位器调光」）。",
  "help.u.motor.t": "电机：三极管 / MOSFET 驱动与续流二极管",
  "help.u.motor.1": "引脚只能提供约 20 mA，不能直接驱动电机。用 NPN 三极管或 N 沟道 MOSFET 做低边开关：负载接在电源 + 与漏极 (D) 之间，源极 (S) 接 GND，栅极 (G) 经 100–220 Ω 接 PWM 引脚，再用 10 kΩ 下拉到 GND，防止上电或复位时引脚悬空导致误启动。",
  "help.u.motor.2": "请选「逻辑电平」MOSFET（如 IRLZ44N，5 V 栅压即可充分导通）；IRF540 等普通 MOSFET 的导通电阻是按 10 V 栅压标定的，5 V 下导通不充分会发热。用三极管时基极串联约 1 kΩ 电阻。",
  "help.u.motor.3": "电机、继电器线圈、电磁阀都是感性负载，断开瞬间会产生很高的反向电压，必须在负载两端反向并联续流二极管（如 1N4007，阴极接电源 +）。电机电源的负极必须与 Arduino GND 相连。需要正反转时使用 H 桥驱动（如 L298N、TB6612）。",
  "help.u.relay.t": "继电器与大功率负载",
  "help.u.relay.1": "继电器用小电流的线圈控制大电流、高电压的触点：COM 是公共端，NO 常开（线圈通电时与 COM 接通），NC 常闭。触点电路与单片机电气隔离，可以开关 12 V 灯泡或市电电器。",
  "help.u.relay.2": "继电器模块内置三极管、续流二极管和指示灯，VCC/GND 接 5V/GND，IN 接任意数字脚即可。注意触发方式：很多模块是低电平触发（IN = LOW 时吸合）；仿真中的模块可在属性里选择高/低电平触发。",
  "help.u.relay.3": "裸继电器的线圈电流通常在 70 mA 以上，不能直接接引脚，要用三极管驱动并加续流二极管。操作 220 V 市电非常危险，请使用带外壳的成品模块，并注意触点的额定电流。",
  "help.u.tone.t": "蜂鸣器与 tone()",
  "help.u.tone.1": "`tone(pin, 频率)` 在任意数字脚输出 50% 占空比的方波，`tone(pin, 频率, 时长)` 到时自动停止，`noTone(pin)` 停止发声。同一时间只能有一个 `tone()`；它占用 Timer2，会使 D3/D11 的 PWM 失效。",
  "help.u.tone.2": "无源蜂鸣器和小喇叭需要 `tone()` 产生的方波才能发声，音调由频率决定；有源蜂鸣器内部带振荡器，只要 `digitalWrite(HIGH)` 就响，但音调固定。",
  "help.u.tone.3": "蜂鸣器串联约 100 Ω 电阻限流；8 Ω 喇叭电流太大，要经三极管驱动。常用音符频率：C4 262、D4 294、E4 330、F4 349、G4 392、A4 440、B4 494、C5 523 Hz。",
  "help.u.servo.t": "舵机",
  "help.u.servo.1": "舵机有三根线：信号（橙/黄）、电源 +（红）、GND（棕/黑）。信号是周期约 20 ms（50 Hz）的脉冲，脉宽通常 1–2 ms 对应转角，Servo 库默认把 544–2400 µs 映射到 0–180°。用法：`attach(pin)` 之后 `write(角度)`。",
  "help.u.servo.2": "Servo 库占用 Timer1，使用后 D9、D10 不能输出 PWM（舵机信号线可接任意数字脚）。Uno 最多可接 12 个舵机。",
  "help.u.servo.3": "舵机启动和堵转时电流可达几百 mA 甚至 1 A 以上。SG90 这类小舵机接一个可由 5V 引脚供电；多个或大舵机请用独立的 5–6 V 电源并共地，在舵机电源端并联 100–470 µF 电容可以减少复位。",
  "help.u.lcd.t": "LCD1602 液晶屏",
  "help.u.lcd.1": "LCD1602（HD44780 控制器）在 4 位模式下只需 6 根信号线：RS、E、D4–D7，RW 接 GND（只写）；也可以用 7 个参数的写法把 RW 接到引脚。`LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`，然后 `lcd.begin(16, 2)`、`lcd.setCursor(列, 行)`、`lcd.print()`、`lcd.clear()`。",
  "help.u.serial.t": "串口调试",
  "help.u.serial.1": "`Serial.begin(9600)` 打开串口（波特率要与串口监视器一致），`Serial.print()` / `println()` 输出文字和数值。这是调试程序最常用的方法：打印变量、程序走到了哪里、传感器读数。",
  "help.u.serial.2": "`Serial.available()` 返回已收到的字节数，`Serial.read()` 读一个字节，`Serial.readStringUntil('\\n')` 读一行。仿真中在串口监视器的输入框里发送文字。",
  "help.u.serial.3": "Uno 的串口占用 D0/D1，使用串口时不要在这两个脚上接其他电路。打印太频繁会拖慢程序（9600 波特约每毫秒 1 个字符），可以用 `millis()` 控制打印间隔。ATtiny85 没有硬件串口，仿真中的 `Serial` 仅用于调试。",
  "help.u.millis.t": "millis() 非阻塞定时",
  "help.u.millis.1": "`delay()` 期间程序什么也做不了（不能读按键，也不能刷新别的 LED）。`millis()` 返回上电以来的毫秒数，用「当前时间 − 上次时间 ≥ 间隔」判断是否到时，就能同时处理多件事。",
  "help.u.millis.2": "时间变量要用 `unsigned long`。用减法比较 `millis() - last >= INTERVAL`，约 49.7 天后计数回绕时也正确；不要写成 `millis() >= last + INTERVAL`。",
  "help.u.millis.3": "每个任务一个时间变量，就组成了简单的状态机：示例「millis() 多任务」让两颗 LED 以不同节奏闪烁并同时打印运行时间，「按键消抖」也用同样的方法。需要微秒精度时用 `micros()`。",
  "help.ex.examples": "相关示例",
  "help.ex.intro": "「载入到画布」会替换当前电路并开始仿真；「插入编辑器」把代码放进当前芯片的程序编辑器（尚未上传，可修改后再上传）；「复制代码」复制到剪贴板。",
  "help.ex.wiring": "接线",
  "help.ex.usage": "相关用法",
  "help.ex.code": "代码",
  "help.ex.load": "载入到画布",
  "help.ex.insert": "插入编辑器",
  "help.ex.copy": "复制代码",
  "help.ex.other": "查看 {board} 的示例（{n} 个）→",
  "help.toast.inserted": "代码已插入 {chip} 的编辑器，点「编译并上传」生效",
  "help.toast.mismatch": "已插入，但这段代码是为 {board} 编写的，引脚可能不对应",
  "help.toast.copied": "代码已复制到剪贴板",
  "help.toast.copy_failed": "复制失败，请在代码框中手动选择后复制",
  "help.toast.no_chip": "画布上没有单片机：请先放一块开发板或芯片，或使用「载入到画布」",
  "help.w.anode": "阳极（+，长脚）",
  "help.w.cathode": "阴极（−）",
  "help.w.onboard_led": "板载 LED（L）",
  "help.w.red_led": "红色 LED",
  "help.w.yellow_led": "黄色 LED",
  "help.w.green_led": "绿色 LED",
  "help.w.white_led": "白色 LED",
  "help.w.all_cathodes": "所有 LED 的阴极",
  "help.w.internal_pullup": "使用内部上拉",
  "help.w.pot_ends": "两端",
  "help.w.wiper": "中间抽头",
  "help.w.gate": "栅极 G",
  "help.w.drain": "漏极 D",
  "help.w.source": "源极 S",
  "help.w.flyback": "与电机反向并联（阴极接电源 +）作续流",
  "help.w.common_gnd": "共地",
  "help.w.servo_sig": "信号线",
  "help.w.servo_vcc": "电源线",
  "help.w.servo_gnd": "地线",
  "help.w.backlight": "背光",
  "help.w.contrast": "对比度",
  "help.w.pin_n4": "第 4 脚",
  "help.w.pin_n5": "第 5 脚",
  "help.w.pin_n6": "第 6 脚",
  "help.w.pin_n8": "第 8 脚",
  "ex.arddebounce": "单片机：按键消抖 切换 LED (millis)",
  "ex.ardnight": "单片机：光敏电阻小夜灯 (LDR → PWM)",
  "ex.ardmulti": "单片机：millis() 多任务 (不用 delay)",
  "ex.ardmotor": "单片机：MOSFET 驱动直流电机调速 (PWM)",
  "ex.ardrelay": "单片机：继电器模块 定时开关 12V 灯",
  "ex.ardtone": "单片机：无源蜂鸣器播放旋律 (tone)",
  "ex.tinyfade": "单片机：ATtiny85 PWM 呼吸灯",
  "exd.arddebounce": "每按一次 D2 上的按键就切换 D8 上 LED 的亮灭：输入保持 30 ms 不变才确认，避免抖动造成多次切换；串口打印按键次数。",
  "exd.ardnight": "5V → 10 kΩ → A0 → 光敏电阻 → GND 组成分压器：越暗读数越高，D9 的 PWM 让白色 LED 越亮。在属性中调节光敏电阻的「光照强度」试试。",
  "exd.ardmulti": "完全不用 delay()：D8 的 LED 每 250 ms 翻转，D7 的 LED 每 700 ms 翻转，每秒打印一次运行时间，三件事同时进行。",
  "exd.ardmotor": "电位器 → A0 → D9 的 PWM → 逻辑电平 MOSFET IRLZ44N → 直流电机。电机用独立的 6 V 电池并与 Arduino 共地，1N4007 续流二极管吸收关断时的反向电压。",
  "exd.ardrelay": "D7 控制继电器模块（高电平触发），让 12 V 灯泡亮 2 秒、灭 2 秒。灯泡回路与 Arduino 电气隔离，引脚只需提供几 mA。",
  "exd.ardtone": "D8 经 100 Ω 驱动无源蜂鸣器，用 tone() 播放一段 16 拍的旋律（0 表示休止），串口打印每个音符的频率。",
  "exd.tinyfade": "ATtiny85 在 PB0（第 5 脚）和 PB1（第 6 脚）输出 PWM：黄色 LED 渐亮时绿色 LED 渐暗，循环往复。",
  "wc.title": "导线颜色",
  "wc.n_wires": "已选 {n} 根导线",
  "wc.red": "红色",
  "wc.black": "黑色",
  "wc.blue": "蓝色",
  "wc.green": "绿色",
  "wc.yellow": "黄色",
  "wc.orange": "橙色",
  "wc.white": "白色",
  "wc.purple": "紫色",
  "wc.gray": "灰色",
  "wc.brown": "棕色",
  "wc.custom": "自定义颜色…",
  "wc.hint": "新画的导线使用最近选择的颜色；颜色不同的导线不会被自动合并。"
});
