// v10.1 pinout / usage reference panel, new examples and wire colours — 繁體中文
I18N.add('zh-TW', {
  "help.btn": "腳位說明",
  "help.title": "腳位說明與用法",
  "help.intro.arduino": "Arduino Uno R3（ATmega328P，16 MHz，5 V 邏輯）：14 個數位腳位 D0–D13（其中 6 個帶 ~ 可輸出 PWM），6 個類比輸入 A0–A5（10 位 ADC，也可當數位腳 D14–D19）。下面依次是腳位圖、每個腳位的功能、電氣極限、模擬支援情況、常規用法，最後是可一鍵載入的範例。",
  "help.intro.attiny85": "ATtiny85（8 腳 DIP，AVR 8 位）：5 個通用 IO PB0–PB4，另有 PB5（預設是 RESET）。沒有硬體串列埠；PWM 在 PB0/PB1/PB4，ADC 在 PB2/PB3/PB4（PB5 也可）。Flash 8 KB、SRAM 512 B、EEPROM 512 B；出廠預設內部 8 MHz RC 振盪器 8 分頻 = 1 MHz（CKDIV8 熔絲）。",
  "help.nav.pinout": "腳位圖",
  "help.nav.table": "腳位表",
  "help.nav.limits": "電氣極限",
  "help.nav.sim": "模擬支援",
  "help.nav.usage": "常規用法",
  "help.nav.examples": "範例",
  "help.cat.dig": "數位 IO",
  "help.cat.pwm": "PWM 輸出",
  "help.cat.ana": "類比輸入",
  "help.cat.com": "通訊 (UART/SPI/I²C)",
  "help.cat.int": "外部中斷",
  "help.cat.pwr": "電源",
  "help.cat.gnd": "地",
  "help.cat.spc": "特殊功能",
  "help.leg.nosim": "虛線框 = 模擬器未模擬",
  "help.th.pin": "腳位",
  "help.th.func": "功能與說明",
  "help.th.sim": "模擬",
  "help.sim.yes": "支援",
  "help.sim.part": "部分支援",
  "help.sim.no": "不支援",
  "help.sim.absent": "元件上無此腳",
  "help.tag.dio": "數位輸入/輸出",
  "help.tag.pwm490": "PWM 約 490 Hz",
  "help.tag.pwm980": "PWM 約 980 Hz",
  "help.tag.tpwm": "PWM 輸出 (analogWrite)",
  "help.tag.adc": "類比輸入（10 位 ADC）",
  "help.tag.rx": "串列埠接收 RX",
  "help.tag.tx": "串列埠傳送 TX",
  "help.tag.int0": "外部中斷 INT0",
  "help.tag.int1": "外部中斷 INT1",
  "help.tag.ss": "SPI 晶片選擇 SS",
  "help.tag.mosi": "SPI 主出從入 MOSI",
  "help.tag.miso": "SPI 主入從出 MISO",
  "help.tag.sck": "SPI 時脈 SCK",
  "help.tag.sda": "I²C 資料 SDA",
  "help.tag.scl": "I²C 時脈 SCL",
  "help.tag.led": "板上 LED「L」",
  "help.tag.aref": "類比參考電壓 AREF",
  "help.tag.ioref": "IO 準位參考 IOREF",
  "help.tag.reset": "重設（低準位有效）",
  "help.tag.treset": "重設 RESET（低準位有效）",
  "help.tag.v5": "5 V 電源",
  "help.tag.v33": "3.3 V 電源輸出",
  "help.tag.vin": "外部電源輸入 VIN",
  "help.tag.gnd": "地 GND",
  "help.tag.vcc": "電源 VCC",
  "help.tag.usi_di": "USI 資料輸入 DI / I²C SDA",
  "help.tag.usi_do": "USI 資料輸出 DO",
  "help.tag.usi_sck": "USI 時脈 USCK / I²C SCL",
  "help.tag.xtal": "外部石英振盪器腳位",
  "help.tag.ain": "類比比較器輸入",
  "help.tag.taref": "外部參考電壓 AREF",
  "help.tag.tled": "Digispark 等板的板上 LED",
  "help.tag.icsp": "ICSP 線上燒錄 (ISP) 介面",
  "help.note.d0d1": "D0/D1 與板上的 USB 轉串列埠晶片相連：上傳程式和 `Serial` 通訊都要用它們，外接電路可能導致上傳失敗。模擬中 D0/D1 可當一般 IO，`Serial` 直接連到串列埠監視器。",
  "help.note.tone": "`tone()` 佔用 Timer2，發聲期間 D3 和 D11 的 PWM 失效。",
  "help.note.servo": "Servo 函式庫佔用 Timer1，使用後 D9 和 D10 都不能再 `analogWrite()`（與伺服馬達接在哪個腳無關）。",
  "help.note.d13": "板上 LED「L」由 D13（`LED_BUILTIN`）驅動，R3 上經運算放大器緩衝。D13 同時是 SPI 的 SCK，使用 SPI 時 LED 會閃。",
  "help.note.a4a5": "A4/A5 同時是 I²C 的 SDA/SCL（R3 在 AREF 旁另有一組 SDA/SCL 排針，與 A4/A5 內部相連）。使用 I²C 時它們不能再作類比輸入。",
  "help.note.v5": "來自板上 5 V 穩壓器（VIN/DC 供電時）或 USB。可給感測器和小模組供電；USB 供電時全板受 500 mA 自恢復保險絲限制。也能從這裡輸入穩壓的 5 V，但會繞過穩壓器和保護電路。",
  "help.note.v33": "板上 3.3 V 穩壓輸出，最大 50 mA。",
  "help.note.vin": "外部電源輸入（DC 插座經二極體接到這裡），建議 7–12 V，極限 6–20 V。低於 7 V 時 5 V 可能不穩，高於 12 V 穩壓器容易過熱。",
  "help.note.gnd": "所有 GND 相互連通。外部電源（電池、馬達電源）的負極必須與 Arduino 的 GND 相連（共地），訊號才有共同的參考。",
  "help.note.reset": "拉低即重設，板上的重設按鈕也接在這裡。模擬元件沒有此腳，可用程式編輯器裡的「重設」按鈕代替。",
  "help.note.aref": "外部類比參考電壓輸入（0–5 V），配合 `analogReference(EXTERNAL)` 使用；接外部電壓前必須先設為 EXTERNAL，否則可能損壞晶片。模擬元件沒有此腳，EXTERNAL 按 VCC (5 V) 處理。",
  "help.note.ioref": "告訴擴充板本板的 IO 準位（Uno 上接 5 V）。模擬元件沒有此腳。",
  "help.note.sdascl": "R3 新增的 I²C 排針，與 A4/A5 電氣上相同。模擬器不支援 I²C（Wire 函式庫）。",
  "help.note.icsp": "6 針 ISP 線上燒錄 (ISP) 介面，用於燒錄開機載入程式 (bootloader)或用燒錄器直接下載程式。模擬中不需要。",
  "help.note.pb5": "預設是 RESET（低準位重設，內部上拉），不能當一般 IO；模擬中把它拉到 0.3·VCC 以下會讓晶片保持重設。燒錄 RSTDISBL 熔絲後才成為（驅動能力較弱的）IO，但之後不能再用 ISP 燒錄，需要高壓燒錄器才能恢復。模擬中可在屬性裡勾選「PB5 作一般 IO」。",
  "help.note.pb34": "PB3/PB4 也是外部石英振盪器腳位：使用外部石英振盪器時不能當 IO。預設使用內部 RC 振盪器，所以可以自由使用。",
  "help.note.pb0": "物理第 5 腳：PWM (OC0A)、USI 的 DI / I²C SDA、ISP 燒錄的 MOSI，也可作外部 AREF（此時不能再作 IO）。",
  "help.note.pb1": "物理第 6 腳：PWM (OC0B / OC1A)、USI 的 DO、ISP 燒錄的 MISO。Digispark 等開發板的板上 LED 接在這裡。",
  "help.note.pb2": "物理第 7 腳：唯一的外部中斷 INT0、類比輸入 A1 (ADC1)、USI 時脈 USCK / I²C SCL、ISP 燒錄的 SCK。",
  "help.note.vcc": "供電 2.7–5.5 V（ATtiny85V 為 1.8–5.5 V），時脈越高需要的電壓越高（20 MHz 需 4.5 V 以上）。VCC 與 GND 之間就近接 100 nF 去耦合電容。",
  "help.lim.arduino.1": "每個 IO 腳位：建議 ≤ 20 mA，絕對最大 40 mA，超過可能永久損壞埠。",
  "help.lim.arduino.2": "所有腳位電流之和（VCC/GND 總電流）不超過 200 mA。",
  "help.lim.arduino.3": "腳位電壓不得超出 −0.5 V … VCC + 0.5 V；輸入低準位 < 0.3·VCC（1.5 V），高準位 > 0.6·VCC（3 V）。",
  "help.lim.arduino.4": "內部上拉電阻 20–50 kΩ（`INPUT_PULLUP`）。",
  "help.lim.arduino.5": "類比輸入 0–5 V（預設參考 = VCC），10 位 → 0–1023，每檔約 4.9 mV；訊號源阻抗建議 ≤ 10 kΩ。",
  "help.lim.arduino.6": "VIN / DC 插座：建議 7–12 V，極限 6–20 V；USB 供電為 5 V，帶 500 mA 自恢復保險絲。",
  "help.lim.arduino.7": "3.3V 腳位最大 50 mA；5V 腳位能給出多少電流取決於電源（USB 時全板 ≤ 500 mA，VIN 供電時受穩壓器發熱限制）。",
  "help.lim.arduino.8": "ATmega328P：16 MHz，Flash 32 KB（bootloader 佔 0.5 KB），SRAM 2 KB，EEPROM 1 KB。",
  "help.lim.attiny85.1": "每個 IO 腳位：建議 ≤ 20 mA，絕對最大 40 mA；VCC/GND 總電流 ≤ 200 mA。",
  "help.lim.attiny85.2": "工作電壓 2.7–5.5 V（ATtiny85V：1.8–5.5 V）；10 MHz 以下 2.7 V 即可，20 MHz 需要 4.5–5.5 V。",
  "help.lim.attiny85.3": "腳位電壓 −0.5 V … VCC + 0.5 V；內部上拉 20–50 kΩ。",
  "help.lim.attiny85.4": "ADC：10 位，4 路單端輸入 ADC0–ADC3 = PB5 / PB2 / PB4 / PB3；參考電壓可選 VCC、內部 1.1 V、內部 2.56 V 或 PB0 上的外部 AREF。",
  "help.lim.attiny85.5": "儲存：Flash 8 KB、SRAM 512 B、EEPROM 512 B。",
  "help.lim.attiny85.6": "時脈：出廠為內部 8 MHz RC ÷ 8 = 1 MHz（CKDIV8 熔絲）；可改為內部 8 MHz、PLL 16 MHz，或外部石英振盪器（佔用 PB3/PB4）。",
  "help.sim.ok": "模擬支援：`pinMode` / `digitalWrite` / `digitalRead`（含 `INPUT_PULLUP`）、`analogRead`（10 位）、`analogWrite`（PWM 頻率與真實晶片一致）、`millis` / `micros` / `delay`、`tone` / `noTone`、`pulseIn`、`shiftOut`、Servo、LiquidCrystal、LiquidCrystal_I2C、DHT、OneWire + DallasTemperature、`Serial`（串列埠監視器）等。腳位的輸出電阻、上拉電阻和電流都參與電路求解，單腳超過 40 mA 會給出警告。",
  "help.sim.no.1": "外部中斷 `attachInterrupt()`：編譯時提示不支援，請改用輪詢或 `millis()`。",
  "help.sim.no.3": "函式庫對定時器的副作用（tone 使 D3/D11 的 PWM 失效、Servo 使 D9/D10 的 PWM 失效）只在說明中提示，模擬中不會出現。",
  "help.sim.no.4": "Uno 元件沒有 RESET、AREF、IOREF、單獨的 SDA/SCL 排針和 ICSP 介面；`analogReference(EXTERNAL)` 按 VCC 處理，`INTERNAL` = 1.1 V。",
  "help.sim.no.5": "ATtiny85 沒有硬體串列埠：模擬中的 `Serial` 是虛擬的，只用於把除錯資訊輸出到串列埠監視器。",
  "help.sim.no.6": "腳位過流不會「燒壞」晶片：模擬只給出警告，請對照電氣極限自行檢查。",
  "help.sim.no.7": "EEPROM、睡眠模式、看門狗、熔絲設定以及直接操作暫存器（如 `PORTB`、`DDRB`）不支援。",
  "help.sim.no.8": "不模擬指令執行時間：程式碼視為瞬間完成，只有 `delay()`、`millis()` 等推動時間；無窮迴圈超過運算上限會報錯。",
  "help.usage.intro": "每一節給出接線要點和一段可以直接複製的程式碼，並連結到相關範例。",
  "help.u.power.t": "供電方式",
  "help.u.power.1": "Uno 有三種供電方式：① USB 5 V（最簡單，全板 ≤ 500 mA）；② DC 插座或 VIN 接 7–12 V，經板上穩壓器得到 5 V；③ 直接向 5V 腳位輸入穩壓的 5 V（繞過穩壓器和保護，接錯會損壞板子）。模擬中可在屬性裡選擇 USB 或 VIN 供電。",
  "help.u.power.2": "5V 和 3.3V 腳位可以給感測器、小模組供電，但不要用它們驅動馬達、多個伺服馬達或大功率 LED：這些負載會拉低電壓，使微控制器重設。大電流負載請用獨立電源，並把電源負極與 Arduino 的 GND 相連（共地）。",
  "help.u.power.3": "ATtiny85 只是一顆晶片，沒有穩壓器：VCC 要直接接 2.7–5.5 V，例如 3 節 AA 電池（4.5 V）、USB 5 V 或單節鋰電池（3.0–4.2 V）。電壓太低晶片不會啟動（模擬顯示 OFF），超過 5.5 V 可能損壞。",
  "help.u.power.4": "每顆晶片的 VCC 與 GND 之間就近放一隻 100 nF 去耦合電容。馬達等感性負載最好使用與微控制器分開的電源，至少要加大電容濾波。",
  "help.u.dout.t": "數位輸出與 LED 限流電阻",
  "help.u.dout.1": "先 `pinMode(pin, OUTPUT)`，再用 `digitalWrite(pin, HIGH)` / `LOW` 輸出約 5 V / 0 V。輸出腳既能輸出電流也能吸收電流，每腳建議不超過 20 mA。",
  "help.u.dout.2": "LED 必須串聯限流電阻：R = (Vcc − Vf) / I。例如 5 V、紅色 LED Vf ≈ 2 V、取 10 mA：R = (5 − 2) / 0.01 = 300 Ω，選常用值 330 Ω；用 220 Ω 約 14 mA 也可以。藍、白色 LED 的 Vf ≈ 3 V，同樣電流約需 200 Ω。",
  "help.u.dout.3": "LED 長腳（陽極 +）經電阻接腳位，短腳（陰極 −）接 GND，此時 HIGH = 亮；也可以把 LED 接到 5V，由腳位吸收電流，此時 LOW = 亮。一個腳位要驅動多顆 LED 或超過 20 mA 的負載時，請用電晶體或 MOSFET。",
  "help.u.din.t": "按鍵輸入：上拉、下拉與去彈跳",
  "help.u.din.1": "`INPUT_PULLUP` 開啟內部 20–50 kΩ 上拉電阻：按鍵一端接腳位、另一端接 GND，不需要外接電阻。沒按時讀到 HIGH，按下讀到 LOW（邏輯相反）。這是最簡單的接法。",
  "help.u.din.2": "下拉接法：按鍵接在 5V 與腳位之間，腳位再經 10 kΩ 接 GND，`pinMode(pin, INPUT)`，按下讀到 HIGH。注意 `INPUT` 模式下腳位懸空時讀數會隨機跳動，必須有上拉或下拉電阻。",
  "help.u.din.3": "機械按鍵按下和鬆開時會抖動幾毫秒，一次按壓可能被讀成好幾次。去彈跳方法：讀數變化後等 20–50 ms 仍不變才確認（用 `millis()` 計時，不要用長時間的 `delay()`），或在硬體上加 RC 濾波。範例「按鍵去彈跳」演示了軟體去彈跳。",
  "help.u.ain.t": "類比輸入：電位器、分壓、光敏/熱敏電阻",
  "help.u.ain.1": "`analogRead(A0)` 返回 0–1023，對應 0 V 到參考電壓（預設 VCC = 5 V）：電壓 = 讀數 × 5.0 / 1024。一次轉換約 100 µs。`analogReference(INTERNAL)` 改用內部 1.1 V 參考，適合測量小電壓。",
  "help.u.ain.2": "電位器：兩端分別接 5V 和 GND，中間滑動端接 A0，旋轉時讀數在 0–1023 之間變化。分壓電阻：Vout = Vin × R2 / (R1 + R2)，可以把高於 5 V 的電壓（如 12 V 電池）降到 0–5 V 再測，但要保證輸入不超過 VCC。",
  "help.u.ain.3": "光敏電阻 (LDR) 和熱敏電阻 (NTC) 要與一個固定電阻串聯成分壓電路，中點接類比腳；固定電阻取感測器在中間工作點的阻值，常用 10 kΩ。LDR 接在下方時越暗電壓越高；NTC 溫度越高阻值越小。可以用 `map()` 把讀數換算成需要的範圍。",
  "help.u.ain.4": "ADC 要求訊號源阻抗 ≤ 10 kΩ，分壓電阻太大時讀數不穩，可在類比腳與 GND 之間加 100 nF 電容。A0–A5 也能當普通數位腳使用（D14–D19）。ATtiny85 的類比腳是 A1 (PB2)、A2 (PB4)、A3 (PB3)；A0 (PB5) 是重設腳，一般不用。",
  "help.u.pwm.t": "PWM：調光與調速",
  "help.u.pwm.1": "`analogWrite(pin, 0–255)` 在帶 ~ 的腳位輸出 PWM 方波：佔空比 = 值 / 255，平均電壓 ≈ 5 V × 值 / 255。Uno 的 D5、D6 約 980 Hz，D3、D9、D10、D11 約 490 Hz；ATtiny85 可用 PB0、PB1、PB4。",
  "help.u.pwm.2": "PWM 適合調 LED 亮度（人眼看到的是平均亮度）和馬達轉速；它不是真正的類比電壓，需要平滑電壓時請加 RC 低通濾波。在不帶 ~ 的腳位上呼叫 `analogWrite()` 時，值 < 128 輸出 LOW，否則輸出 HIGH。",
  "help.u.pwm.3": "值為 0 或 255 時輸出恆定的 LOW / HIGH。人眼對亮度的感覺是非線性的，呼吸燈用平方曲線會更自然。可以用示波器觀察 PWM 波形（範例「電位器調光」）。",
  "help.u.motor.t": "馬達：電晶體 / MOSFET 驅動與續流二極體",
  "help.u.motor.1": "腳位只能提供約 20 mA，不能直接驅動馬達。用 NPN 電晶體或 N 通道 MOSFET 做低側開關：負載接在電源 + 與汲極 (D) 之間，源極 (S) 接 GND，閘極 (G) 經 100–220 Ω 接 PWM 腳位，再用 10 kΩ 下拉到 GND，防止通電或重設時腳位懸空導致誤啟動。",
  "help.u.motor.2": "請選「邏輯準位」MOSFET（如 IRLZ44N，5 V 閘極電壓即可充分導通）；IRF540 等普通 MOSFET 的導通電阻是按 10 V 閘極電壓標定的，5 V 下導通不充分會發熱。用電晶體時基極串聯約 1 kΩ 電阻。",
  "help.u.motor.3": "馬達、繼電器線圈、電磁閥都是感性負載，斷開瞬間會產生很高的反向電壓，必須在負載兩端反向並聯續流二極體（如 1N4007，陰極接電源 +）。馬達電源的負極必須與 Arduino GND 相連。需要正反轉時使用 H 橋驅動（如 L298N、TB6612）。",
  "help.u.relay.t": "繼電器與大功率負載",
  "help.u.relay.1": "繼電器用小電流的線圈控制大電流、高電壓的觸點：COM 是公共端，NO 常開（線圈通電時與 COM 接通），NC 常閉。觸點電路與微控制器電氣隔離，可以開關 12 V 燈泡或市電電器。",
  "help.u.relay.2": "繼電器模組內建電晶體、續流二極體和指示燈，VCC/GND 接 5V/GND，IN 接任意數位腳即可。注意觸發方式：很多模組是低準位觸發（IN = LOW 時吸合）；模擬中的模組可在屬性裡選擇高/低準位觸發。",
  "help.u.relay.3": "裸繼電器的線圈電流通常在 70 mA 以上，不能直接接腳位，要用電晶體驅動並加續流二極體。操作 220 V 市電非常危險，請使用帶外殼的成品模組，並注意觸點的額定電流。",
  "help.u.tone.t": "蜂鳴器與 tone()",
  "help.u.tone.1": "`tone(pin, 頻率)` 在任意數位腳輸出 50% 佔空比的方波，`tone(pin, 頻率, 時長)` 到時自動停止，`noTone(pin)` 停止發聲。同一時間只能有一個 `tone()`；它佔用 Timer2，會使 D3/D11 的 PWM 失效。",
  "help.u.tone.2": "被動式蜂鳴器和小喇叭需要 `tone()` 產生的方波才能發聲，音調由頻率決定；主動式蜂鳴器內部帶振盪器，只要 `digitalWrite(HIGH)` 就響，但音調固定。",
  "help.u.tone.3": "蜂鳴器串聯約 100 Ω 電阻限流；8 Ω 喇叭電流太大，要經電晶體驅動。常用音符頻率：C4 262、D4 294、E4 330、F4 349、G4 392、A4 440、B4 494、C5 523 Hz。",
  "help.u.servo.t": "伺服馬達",
  "help.u.servo.1": "伺服馬達有三根線：訊號（橙/黃）、電源 +（紅）、GND（棕/黑）。訊號是週期約 20 ms（50 Hz）的脈衝，脈寬通常 1–2 ms 對應轉角，Servo 函式庫預設把 544–2400 µs 對應到 0–180°。用法：`attach(pin)` 之後 `write(角度)`。",
  "help.u.servo.2": "Servo 函式庫佔用 Timer1，使用後 D9、D10 不能輸出 PWM（伺服馬達訊號線可接任意數位腳）。Uno 最多可接 12 個伺服馬達。",
  "help.u.servo.3": "伺服馬達啟動和堵轉時電流可達幾百 mA 甚至 1 A 以上。SG90 這類小伺服馬達接一個可由 5V 腳位供電；多個或大伺服馬達請用獨立的 5–6 V 電源並共地，在伺服馬達電源端並聯 100–470 µF 電容可以減少重設。",
  "help.u.lcd.t": "LCD1602 液晶顯示器",
  "help.u.lcd.1": "LCD1602（HD44780 控制器）在 4 位模式下只需 6 根訊號線：RS、E、D4–D7，RW 接 GND（只寫）；也可以用 7 個引數的寫法把 RW 接到腳位。`LiquidCrystal lcd(rs, en, d4, d5, d6, d7)`，然後 `lcd.begin(16, 2)`、`lcd.setCursor(列, 行)`、`lcd.print()`、`lcd.clear()`。",
  "help.u.serial.t": "串列埠除錯",
  "help.u.serial.1": "`Serial.begin(9600)` 開啟串列埠（鮑率要與串列埠監視器一致），`Serial.print()` / `println()` 輸出文字和數值。這是除錯程式最常用的方法：列印變數、程式走到了哪裡、感測器讀數。",
  "help.u.serial.2": "`Serial.available()` 返回已收到的位元組數，`Serial.read()` 讀一個位元組，`Serial.readStringUntil('\\n')` 讀一行。模擬中在串列埠監視器的輸入框裡傳送文字。",
  "help.u.serial.3": "Uno 的串列埠佔用 D0/D1，使用串列埠時不要在這兩個腳上接其他電路。列印太頻繁會拖慢程式（9600 鮑約每毫秒 1 個字元），可以用 `millis()` 控制列印間隔。ATtiny85 沒有硬體串列埠，模擬中的 `Serial` 僅用於除錯。",
  "help.u.millis.t": "millis() 非阻塞定時",
  "help.u.millis.1": "`delay()` 期間程式什麼也做不了（不能讀按鍵，也不能更新其他 LED）。`millis()` 返回通電以來的毫秒數，用「目前時間 − 上次時間 ≥ 間隔」判斷是否到時，就能同時處理多件事。",
  "help.u.millis.2": "時間變數要用 `unsigned long`。用減法比較 `millis() - last >= INTERVAL`，約 49.7 天後計數迴繞時也正確；不要寫成 `millis() >= last + INTERVAL`。",
  "help.u.millis.3": "每個任務一個時間變數，就組成了簡單的狀態機：範例「millis() 多工」讓兩顆 LED 以不同節奏閃爍並同時列印運行時間，「按鍵去彈跳」也用同樣的方法。需要微秒精度時用 `micros()`。",
  "help.ex.examples": "相關範例",
  "help.ex.intro": "「載入到畫布」會替換目前電路並開始模擬；「插入編輯器」把程式碼放進目前晶片的程式編輯器（尚未上傳，可修改後再上傳）；「複製程式碼」複製到剪貼簿。",
  "help.ex.wiring": "接線",
  "help.ex.usage": "相關用法",
  "help.ex.code": "程式碼",
  "help.ex.load": "載入到畫布",
  "help.ex.insert": "插入編輯器",
  "help.ex.copy": "複製程式碼",
  "help.ex.other": "檢視 {board} 的範例（{n} 個）→",
  "help.toast.inserted": "程式碼已插入 {chip} 的編輯器，點「編譯並上傳」生效",
  "help.toast.mismatch": "已插入，但這段程式碼是為 {board} 編寫的，腳位可能不對應",
  "help.toast.copied": "程式碼已複製到剪貼簿",
  "help.toast.copy_failed": "複製失敗，請在程式碼框中手動選擇後複製",
  "help.toast.no_chip": "畫布上沒有單晶片：請先放一塊開發板或晶片，或使用「載入到畫布」",
  "help.w.anode": "陽極（+，長腳）",
  "help.w.cathode": "陰極（−）",
  "help.w.onboard_led": "板上 LED（L）",
  "help.w.red_led": "紅色 LED",
  "help.w.yellow_led": "黃色 LED",
  "help.w.green_led": "綠色 LED",
  "help.w.white_led": "白色 LED",
  "help.w.all_cathodes": "所有 LED 的陰極",
  "help.w.internal_pullup": "使用內部上拉",
  "help.w.pot_ends": "兩端",
  "help.w.wiper": "中間滑動端",
  "help.w.gate": "閘極 G",
  "help.w.drain": "汲極 D",
  "help.w.source": "源極 S",
  "help.w.flyback": "與馬達反向並聯（陰極接電源 +）作續流",
  "help.w.common_gnd": "共地",
  "help.w.servo_sig": "訊號線",
  "help.w.servo_vcc": "電源線",
  "help.w.servo_gnd": "地線",
  "help.w.backlight": "背光",
  "help.w.contrast": "對比度",
  "help.w.pin_n4": "第 4 腳",
  "help.w.pin_n5": "第 5 腳",
  "help.w.pin_n6": "第 6 腳",
  "help.w.pin_n8": "第 8 腳",
  "ex.arddebounce": "單晶片：按鍵去彈跳 切換 LED (millis)",
  "ex.ardnight": "單晶片：光敏電阻小夜燈 (LDR → PWM)",
  "ex.ardmulti": "單晶片：millis() 多工 (不用 delay)",
  "ex.ardmotor": "單晶片：MOSFET 驅動直流馬達調速 (PWM)",
  "ex.ardrelay": "單晶片：繼電器模組 定時開關 12V 燈",
  "ex.ardtone": "單晶片：被動式蜂鳴器播放旋律 (tone)",
  "ex.tinyfade": "單晶片：ATtiny85 PWM 呼吸燈",
  "exd.arddebounce": "每按一次 D2 上的按鍵就切換 D8 上 LED 的亮滅：輸入保持 30 ms 不變才確認，避免抖動造成多次切換；串列埠列印按鍵次數。",
  "exd.ardnight": "5V → 10 kΩ → A0 → 光敏電阻 → GND 組成分壓電路：越暗讀數越高，D9 的 PWM 讓白色 LED 越亮。在屬性中調節光敏電阻的「光照強度」試試。",
  "exd.ardmulti": "完全不用 delay()：D8 的 LED 每 250 ms 翻轉，D7 的 LED 每 700 ms 翻轉，每秒列印一次運行時間，三件事同時進行。",
  "exd.ardmotor": "電位器 → A0 → D9 的 PWM → 邏輯準位 MOSFET IRLZ44N → 直流馬達。馬達用獨立的 6 V 電池並與 Arduino 共地，1N4007 續流二極體吸收關斷時的反向電壓。",
  "exd.ardrelay": "D7 控制繼電器模組（高準位觸發），讓 12 V 燈泡亮 2 秒、滅 2 秒。燈泡迴路與 Arduino 電氣隔離，腳位只需提供幾 mA。",
  "exd.ardtone": "D8 經 100 Ω 驅動被動式蜂鳴器，用 tone() 播放一段 16 拍的旋律（0 表示休止），串列埠列印每個音符的頻率。",
  "exd.tinyfade": "ATtiny85 在 PB0（第 5 腳）和 PB1（第 6 腳）輸出 PWM：黃色 LED 漸亮時綠色 LED 漸暗，反覆循環。",
  "wc.title": "導線顏色",
  "wc.n_wires": "已選 {n} 根導線",
  "wc.red": "紅色",
  "wc.black": "黑色",
  "wc.blue": "藍色",
  "wc.green": "綠色",
  "wc.yellow": "黃色",
  "wc.orange": "橙色",
  "wc.white": "白色",
  "wc.purple": "紫色",
  "wc.gray": "灰色",
  "wc.brown": "棕色",
  "wc.custom": "自訂顏色…",
  "wc.hint": "新畫的導線使用最近選擇的顏色；顏色不同的導線不會被自動合併。"
});
